### ISSUE TITLE
Birthday notifications

### ISSUE THREAD

**Issue by Nygu** [diaspora/diaspora#1649]
If current day == date of birth as set by Bob, send a notification to the notification page of Bob's friends. Include the option to turn mails about birthdays off through the Settings page.

_____
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/197123-birthday-notifications?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github).

**Comment by jhass** [comment]
I'm not sure how useful this is, many people seem to use incomplete or fake dates on diaspora.

**Comment by Flaburgan** [comment]
The birth date fields in diaspora* are separated in day, month and year. I guess if at least day and month are filled, we are able to determine if today is the birthday of a user.
So I propose the following spec: each new day, for each user we check if today == dob. If so, we add a new notification in the notification dropdown for each user who has this user in at least one aspect. If the notification sends or not an email can be set as for all other notifications in the setting panel.

**Comment by mapeveri** [comment]
@Flaburgan This issue I like to start. It's okay?

**Comment by Flaburgan** [comment]
Nobody is working on it so yes you can take it. You will need to create a new type of notification for birthday.

**Comment by netagonen** [comment]
Hi! @Rete2 and me want to work on this issue. Is someone already working on it?

**Comment by SuperTux88** [comment]
It seems that nobody is working on that, so you can take it.

**Comment by netagonen** [comment]
Hi,
We are working on the issue and have few questions:
1. We are using the `contact` object in order to send notifications to the birthday person contacts. The `contact` have `receiving` and `sharing` attributes and we need some clarifications about them. We are a bit unsure if receiving means that the user is receiving from the person or if it's the other way around. Specifically, when we test the worker for this notification, we want to test the case where the birthday person is not sharing/receiving with a contact. Which of these attributes should we set to false in the test? Should we test both? You can see the code [here]: (https://github.com/codebearsteam/diaspora/blob/birthday_notification/spec/workers/check_birthday_spec.rb), lines 42 and 49. Accordingly, we would need to change the condition in the `check_birthday` [worker] (https://github.com/codebearsteam/diaspora/blob/birthday_notification/app/workers/check_birthday.rb) line 14.
2. In the `check_birthday` worker we are iterating over all the profiles that are in a pod in order to check their birthday. We were wondering if it would be more efficient to add an index for the birthday, what do you think?
Thanks!

**Comment by SuperTux88** [comment]
> The `contact` have `receiving` and `sharing` attributes and we need some clarifications about them.

Yes, contacts are a bit confusing. `receiving` means, that the `user` reads posts of the `person` (and shares with the `person`). And `sharing` means, that the `person` shares with the `user` (so the other direction).

For the birthday notifications, you need to check that both are true, the person whose birthday it is, needs to be `sharing` with the user and the user needs to be `receiving` (being interested in) the persons birthday.

By the way, you can directly query the contacts from the database with these flags (in [check_birthday.rby](https://github.com/codebearsteam/diaspora/blob/birthday_notification/app/workers/check_birthday.rb#L13), so you only have the contacts you want for your loop, then you don't need the `if` in the loop:
```ruby
profile.person.contacts.where(sharing: true, receiving: true)
```

> We were wondering if it would be more efficient to add an index for the birthday, what do you think?

I just checked that with my production database, and with 87598 profiles the query needed 0.2091 seconds with mysql, and I think that's OK for once per day.

But there is another problem with your query: `date_part` only works with postgres, so you need a different solution for mysql, I used `MONTH(birthday)` and `DAY(birthday)` for my test. You can see if the post runs with postgres with `AppConfig.postgres?`.

> From what we have searched, it seems like this functionality is tested for all email types together. Is this true or should we test this functionality specifically for birthday notification emails?

I think you are talking about these tests?

https://github.com/diaspora/diaspora/blob/e82690963dc55d10491b8da6b4fc0b6f397bea6d/spec/controllers/users_controller_spec.rb#L215-L234

This generates a test for each email type. So they are already tested each individually. All you need to do is to add your notification type here, then it will be tested automatically:

https://github.com/diaspora/diaspora/blob/e82690963dc55d10491b8da6b4fc0b6f397bea6d/app/models/user_preference.rb#L8-L17

**Comment by goobertron** [comment]
> 3. We added to the user/edit page a checkbox to enable the user not to get birthday notification emails.

Please could you also add an opt-out that Bob can set to prevent notifications being sent to his contacts on his birthday? So there are two opt-outs: 1. Don't send birthday notifications to my contacts; 2. Don't receive birthday notifications from my contacts.

**Comment by SuperTux88** [comment]
@goobertron that change would need federation changes. And we would need to first add this change then, and wait so people can set that option and then in half a year we can add the notifications for birthday.

But I don't think that this is needed, because when people don't want that others know when their birthday is, they can simply not set it (it's optional), and then no notifications will be sent. That doesn't need any changes. When you publish your birthday, people can also add it manually to their calendar and set a reminder for it, so they receive notifications for it, and you can't prevent them from adding the date to the calendar.

**Comment by netagonen** [comment]
Hi
When we run the rspec we have some failures. We traced the problem to the [notification_service.rb](https://github.com/diaspora/diaspora/compare/develop...codebearsteam:birthday_notification#diff-8aed2077027ea284d8fb0e97a2a2c4f4). We added our Notification as a value to the key Contact since it need the attributes from this class. But it seems that every time the StartedSharing is called in the tests, also ContactsBirthday is called and causes failures. 
It seems that there are two options: either create a Birthday class and add it ass a key to the NOTIFICATION_TYPES hash, or to do something similar to the Comment key, where there are three Notification types in the hash. 
What do you think is a better solution? And how can we implement it the code?

**Comment by SuperTux88** [comment]
`NOTIFICATION_TYPES` is for what notifications are created, when you receive a entity in the federation logic. And when we receive a `Contact` we need to send a `StartedSharing`-notification.

https://github.com/diaspora/diaspora/blob/26a9e50ef935628c800f9a21d345057556fa5c31/app/workers/receive_local.rb#L12

But we don't need to send a `ContactsBirthday` when we receive a `Contact`. Birthdays are triggered locally from a cronjob, so you don't need to add it to `NOTIFICATION_TYPES`.
