### ISSUE TITLE
When a pod gets a 404 when federating a private message, it should remove the user from its database

### ISSUE THREAD

**Issue by grinapo** [diaspora/diaspora#2021]
pod was reinstalled, so the users got new id's. now:
Started POST "/receive/users/0e8377826c716733/" for ____ at Thu Sep 22 00:43:56 +0200 2011 pid=7309  time=1316645036 
Completed 404 Not Found in 439ms (Views: 1.8ms | ActiveRecord: 7.8ms) pid=7309  time=1316645037 

Since the name of the contact is the same, the otherpod search finds the person: the old id doesn't exist anymore, and it is not reloaded (refreshed, overwritten, whatever) despite the 404 error. Especially when the contact isn't referenced anymore.
##

**Comment by Flaburgan** [comment]
@SuperTux88 is this handled now?

**Comment by SuperTux88** [comment]
No, and I think we shouldn't auto-close accounts. If a pod is down for some days, we would close all it's users (and closing is a final action, it can't be undone). You can now shut down your pod for a year, start it again and continue using it like before, everything would still be working (as long as you keep the database). So I think we should keep the current behavior (after knowing a user with it's key, only change something with a valid signature).

So I think we can close this issue, because we have #6791 for when the pod simply didn't receive a "account deletion" message, and the pod can resend this message when it receives a message for a closed account.
