### ISSUE TITLE
Displaying Facebook content as one of filters on the left side

### ISSUE THREAD

**Issue by memarko** [diaspora/diaspora#3009]
It is not an issue it is just a feature.
I would just like to have everything in  one place, So one facebook filter on left side which can display posts from Facebook.
Is it possible to read posts just like in Facebook home page through API? Maybe some notifications also?

I think this integration can bring more people in and would be easier for them to migrate from biggest network to Diaspora.

Is it too much?  Anyway this feature looks like reinventing Facebook. :)

**Comment by jaywink** [comment]
I doubt this is even workable and thus IMHO should be closed... From Facebook permission docs:

> ## read_stream
> 
> Provides access to read the posts in a person's News Feed, or the posts on their Profile.
> 
> ### Review
> 
> If your app requests this permission Facebook will have to review how your app uses it.
> 
> ### Limited Use
> 
> This permission is granted to apps building a Facebook-branded client on platforms where Facebook is not already available. For example, Android and iOS apps will not be approved for this permission. In addition, Web, Desktop, in-car and TV apps will not be granted this permission.

diaspora* is a web app - and thus, will not ever be granted this permission by Facebook.

**Comment by metafarion** [comment]
CybershamanX is absolutely correct here, and I'm a bit concerned that the Diaspora devs don't seem to realize how important this kind of functionality is in getting people to switch.  It is a DEAL-BREAKER that Facebook content be available to new users, at least as an option, regardless of what privacy issues this might raise.  The number 1 priority for participating in social media is to be connected, and regardless of what fantastic ideals we might be pitching for joining a non-commercial decentralized one that doesn't spy on you or advertise.... it's plainly obvious that most people trade all of those things for the connectivity with just a little grumbling.  They go where the people are.

Even speaking as someone who really believes 1000% in Diaspora's purpose and would love to see Facebook burn to the ground, I am STILL reluctant to join because it severs so many of my connections.  I can proselytize to my friends until I'm blue in the face, but they won't switch for the same reason I hesitated, only they DON'T have a tin-foil hat like mine to motivate them.  For so many people, myself included, just keeping up on Facebook is enough work, I don't need another news feed to read in a separate platform where nobody I know lives.

If you want a success story here, I'm reminded of the way Apple is slowly unseating the incumbant SMS protocol by providing a completely user-experience-transparent alternative (iMessage) that most people have no idea they're using.  When iOS devices message each other, they use iMessage, when they message other mobile devices they revert to SMS.  This switch is completely invisible to the user, and it would not have taken hold if it had been otherwise.  Now they've amassed such a user base using iMessage that it is practical, even a selling point that Wifi-only devices and Macs can communicate via this protocol.

That's the kind of connectivity we need.  Regardless of how it might clutter up the Stream or compromise privacy (only for correspondence via the FB protocol yeah?), it is absolutely essential and you will not see Diaspora unseat Facebook without it.  We could even be pushy in clever little ways, like a little reminder at the bottom of FB correspondence that warns of an insecure connection, or some other "bad network" "good network" highlighting.  Privacy will come gradually instead of a complete detachment from one's less progress-minded peers.

**Comment by svbergerem** [comment]
@metafarion Did you read [jaywink's comment](https://github.com/diaspora/diaspora/issues/3009#issuecomment-75374504)? I think the Facebook permission docs are pretty clear about this topic. That means we are not able to display Facebook content because Facebook doesn't allow us to do that. For me this is a `won't fix` and I think we should close this issue. Any objections?

**Comment by denschub** [comment]
Affirm. Building applications displaying Facebook stream contents where possible in the past, but that changed a year ago.

**Comment by jhass** [comment]
Yes, it's actually pretty clear, I close this, we're not allowed to do it.

**Comment by petko10** [comment]
In order to close this huge gap for the new users (I actually have no incentive to use Diaspora before I can integrate FB in it) I want to mention the possibility for a hack around - a browser extension. The browser extension would rip the posts from the actual FB web page and display them in the diaspora news feed. I don't think it would be against any policies, since it's all happening on the user side. The ripping part won't be an easy task, but such a set of browser extensions (maybe using a common JS library) would benefit many projects that want to use FB content, so I guess with enough people getting behind the idea it would be possible.

**Comment by djcf** [comment]
+1. I think this is an excellent idea and would love to work on such a feature.

**Comment by metafarion** [comment]
Yeah, that seems like a decent solution in the face of an impassable TOS.  I wonder if it would have to be visibly unaffiliated with the Diaspora project to escape FB's wrath.

**Comment by jaywink** [comment]
>  I wonder if it would have to be visibly unaffiliated with the Diaspora project to escape FB's wrath.

Any solution that would be code as a browser extension and not core diaspora* code would *automatically* be not involved with the diaspora project officially.

So go ahead do what you like! :)
