### ISSUE TITLE
Cannot send new messages

### ISSUE THREAD

**Issue by galactica132** [diaspora/diaspora#3452]
Hello all i know that was discussed many times before. But i have a weird problem when i am trying to send new message to a user. 
OS: Ubuntu 11.10 64 bit
production.log contents

```
Started GET "/conversations/new?_=1342302293486" for 111.40.6.98 at Sun Jul 15 01:49:52 +0400 2012
Processing by ConversationsController#new as */*
  Parameters: {"_"=>"1342302293486"}
  Rendered conversations/new.haml (4.8ms)
Completed 200 OK in 19ms (Views: 6.1ms | ActiveRecord: 6.7ms)


Started POST "/conversations" for 111.40.6.98 at Sun Jul 15 01:50:10 +0400 2012
Processing by ConversationsController#create as HTML
  Parameters: {"contact_autocomplete"=>"szrichard", "utf8"=>"â^Ü^Ó", "conversation"=>{"subject"=>"xxxx", "text"=>"[FIL$
Completed 500 Internal Server Error in 4ms

NoMethodError (private method `split' called for nil:NilClass):
  app/controllers/conversations_controller.rb:30:in `create'
  lib/rack/chrome_frame.rb:39:in `call'
```

**Comment by AugierLe42e** [comment]
1 year old. Maybe this should be closed.

**Comment by svbergerem** [comment]
The error message says that the server can't split nil in `ConversationsController#create`. Since 2013 ([commit](https://github.com/diaspora/diaspora/commit/b3c859bcd53f9efb95a0f4d3f353aaa0255c0bb5)) we make sure that `params[:contact_ids]` is not nil before splitting it which should have fixed this bug.
