### ISSUE TITLE
Photo upload broken

### ISSUE THREAD

**Issue by balasankarc** [diaspora/diaspora#3653]
The photo upload facility is completely broken today..  The icon (rotating one) showing "uploading" rotates till infinity... It just won't stop... And still photo is not being uploaded... Please fix it...

Balu

**Comment by svbergerem** [comment]
We would have to apply the solution @taratatach [mentioned here](https://github.com/diaspora/diaspora/issues/3653#issuecomment-24876887) to the [apache conf](https://gist.github.com/jhass/719014).

**Comment by jaywink** [comment]
I don't see how setting a larger body size in the web server will help in the case that the connection is just slow? The server side doesn't support chunking uploads and until it does it makes little sense to bump the 4mb limit or even suggest bumping it. Some users will just get more timeouts the larger the limit is increased. Photo uploads really should fall back or be able to use smaller chunks so that timeouts don't happen, which is mentioned in #4997.

**Comment by jaywink** [comment]
Any objections to closing this?

**Comment by jhass** [comment]
Nope.
