### ISSUE TITLE
Post preview not working for some users

### ISSUE THREAD

**Issue by svbergerem** [diaspora/diaspora#4326]
Like Ravenbird [posted on diaspora](https://pod.geraspora.de/posts/1428163) the post preview does not work for some users. When he wants to preview a post, the post does not appear in the stream and instead the style of the first post in the stream changes to the preview-style. So for some reason [this line](https://github.com/diaspora/diaspora/blob/develop/app/assets/javascripts/app/views/publisher_view.js#L188) does not work as expected.

The preview fails for him on Windows and Linux, both with Firefox 22. I am not able to reproduce the bug.

**Comment by marienfressinaud** [comment]
I think I found your bug: this is just because just-published post are in the future! (see my screenshot). It seems once the current time has reached the last published post time, preview works as expected.

![capture d ecran de 2015-02-06 18 32 57](https://cloud.githubusercontent.com/assets/1436309/6084158/f5859392-ae2e-11e4-982c-5b52b058ec87.png)

Up to you to fix the bug :p

**Comment by jhass** [comment]
Wow, good catch!

**Comment by svbergerem** [comment]
I was able to reproduce the bug (see #5275) and the last post in the stream had been posted more than 20 minutes ago.

**Comment by marienfressinaud** [comment]
@svbergerem > I'm quite confident in my suggestion. Have a look to my following screenshot:

![capture d ecran de 2015-02-07 08 25 42](https://cloud.githubusercontent.com/assets/1436309/6091430/a2a6f512-aeab-11e4-80bb-82a89e4a96f6.png)

I have put my PC one hour earlier (8:25 instead of 9:25 ; btw, it is easy to reproduce now :)) and the bug happens with the first post which has been posted at 9:04, 20 minutes ago (even if Diaspora* shows to me it was 40 minutes ago, which is quite strange too).

I don't know exactly how the code works but I guess the preview message is put in a list according to its date and you apply a specific style for the first post. Problem is when the preview date is older than the first post of the list. However, I don't know why the preview appears at the bottom of the loaded stream instead.

**Comment by svbergerem** [comment]
@marienfressinaud I don't say that posts from the future don't trigger this bug (and also #5275). When we add a post to the stream we first add it to a list of posts. We sort that list by date and check afterwards, if our new post is the first one in that list. In that case we would add the post to the top of the stream. Otherwise we would append it to the stream.

https://github.com/diaspora/diaspora/blob/develop/app/assets/javascripts/app/views/infinite_stream_view.js#L49

When the first post in your stream is a post from the future it is quite obvious that you will find new posts at the end of the stream.

> I guess the preview message is put in a list according to its date and you apply a specific style for the first post.

That is correct.

What I was trying to express with my comment is that there are also other circumstances that trigger this bug.

**Comment by marienfressinaud** [comment]
Ok, I understand! I didn't pay enough attention to your comment (https://github.com/diaspora/diaspora/issues/5275#issuecomment-67144130).

An easy solution may be to add the preview post in a dedicated "box"? So it could help later for preview of comments (#4973) and private messages (#5210). Actually, it seems to me it is quite a hack to use infinite scroll methods in order to add a single post on the top of a list, isn't it?

**Comment by svbergerem** [comment]
Fixed by #6551.
