### ISSUE TITLE
Make more clear that the time ago is a link to the SPV

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#4975]
Many user don't get that we can click on the date of a post to display the post in the SPV.

One way to improve that situation would be to add a icon like this one next to the date:

![](http://www.businessmarketingblog.org/wp-content/uploads/2011/04/links.jpg)

Do you have any other ideas?

**Comment by giniouxe** [comment]
What about a link description which could explain where the link points, by changing  the alt text ?

**Comment by Flaburgan** [comment]
That would be already better indeed, but the alt text is currently the date. You think about putting both?

**Comment by giniouxe** [comment]
Exactly

**Comment by Flaburgan** [comment]
Why not. Let's wait for other opinions on that.
I still would like to see a ![](http://www.icone-png.com/png/2/1662.png) icon on hover. 
![](http://sotravel.fr/site/wp-content/themes/ensconce/images/icons/link-icon.png) means target="_blank" to me. We use entypo so you can check there if there is some nice icons.

**Comment by goobertron** [comment]
A description in alt-text could be something like 'See original post from {timestamp}', I suppose.

I'd be happy with adding a permalink icon like the one in Fla's second paragraph, although I don't strongly feel it's necessary.

**Comment by svbergerem** [comment]
I'm not really keen on changing the title of the link. We only set the timestamp as the title everywhere else and I think we should keep it that way. With the extra 'See original post from …' I think the title would be too long. I just checked how facebook and twitter are doing this. Twitter also uses the timestamp as a link and doesn't have any additional information about the behavior. On hover you also only see the timestamp. However the whole tweet is a link to the 'SPV'. Facebook also uses the timestamp as a link and also has no extra information about that.

I am not saying that we shouldn't do anything just because facebook and twitter are doing the same but at least users coming from one of those networks should be familiar with the timestamp being a link to the SPV.

**Comment by pafcu** [comment]
I just spent some time trying to figure out how to get a permalink to a post, and had to resort to google to figure it out. Currently there is no indication whatsoever that the time is a link to something. Why not underline it or make it the same color as "Like" and "Comment" to make it clear it's a link?

While I liked the classic point-and-click games of the 90's, where you had to move your mouse over every single thing to see if you could interact with it, I feel like this is not the correct aproach for Diaspora* :-)

**Comment by pafcu** [comment]
Oh, and at least Twitter does have a "Copy link to Tweet" item in the "..." menu, which is a lot more discoverable than the timestamp thing (I was unaware that it works like that in Twitter). Maybe some similar menu system could be implemented in Diaspora as well?

**Comment by svbergerem** [comment]
Here are two ideas. In both cases the icon is only visible when the mouse is over the post.

### Version 1

![permalink-v1](https://cloud.githubusercontent.com/assets/3798614/10245658/e5a35c5c-6909-11e5-9227-7ce2b0b9d5c0.png)

### Version 2

![permalink-v2](https://cloud.githubusercontent.com/assets/3798614/10245664/eafa3a4a-6909-11e5-88b3-9d8174e5f0ed.png)

Which one do you prefer?

**Comment by SuperTux88** [comment]
I prefer version 1, because maybe someone can learn that he can click the whole timestamp :)

**Comment by Globulle** [comment]
I prefer version 2, since all the icons are grouped in a nice way. However I think we should not add too much icons in this corner to keep things simple. Would it be possible to have a "..." icon under which "permalink" and "report" icons could be grouped (they would appear when the mouse points the "..." )? My point is that "permalink" and "report" are not of frequent use, so they may not need a permanent visibility.

**Comment by goobertron** [comment]
That's a neat solution, Steffen. I rpefer version 1, because the new icon is next to the existing permalink, the timestamp.

**Comment by jaywink** [comment]
One v1 please, to go.

**Comment by Realtin** [comment]
guess I'm outnumbered  but I like version 2 :D

**Comment by Flaburgan** [comment]
Cool! Thanks @svbergerem!

**Comment by Loelo** [comment]
Hi, I suggest that the new icon opens the SPV in a new tab (whereas the timestamp opens it in the same tab as it is the case now.), so that both will not be total duplicate.

Also, shouldn't the hover text be changed from "permalink" to "open in single post view" or "open post in a new tab" :

**Comment by marienfressinaud** [comment]
I'm not convinced about opening permalink in a new tab, it's disturbing me most of the time.

**Comment by svbergerem** [comment]
> I'm not convinced about opening permalink in a new tab, it's disturbing me most of the time.

I agree.
