### ISSUE TITLE
Working on FaceBook API 2.x

### ISSUE THREAD

**Issue by Anime-Machina** [diaspora/diaspora#5260]
Hello there,

Today I noticed that FaceBook is closing down API 1.x on 25th December and all API's will have to be updated prior 25th December. Is D* already running API 2.x or still under the old API or is it already running API 2.X???

Proof:
http://i.imgur.com/jx0Iup7.png

Regards,
Anime Machina

**Comment by jaywink** [comment]
The dates are wrong as discussed on various forums:

> With the launch of v2.0 of the API, we have two versions in service at the same time:
> 
> Version 1.0, which is what we call the API as it existed the day before v2.0 was launched. We'll support v1.0 for one year and it will expire on April 30th, 2015.
> Version 2.0, which is what this upgrade guide covers. Version 2.0 is supported for at least two years. At the earliest, it will expire on April 30th, 2016.

https://developers.facebook.com/docs/apps/upgrading#v1tov2

The problem I have is I can't figure out from anywhere *why* our current integration would even work, since we've *never* required afaict *publish_actions* - **and this is not changing in v2**.. Maybe time for a podmin poll..

But AFAICT our code should be all good with api v2. I don't see anything in the v2 API that would break our current implementation.

**Comment by Anime-Machina** [comment]
I did had error messages showing up about post actions, it definitely needs more info in future. Although I personally dropped FaceBook and Twitter support on my pod cause some one violated their terms.

**Comment by denschub** [comment]
Closing this. Additional configuration available with 7c0e50c2c270e696b7dbd6540d00b4cc38e25375, additional information regarding this change and issues in #5085. Feel free to reopen if you feel the urge of doing so.
