### ISSUE TITLE
publisher adds new post to the bottom of the stream instead of top

### ISSUE THREAD

**Issue by Raven24** [diaspora/diaspora#5275]
When I post a status message, I expect it to become the first one in my stream.
Instead I just observed the fresh post becoming the last entry at the bottom of the loaded stream.
I am on the lastest develop commit as of the time of this post.

can someone confirm this?
##

**Comment by balasankarc** [comment]
I just tested this on poddery and it seems to be fixed. The new post remains on top. 
Can anyone else confirm?

**Comment by goobertron** [comment]
I have certainly not seen this bug for a long time on any of the pods I use.

**Comment by jaywink** [comment]
Alright, closing for now. Never managed to witness this myself and the latest confirmation about the bug is soon one year old. Please shout here for reopen if you witness this again.

**Comment by Ravenbird** [comment]
The bug is back. I'm on nerdpol.ch and my postings often (not always) at the end of the stream.

https://lutim.allmende.io/sBJaZo

**Comment by cmrd-senya** [comment]
Have anyone observed the issue for the last couple of years? I never noticed it myself.

There were some changes to infinite scroll since the time @Ravenbird reported the issue, though I can't see anything related. Also dependencies were updated so if it was due to an upstream bug it could be gone because of an upstream fix.

If it doesn't happen to anyone today I suggest closing.

**Comment by goobertron** [comment]
I've not seen this for a *very* long time.

**Comment by SuperTux88** [comment]
Yes, I never saw this bug for years or remember anybody to complain about a bug like this, so lets close this.
