### ISSUE TITLE
Commenting on a post of someone ignoring you doesn't show the reason

### ISSUE THREAD

**Issue by cocreature** [diaspora/diaspora#5366]
When you comment on a post of a person ignoring you, diaspora returns a 422 and shows something along the lines of “something went wrong” instead of showing the actual reason (the post author is ignoring the commenter) or at least something a bit more specific like “you are not allowed to comment on this post”.

**Comment by Faldrian** [comment]
I also would like an UI change for this. This situation just happened to me and I wrote a nice long helpful comment to explain something to a new person - and it gave me an error. Luckily I had the comment saved (just in case) - but if I had known this person is ignoring me, I would never have written the comment.

So I would like to extend this issue (if you are okay with that): The interaction-options of a post from a user who is ignoring you should be disabled and in the place where the comment-field would be there should be a hint "This person is ignoring you, you can't comment".

This will not impact privacy of the ignoring user, because only blocked users would see that they are blocked - and they would know anyways if they try to comment or like and nothing happens.

Oh... and as we are on it: I would like an error message when you try to like the post ... and just nothing currently happens. I wait 2 seconds and no heart is turning red and I know "oh.... blocked."

(And as I introduce all these aspects of the matter... I would take care of implementing, if we have a consent of what should be done.)

**Comment by SansPseudoFix** [comment]
:+1: @Faldrian

**Comment by WebDevFromScratch** [comment]
I would like to jump in on this. I am new to using Diaspora though, so I'm probably going to need some time getting familiar with the code first.

**Comment by svbergerem** [comment]
@WebDevFromScratch Sure, you can ask if you have any questions.

@Faldrian AFAIK the list of ignored users is not federated so this would only work when both users are on the same pod, right?

**Comment by Faldrian** [comment]
@svbergerem 
Hm.. but I don't understand how an action could fail so fast if my pod does not know the list of blocked users from a remote user. As far as I know there is no federation-roundtrip made before I get the ajax-response when commenting / interacting.
So there *must* be a list of blocked users present somehow.

**Comment by jhass** [comment]
Well, it's not unlikely that this only happens when the post author is local. The list of ignored people is most definitely not federated.

**Comment by Faldrian** [comment]
So if the person I interact with is on another pod, I will never know that interaction didn't succeed because I will get no error, no "missing comment" no nothing (because on local server the comment is stored when I comment...)?

**Comment by jhass** [comment]
Probably.

**Comment by Faldrian** [comment]
Somehow I don't like that local users and remote users are dealt with differently. That makes the network hard to understand for not-IT-savvy people. As I see it there are two options:

- make interaction with local users behave like interaction with remote users: Let the user comment, like, whatever ... but don't show that to the other user who is ignoring the interacting user.
- make interaction with remote users behave like interaction with local users: Give immediate feedback and tell the other user (preferedly before making the interaction) that the user is ignoring the user.

As the second option would have impact on the privacy of a user, I think we will most likely tend to the first option, if we decide to change this into a consistent behavior?
Any options I forgot?

**Comment by jhass** [comment]
I didn't come up with anything else either.

**Comment by WebDevFromScratch** [comment]
Okay, so I have been working on that and I have a question... Actually, a couple of questions ;)

So I implemented the initially requested fix, plus some extras. What I did:

* changed flash alert if commenting the post fails to sth more suggestive
* added flash alert if like fails
* fixed a bug in userLike method

And my question is, should I test it anyhow? I know the obvious answer would be 'sure', but I can't really find the place where to test that kind of stuff... Or maybe that's too small of a feature/fix to cover by tests here?

Another question is about these other suggestions you have been talking about here, but I assumed there is no clear request for that yet.

Someone, please let me know about those tests, so I know if I should create a pull request right away or work on these.

Thanks!

**Comment by jhass** [comment]
> changed flash alert if commenting the post fails to sth more suggestive

Requires no test

> added flash alert if like fails

Should at most be a RSpec controller if set in a server side action or a Jasmine test of the corresponding backbone view.

> fixed a bug in userLike method

Should most likely also have a Jasmine test that fails without the change.

> so I know if I should create a pull request right away or work on these.

We have no problem at all with work in progress pull requests, especially if you want some feedback on your code early.

**Comment by WebDevFromScratch** [comment]
opened a pull request for this: https://github.com/diaspora/diaspora/pull/5689
