### ISSUE TITLE
Resize images on client-side before uploading

### ISSUE THREAD

**Issue by Debakel** [diaspora/diaspora#5621]
Instead of limiting the file size to 4 MB, high resolution images should be automatically resized on the client side before uploading them to the server. People are used to upload images straight from their camera and it's inconvenient to resize them manually.

One (easy) way to do this is described here: https://hacks.mozilla.org/2011/01/how-to-develop-a-html5-image-uploader/
##

**Comment by AugierLe42e** [comment]
Related to #5700.

**Comment by Fensterbank** [comment]
Is not as easy as I thought.
Diaspora uses a pretty old unmaintained version of a file uploader (maybe [this one](https://github.com/Valums-File-Uploader/file-uploader)) which handles the maximum size error itself and doesn't even implement an `onError` method in this version.
There is no way to work with the original image without modifying the file uploader.

But I think we could upgrade our current uploader to [FineUploader](https://github.com/FineUploader/fine-uploader), a modern commercial version of the old one.

While mainly developed from a company, it seems to be free and open source and includes nice features like uploading scaled images (so we don't need a special resizing class) and direct upload from mobile camera.

Does something speak against it?
@svbergerem, what's your opinion?

**Comment by svbergerem** [comment]
@Fensterbank FineUploader seems to be actively maintained and the license (MIT) looks good to me. If anyone is interested in using FineUploader for diaspora\* I don't see why we shouldn't give it a try.

**Comment by rnicholus** [comment]
I happen to be the (long-time) maintainer of Fine Uploader. Do let me know if you run into any immediate issues integrating Fine Uploader. The [scaled image upload feature page](http://docs.fineuploader.com/branch/master/features/scaling.html) should be a useful resource.

**Comment by flashcode** [comment]
Hi,

Any news on this issue?

The limit of 4MB per file to upload is a major issue for me (my smartphone and DLSR photos are bigger than 4MB). I'm forced to use other social networks for photos, since it's a pain to manually resize photos before upload (especially on mobile phone).

By the way, I don't agree with @Fensterbank about the 4MB limit which "should stay". Today with large disks and bandwith, why keeping such low hardcoded limit?
At least pods admins should be able to choose a higher value if they want to.

I see that help is wanted for this issue, but unfortunately, I'm not able to help on this issue (not enough time).

**Comment by svbergerem** [comment]
>  At least pods admins should be able to choose a higher value if they want to.

https://github.com/diaspora/diaspora/pull/6819#issuecomment-216005316

**Comment by Flaburgan** [comment]
Linked to https://github.com/diaspora/diaspora/issues/4997

**Comment by Flaburgan** [comment]
Fyi, the bounty earned by whoever solves this issue is now at $200.
