### ISSUE TITLE
People's preview broken

### ISSUE THREAD

**Issue by sedrubal** [diaspora/diaspora#5631]
The preview for people appeares and dissappears sometimes, when I move the cursor on the avatar of a person.

**Comment by S-Ercan** [comment]
Fixed and created PR https://github.com/diaspora/diaspora/pull/5714 for this.

The issue was the following:
If, on hover, your mouse pointer happened to be just off the border of the appearing hovercard, this would register as a `mouseleave` event in the hovercard and the hovercard would then get hidden again.
As a result, the `mouseenter` event in the original element that you hovered on was triggered again.
This then kept repeating itself, leading to the flickering behaviour described by sedrubal.

I fixed this by changing the top and left coordinates of the hovercard to match those of the parent element (that was hovered on originally). This way the mouse pointer is guaranteed to be inside the hovercard, preventing the mentioned scenario from occurring.
