### ISSUE TITLE
add possibility to add people to private messages after creating one

### ISSUE THREAD

**Issue by kas70** [diaspora/diaspora#5642]
this could be some sort of replacement for groups, which many people are missing on d*.

**Comment by goobertron** [comment]
I disagree, because private conversations are private, therefore if one contributes to a private conversation, you don't want to find that someone has later added someone to the conversation without your agreement. You'd have to build in a function whereby every existing participant agrees to the addition before the person is added, or something like that. This suggestion needs Loomio discussion as the issue isn't a technical one but an issue about functionality.

In any case, rather than implement something like this as an ersatz group feature, let's implement groups! There are already discussions on that, see [this Loomio thread](https://www.loomio.org/d/kOuGjiTR/add-support-for-groups-in-diaspora), for example.

**Comment by jhass** [comment]
Please take this to Loomio then, we can reopen this issue once a decision has been made.

**Comment by davidbaumann** [comment]
If the newly added user can only see the new messages, and can only be added by the creator of the group, I don't see a problem here.
It just has to be obvious, that some new user has been added.
