### ISSUE TITLE
Add warning for old profile data

### ISSUE THREAD

**Issue by marienfressinaud** [diaspora/diaspora#5727]
With the new system to download profile data, user has to refresh its data before downloading them. Even if there is a date indication, it could be great to add a kind of warning message to indicate for instance if the last refresh is older than 2 weeks in order to prevent download of old data.

I don't know if this message should appear after an arbitrary time or if it is possible to know if a user has been active (e.g. add a comment, publish a post) since the last profile data refresh. I would prefer the second solution since data can already be up-to-date after two weeks if you didn't do anything.
##

**Comment by Loris1123** [comment]
I don't think a warning popup would be a good idea. Users will be annoyed.
At the moment there is the pretty small `(Last updated at 2016-01-15 19:09:21 UTC) ` text. I think we should impove this by moving it more up to the download button and change it to something like `Last updated 5 days ago`, since the current version isn't very userfriendly.
