### ISSUE TITLE
Improve the publisher

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5801]
This is an issue to design a new publisher, to solve two problems:
* Allow to preview every message fields, including the conversation (private messages), comments and faceboxes
* Make the usage of markdown easier for non-technical people

I like the way github is dealing with this problem: a tab "Write" where the text is entered, possibly using markdown (we could add buttons to easily integrate markdown here), and a tab "Preview" to show how the text will be rendered once posted. The content of the "Preview" tab **cannot be edited**, that means, this would **not** be a wysiwyg editor: it would be a smart editor with shortcuts to use markdown in the "Write" tab, and a "Preview" tab which is here to check if your message is correctly rendered.

What do you guys think about this solution?

**Comment by jhass** [comment]
I think a preview tab would indeed work better than our current solution.

However I would be distracted by the buttons and I also dislike adding too many settings, since they make both, UX and implementation more cumbersome.

I think making the "Markdown" link open an inline help popup, that leaves the focus on the publisher would be nice.

So I wonder, if we look at this from an interaction point of view, is formatting really a core feature of every post you write, or wouldn't be writing regular posts with mentions, tags and paragraphs be more than enough for a new user?

**Comment by AugierLe42e** [comment]
> However I would be distracted by the buttons and I also dislike adding too many settings, since they make both, UX and implementation more cumbersome.

This is a key point. We must not forget that we are making a social etwork for everyone. And many new users complain about the complexity of MD. The is a big accessibility issue to me. And the popup thing won't solve anything because most user just don't want to refer to the documentation each time they write something.

An opt-in solution is the best choice to me.

**Comment by AugierLe42e** [comment]
I also think that copy/pasting into the publisher should keep the formatting e.g quoting, italic, etc..

**Comment by Globulle** [comment]
> So I wonder, if we look at this from an interaction point of view, is formatting really a core feature of every post you write, or wouldn't be writing regular posts with mentions, tags and paragraphs be more than enough for a new user?

I think lots of users use comment threads to discuss polemical topics which need long paragraphs and structured comments. The ability to use Markdown is then very convenient and is clearly an advantage over Facebook. And preview in such cases would be indeed appreciable.

**Comment by denschub** [comment]
So, since the last pull request went bonkers but I've done some research on `bootstrap-markdown`, I'd like to write them down for future contributors who will give it a try. For PoC'ing purposes, I've created a little jsbin with some tests ([editor](https://jsbin.com/titawa/edit?html,css,js,output), [demo](https://output.jsbin.com/titawa)).

Obviously, this is a very unpolished demo, but it is not clear that

* we could add tabs to toggle between edit and preview with ease
* we could toggle the editor if needed (for example by clicking the "markdown" link)
* we could add custom buttons if needed (for example for polls, location, custom markdown or maybe a post draft saving feature)
* we could use our existing markdown parser
* we **could not** move the controls to the bottom without having to use absolute positioning

For a future contributor, some things have to be researched and discussed in this group (preferably on loomio)

* if we are able to integrate our mention auto-completion
* if we are able to find a nice UI that most of the people like and understand

**Comment by AugierLe42e** [comment]
> For a future contributor, some things have to be researched and discussed in this group (preferably on loomio)
> 
> * if we are able to integrate our mention auto-completion

Of course. It was already working in my PR...

**Comment by svbergerem** [comment]
Fixed by #6551.

**Comment by cmrd-senya** [comment]
Horray! More marked up posts on diaspora! Welcome, user friendly publisher! Thanks @AugierLe42e!
