### ISSUE TITLE
Homogeneous Markdown rendering of quotations between stream view and single post view

### ISSUE THREAD

**Issue by Globulle** [diaspora/diaspora#5807]
I like to use quotations with Markdown, using the ">" character. But the rendering is not the same in the stream view and in single post view, which can be confusing.
Here is how it renders in __stream view__:
* Same size as normal text
* Gray color
* Italics

And here how it renders in __single post view__:
* Bigger size as normal text
* Black color
* Vertical bar on the left

I think it would be clearer to use the same convention in both views, which could be a mix of the two. I suggest:
* Same size as normal text
* Gray color
* Italics
* Vertical bar on the left

Your thoughts?

Below are two images to illustrate the different renderings.
![diaspora_streamview](https://cloud.githubusercontent.com/assets/11587267/6765914/2f2fa44e-cff3-11e4-9b54-fea82ed4ee49.png)
![diaspora_singlepostview](https://cloud.githubusercontent.com/assets/11587267/6765915/4883cd26-cff3-11e4-8a3b-a46666dbdc23.png)

**Comment by svbergerem** [comment]
This issue has been fixed in the development version. Your screenshot of the stream shows an outdated version with the blueprint stream. We are now using Bootstrap everywhere so the style of quotations is the same in the stream and the single post view. The applied style is
* same size as normal text
* gray text color
* left border
