### ISSUE TITLE
Wrong url and bug in settings nav after changing user settings

### ISSUE THREAD

**Issue by svbergerem** [diaspora/diaspora#5847]
When changing user settings the users controller renders the edit page which leads to a wrong url (pod.tld/user) and a settings nav with no selected active page. Before #5580 it redirected to the user edit page which is not possible anymore because it would break the validation errors added in #5580.

**Comment by cmrd-senya** [comment]
First I tried to change the PUT/PATCH route from `/user` to `/user/edit` so it matched the proper page URL on UsersController#update action.

But that didn't help with the styling of the navbar! As it turned out, the `current_page?` method used in the [navbar template](https://github.com/diaspora/diaspora/blob/develop/app/views/shared/_settings_nav.haml#L9) [returns false](https://github.com/rails/rails/blob/c24659bf9963578f82173b00ee9dca087692ed25/actionview/lib/action_view/helpers/url_helper.rb#L533) on every request that is not GET or HEAD. [Replacing](https://github.com/cmrd-senya/diaspora/commit/067f597230aff781a299b2d1c61676f94567607c#diff-7c35e7ebaa62c0ac89c65164ea5a1fc0L7) the calls with a simple own [`current_path?`](https://github.com/cmrd-senya/diaspora/commit/067f597230aff781a299b2d1c61676f94567607c#diff-127a850b7d7b20173ad3fba88f8a25e3R67) method fixed the thing. There are still some issues from #6801 left which are probably caused by the same thing, but otherwise it works as expected.

Tell me please, if the approach is generally fine and I will prepare a PR then.

**Comment by Flaburgan** [comment]
I don't know if it's the same issue but a similar problem exists on the sign up page. If you submit the form with some errors (for example, email already token, or the two passwords don't match) then the page will reload with a broken design.
