### ISSUE TITLE
add 'what is diaspora*?' info to email invitation

### ISSUE THREAD

**Issue by kas70** [diaspora/diaspora#5884]
maybe by adding a link to diasporafoundation.org.

**Comment by efstrian** [comment]
Should this be done for every locale file?

**Comment by jhass** [comment]
No, our translators will do that work, only update/add to the English locale.

**Comment by efstrian** [comment]
Any preferred message? (a dummy question, but is there any way to test the output?)

**Comment by jhass** [comment]
To test the output just trigger the message delivery from `bin/rails console` and watch your `log/development.log`.

**Comment by efstrian** [comment]
I've added the link directly to the locale file. Is that right?

**Comment by kas70** [comment]
Hey there,
just noticed, that something is going wrong here with the translations.
I tried invitations with different languages (I'm on geraspora).

English (works):
> P.S.: Just in case you don't know (yet) what diaspora* is, here is the answer!

Italian: the line above is totally missing (is this just a thing of a missing translation?)

German:
> PS: Nur für den Fall das du (bisher) nicht weißt was diaspora* ist, [hier][2] gibt es die Antwort.
> [2]https://diasporafoundation.org/

**Comment by cmrd-senya** [comment]
@kas70, the issue is that the original English text was first written,
then translated, then modified and now we have English version updated
while translations still have the old contents. We noticed that before
for another email text and Russian text was updated. However it's hard
to track that way. Perhaps our translation platform supports some way of
marking texts for verification when original source has changed?
