### ISSUE TITLE
HTML CSS failure

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#5928]
See https://diasp.eu/posts/3093939

Why is diaspora web page layout not compliant with w3 standards?

Why the reliance on ecmascript?

**Comment by jhass** [comment]
Please elaborate and describe how to reproduce.

**Comment by githubgnulinux** [comment]
See:

http://validator.w3.org/check?uri=https%3A%2F%2Fjoindiaspora.co.uk&charset=%28detect+automatically%29&doctype=Inline&group=0

http://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fjoindiaspora.co.uk&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en

**Comment by jhass** [comment]
That aren't sufficient instructions to reproduce your issue.

**Comment by githubgnulinux** [comment]
Ignore the distraction of trying to reproduce. Instead, review the html and css code errors. When these are corrected, diaspora layout will be w3 standards compliants and therefore compatible with all standards-compliant web browsers, operating systems, devices.

**Comment by jhass** [comment]
I'm sorry to inform you, but you live in a dream world about that.

**Comment by githubgnulinux** [comment]
Programmers made the (correct) decision to avoid development of silly "apps" in instead design a good web site that is equally accessible via any device.

To achieve that (including visually impaired people), compliance with w3 standards is the most efficient use of programmers' time.

http://www.w3.org/WAI/

(Beautifully compliant web site of course, even via orweb v2! :) )

**Comment by githubgnulinux** [comment]
Programmers made the (correct) decision to avoid development of silly "apps" and instead design a good web site that is equally accessible via any device.

To achieve that (including visually impaired people), compliance with w3 standards is the most efficient use of programmers' time.

http://www.w3.org/WAI/

(Beautifully compliant web site of course, even via orweb v2! :) )

**Comment by denschub** [comment]
This is neither an issue nor a feature request. Feel free to create an issue if you found an issue and you are able to provide instructions on how to reproduce it or start a discussion on Loomio for feature requests.

**Comment by githubgnulinux** [comment]
Layout failure continues with latest version.

Previously, a post would be positioned on left half of the web page and comments on right half. Now both original post and comments appear only on left half of the web page; the right half is empty. Now occurs on all pods with the latest version.

https://diasp.net/posts/172797

**Comment by githubgnulinux** [comment]
If you don't consider accessibility an issue, wow!

Layout failure continues with latest version.

Previously, a post would be positioned on left half of the web page and comments on right half. Now both original post and comments appear only on left half of the web page; the right half is empty. Now occurs on all pods with the latest version.

https://diasp.net/posts/172797

Why start discussion on loomio, diaspora exists for discussion?

**Comment by Flaburgan** [comment]
@githubgnulinux there is three different things here, standards compliance, accessibility and your design breaks problem. Those three issues are important but we have limited time. This ticket was about the layout issue, I know no one with the same problems, what's your browser, and is Javascript enabled?

**Comment by githubgnulinux** [comment]
> Flaburgan:

The time limit is well understood. With respect, the standard programmer response: browser version, operating system, how to reproduce, etc. etc.. is not appropriate in my low opinion.

A more strategic question for discussion amongst those involved: are standards compliance and accessibility important to minimise programmers' time to design the web site for maximum use?

If the answer is no, there is no need to investigate issues such as layout differences.

If the answer is yes, then:

What is the cause of the non-compliance as reported by w3 html and css validators?
Should the web design require ecmascript?
Should the web design have an acceptable "default" if ecmascript is disabled (more numerous reasons by the user)?
Should we tell users "use browser X/Y/Z" (like the "this web page is best viewed in internet explorer" in the bad old days)?
Should we tell users "use any web browser that complies with w3 wia guidance"?

**Comment by denschub** [comment]
So you linked the W3 validation service and it complains about two missing attributes and an empty headline. Great. You assume this will break your layout and I have no idea why you do this. Even after asking multiple times, you fail to provide actual steps that would allow us to see what you see and figure out what is wrong. You're basically wasting time and resources here.

Your so-called issue not not causing any troubles. In addition to a link with a screenshot of your issue, you asked two questions which are clearly not issues either. If you feel the urge to discuss it, do it, but not in GitHub. This is an issue tracking tool and not a suggestion box. If you want to discuss about how important it is to be 100% spec compliant, head over to Loomio and do what you need to do. Why Loomio? Because that's [how our community wants to communicate](https://wiki.diasporafoundation.org/How_we_communicate).

I understand you are a highly trained and very experienced web developer, so I am looking forward to your pull request introducing 100% spec compliance and your second pull request to remove all JavaScript dependencies. Should be an easy task for you.

Please stop using GitHub for discussions on what we should do and how we should do it, use Loomio for that. If you see an issue, report it and tell us how we can reproduce it. If you think providing steps to reproduce is not important, fix the issues yourself and submit a pull request. Do not report issues that require crystal ball powers to resolve. Thank you.

**Comment by githubgnulinux** [comment]
Html validation reported 3 errors, css validation reported 603 errors; why do you state that validation comprises only 2 missing attributes? This is not understood.

Similarly to (proprietary) github, it was a surprise to observe that loomio does not accept sign-in via diaspora accounts, but if memory is correct, other social network accounts. Just tried loomio, but web site prompts for captcha, because of access via tor...

To clarify, there are two validation services for html and css, the latter seems to be the major problem source of non-compliant errors.

As suggested, reproduction is not required (again, my low opinion) because w3 css validation is performed to a diaspora pod url; you can reproduce by repetition with any pod url you choose when you test validation at the w3 web site. The validation errors and warnings report produced by w3 seems detailed.

Your opinion is your human right, as is your right to reject the opinions of others.

**Comment by denschub** [comment]
> Please stop using GitHub for discussions on what we should do and how we should do it, use Loomio for that. If you see an issue, report it and tell us how we can reproduce it. If you think providing steps to reproduce is not important, fix the issues yourself and submit a pull request. Do not report issues that require crystal ball powers to resolve. Thank you.

I will now lock this issue to prevent additional discussions with no potential outcome. If someone is able to provide additional details or relevant discussions, please ping a core member on IRC.
