### ISSUE TITLE
Welcome messages to users

### ISSUE THREAD

**Issue by TwizzyDizzy** [diaspora/diaspora#6021]
Hi folks,

a feature request: It would be great to, as a podmin, have a sort of default welcome message you could post to a newly registered user's inbox to show them how things are handled on your pod.

There could be config options in diaspora.yaml:

* welcome_sendmsg: BOOLEAN, Determines if welcome messages shall be sent
* welcome_msg: VARCHAR The text of the message, maybe containing a token (e.g. [USERNAME]) to be replaced with the user's name. Diaspora shall provide a sound default. (I would write one, if this feature request gets accepted)

Cheers
Thomas

**Comment by fap-** [comment]
I would like to work on this issue, if this is alright?

If we drop the message in the user's inbox we need a sender account.
Maybe use the admin account specified in 'diaspora.yml' and 
ignore the 'welcome_sendmsg' flag if no admin account is specified?

**Comment by jhass** [comment]
Admin account sounds good, I think falling back to the autofollow_on_join user wouldn't be too bad too, so by default `diasporahq@joindiaspora.com`.

**Comment by TwizzyDizzy** [comment]
Hi folks,

using the specified admin account seems like the way to, ignoring the welcome_sendmsg flag if no account is specified, too.

I'll compose an intriguing ( ;) ) welcome message up until saturday.

Maybe we could shortly agree on the contents. I'd like to mention at least the following things:

* "hi, welcome to this pod"
* some links to sites containing information on how to use diaspora (any ideas?)
* link to legal terms
* some information on whom to contact in case the pod doesn't behave as expected
* some encouragement to support your podmin (bitcoin, paypal)

If something else comes to your mind, just mention it :)

Cheers so far,
Thomas

**Comment by jaywink** [comment]
Aww shucks, sorry, accidental mouse click :dancer: 

Was just going to say "great idea", then decided not to spam with a comment and accidently clicked Close. So, great idea ;)

**Comment by Flaburgan** [comment]
I'm definitely in favour of introducing the software to the new users (and @SansPseudoFix probably has suggestion about that, he is welcoming manually new users on framasphere for a while now) but I would prefer to improve the already existing "getting_started" panels. You can reactivate it in the settings if you forgot what is this about, but to summarize, there is a welcome message, a presentation of the publisher, a presentation of the audience control component and a presentation of the stream. We can help the new user discovers the other part of diaspora* with this mechanism.

**Comment by jaywink** [comment]
I think there is a good reason to use email here - it ends up safe in the inbox so the user can look it up later, if the pod is down for example.

I guess as fallback, since not all pods configure email, conversations could be used.

Also I don't see why a welcoming conflicts with improving the getting started panels. Both can be done.

**Comment by Flaburgan** [comment]
Hm, I thought this was about a private message, not an email.

**Comment by SansPseudoFix** [comment]
Yeah, it's a great idea!

In first place, I welcomed every new users on framasphere, but now I just check #newhere tag and post an help message if the post is in limited aspect (obviously, if you post a #newhere message, it means you want to meet people). This welcome message can be displayed on stream. Maybe I'm wrong, but I think many users don't have a look to the "getting_started" panels, just a :open_mouth: face and close it.

The message can be like this:

> Welcome !
> If you want to meet people, you can post a message in **Public** view with #newhere tag:
>> Hi, I'm #newhere, and I want to talk about #diaspora 
> 
> * **All aspects** or at least one of them -> only contacts can see what you post
> * **Public** -> everybody can see what you post
>
> ![publisher img](https://lut.im/YZqNL8sp/S8Ug2lEy)
>
> If you have any question about diaspora*, you can consult [help](/help) section (see menu) or just ask me by mentionning me.
>
> Helpfull links:
> * [Formatting](https://diasporafoundation.org/formatting)
> * [Getting start](https://diasporafoundation.org/getting_started/sign_up)
> * [Wiki](https://wiki.diasporafoundation.org/Main_Page)
>
> Hope you'll enjoying your trip!

Of course, with a better english and some other points and links :)

**Comment by fap-** [comment]
Okay, I think we need a consensus on how to do this before I go on with the implementation.

I investigated the conversation/inbox route and the problem I encountered is that you can only start a conversation with someone if he has you in his contacts.
I think the solution would be to bypass the check [here](https://github.com/diaspora/diaspora/blob/develop/app/models/conversation.rb#L27) if the author is the podmin contact (can't check for admin because the podmin doesn't have to be an actual admin).

Referencing a user in stream posts probably has a similar restriction/validation but I haven't looked at the code yet.

**Comment by jhass** [comment]
Sounds about right, maybe make sure the recipient is local if the podmin account is the sender.

**Comment by goobertron** [comment]
This looks like a good idea to me.

If this could incorporate an explanation of the auto-follow process as per #6021 (i.e., that your new account has been set to auto-follow another account, which account that is and why we do this, and what to do if you *don't* want to follow that account), that would be excellent.

**Comment by jhass** [comment]
#6128 added the infrastructure for this, I'm keeping this open because tbh I think we can still improve the default for the actual message ;)

**Comment by Flaburgan** [comment]
maybe @goobertron wants to write the default message? ;)

**Comment by goobertron** [comment]
Thanks, boys, I'll have a look at it.

**Comment by goobertron** [comment]
OK, my suggestion is to have the text in several sections (fields), so that the defaults for the subject, opening section and sign-off can be left alone by podmins and any custom text inserted into the middle section. This would enable the default text at least to be localised using i18n. Podmins could enter whatever translations they can provide for their custom text into the relevant locale files, but this would default to either English or whatever language they entered it in, if they don't enter a translation for the relevant language.

`subject`
> Welcome to %{pod_name}

`body_1`
 > Dear %{username},
> 
> Thanks for choosing %{pod_name} as your new home in the diaspora\* network.
> 
> If you’re new to diaspora\*, have a look at our ‘getting started’ tutorials [link to https://diasporafoundation.org/getting_started/sign_up] to get you familiar with diaspora\*’s interface and help you connect you to your friends and other community members with interests similar to yours.

`body_2`
[this bit will be left blank in the defaults and can be filled in with any custom information]

`sign_off`
> Hope you enjoy being part of diaspora\*'s worldwide community through %{pod_name}!
> 
>  Thanks,
> 
> Your podmin at %{pod_name}

How does that sound?

**Comment by jhass** [comment]
Oh well, translations. Currently the message is generated on sign up, so prior getting started being done = prior user choosing their language.

**Comment by goobertron** [comment]
Ah. As I read in diaspora.yml.example in #6128 that this will 'Send a message to new users **after** registration' I assumed this meant after getting started had been completed.

Would it be feasible (i.e. not *too* complex) to change the generation of this message so it happens after a language has been chosen?

If that's not on the cards, then we can leave the message as one field.

**Comment by jhass** [comment]
It wouldn't be hard, but I'm not sure I like suggesting to send them a mixed language message.

**Comment by TwizzyDizzy** [comment]
Hi folks,

sorry for not keeping my promise to compose a message until saturday - I had some urgent private matters that needed attendance.

I'm actually quite fond of @goobertron's message.

As to the language of the message: I guess one could be opportunistic in that case and detect the locale of the browser the user registered with and fall back to english, if no proper locale was detected. That would keep the code changes to a minimum while being "precise enough".

Cheers
Thomas

**Comment by jhass** [comment]
Nah, delaying until after getting started is no issue, I'm just not fond of having mixed translated parts with untranslated parts from the podmins config.

**Comment by goobertron** [comment]
> I'm just not fond of having mixed translated parts with untranslated parts from the podmins config.

Neither am I; but nor am I keen on sending a message in English or the podmin's language regardless of what language(s) the user speaks. In some cases this will be fine, for instance where a pod is being run for a particular locality, such as diaspora-fr or joindiaspora.co.uk, but in general I don't see sending (potentially) mixed-language messages as worse than always sending a message in one language.

I don't really see an ideal option here, and I don't feel strongly one way or the other. Both approaches have drawbacks.

How about this: keep all the default text in one field in diaspora.yml.example. The message sender code could (I hope) check this field against defaults.yml and, if the two are identical, use the i18n text (which would be identical in the en.yml locale). If, on the other hand, the podmin has made any changes to this field in diaspora.yml, this customised text in diaspora.yml will be used rather than any i18n locales. That way messages could be sent in users' preferred languages *if* the default text has remained unchanged, but if the podmin has customised the text, it will be sent to each user in the language set by the podmin. A note that the welcome message will not be localised if the podmin changes the text could be added to the explanation of this feature in diaspora.yml.example.

**Comment by goobertron** [comment]
If there is any text I can add to the default to make it less likely for a podmin to feel they need to customise the text (i.e. information that would be useful to users of any pod), let me know and I'll add it.

If we decide to stick with the fixed-language message for now, then I can make a PR with that text once everyone's happy with the default text - unless either @TwizzyDizzy or @fap- wants to do it - and localisation can be a later refinement, if we can find an elegant solution.

**Comment by jhass** [comment]
Yeah, I guess having the default localized and have the config option override the localized version is the best compromise. Though I think I actually wouldn't even mind to not make it configurable at all.

**Comment by goobertron** [comment]
Perhaps we should take a vote on whether or not to have this configurable.

**Comment by denschub** [comment]
I removed any target milestone on this issue since we just froze the third target release without any action in this issue. Will add a new target as soon as there is activity again.

**Comment by TwizzyDizzy** [comment]
@denschub erm... this has been implemented and released already and I'm actually using it on my pod.

**Comment by TwizzyDizzy** [comment]
*ping* this issue can be closed (see last comment). A question though:

Currently my config snippet regarding the welcome message looks this way:

```
    ## Welcome Message settings
    welcome_message: ##Section

      ## Welcome Message on registration (default=false)
      ## Send a message to new users after registration
      ## to tell them about your pod and how things
      ## are handled on it.
      enabled: true

      ## Welcome Message subject (default='Welcome Message')
      ## The subject of the conversation that is started
      ## by your welcome message.
      subject: "Welcome on my pod and to diaspora!"

      ## Welcome Message text (default='Hello %{username}, welcome to diaspora.')
      ## The content of your welcome message.
      ## The placeholder "%{username}" will be replaced by the username
      ## of the new user.
      text: "Hi %{username},

thanks for joining diaspora and choosing my pod, I hope you will enjoy your time here!

If you encounter any issues with my pod now or in the future, do not hesitate to contact me and tell me about them.

You can reach me at any time, just send a mail to: ---podmin mail---

Cheers
Thomas (operator)"
```

The message that is sent to the user unfortunately doesn't contain the two line breaks (for example between "them." and "You can" in the last paragraph but does only contain one (so in the message the second line is below the first without an empty line in between.

I already tried to escape the line breaks with \n, but to no avail. Any idea?

Cheers
Thomas

**Comment by fap-** [comment]
Just checked out master and it seems to work for me when I use escaped linebreaks "\n"?
![welcome_message_linebreaks](https://cloud.githubusercontent.com/assets/459631/13481062/c6d9b43c-e0e2-11e5-8619-747ce3a3d945.png)

Config was:
`text: "Hello %{username},\n\n welcome to diaspora."`

**Comment by denschub** [comment]
@TwizzyDizzy: eh, you are right, this is already implemented!

However, please open a new issue since this gets a bit messy otherwise.

**Comment by TwizzyDizzy** [comment]
No need to - in fact it worked with the "everything in one line with escaped newlines"-approach. Thanks @fap-.
