### ISSUE TITLE
Open external hyperlinks into seperate tabs in the mobile version too

### ISSUE THREAD

**Issue by Ravenbird** [diaspora/diaspora#6044]
Into the desktop version of diaspora external links will open in a new browser tab/window. Into the mobile version external links will open into the same tab/window which is diaspora in. Modern mobile Browsers support tabs since a long time and it's easy to switch between these tabs. So why don't open external links in a separate Tab into the mobile Version too?

Sorry for my bad English. Learned it long time ago and don't have a lot of practise.

**Comment by polsVoice** [comment]
Actually, I argue that we shouldn't have pages opening in a new window / tab on *any* platform. There are many reasons for this, but I think [this article sums up the main objections.](http://www.dave-woods.co.uk/why-opening-external-links-in-new-tabs-should-no-longer-be-standard-behaviour/) The biggest issue, in my opinion, is that it's confusing for novice users and aggravating for advanced users.

For novice users, it breaks the back button. The expected behavior is that the back button will take you back to the page you were previously viewing; opening it in a new tab prevents that. For advanced users, it takes control away from the user. If I want to open a page in a new window or tab, I can do that with a right-click or middle-click. Programming them to open on their own takes that control away from me.

Additionally, there are accessibility issues. For example, users who are accessing the website with a screen-reader may be confused by a page that opens in a new tab unannounced.

**Comment by AugierLe42e** [comment]
While we can discuss the points raised in the article, they make absolutely no sense in the case of the mobile version, which has to behave like an application, i.e: *always* open the links in a separate tab/window. This is particularly needed in the case of @Flaburgan's [native webapp](https://github.com/Flaburgan/diaspora-webapp) which do not manage the tab system, hence, always open the links in the current window.

**Comment by svbergerem** [comment]
Looks to me like we are doing that for quite some time now (<=2013):

https://github.com/diaspora/diaspora/blob/652050a/lib/diaspora/markdownify/html.rb#L9

Am I missing anything?

**Comment by denschub** [comment]
No, you did not miss anything. I can confirm there is a blank target on mobile.
