### ISSUE TITLE
[Getting Started] The aspect combobox doesn't reload when creating a new aspect

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#6120]
On the getting started page, when you have been invited by someone, there is an aspect selection dropdown to put the person in an aspect. This dropdown allows you to create a new aspect. Once you submitted the modal, the aspect dropdown doesn't contain the new created aspect, so you can't select it.

**Comment by theworldbright** [comment]
By comparing it to the profile page's aspect combobox's contact backbone view (contact.js), the getting started page's aspect membership backbone view (aspect_membership_view.js) is missing a `app.events.on("aspect:create", function(){ window.location.reload() });` handler.

**Comment by Faldrian** [comment]
This quick hack would cause reloading of the whole page... that's not convenient. I will refactor the aspect-dropdown to a true backbone-component (currently the HTML is generated via ruby and updated via ajax when you populare a hovercoard...). When this is a backbone-component, the client can manipulate the aspect-dropdown in any possible way, so adding a newly created aspect to the already shown list should be straight forward instead of consist of a series of hacks. :)

**Comment by svbergerem** [comment]
Once you ported the aspect dropdown to a backbone template you can just rerender it on change.

**Comment by Faldrian** [comment]
> Once you ported the aspect dropdown to a backbone template you can just rerender it on change.

That's my plan. :)

**Comment by Flaburgan** [comment]
@Faldrian this issue is currently a blocker for the 0.6 release. Do you plan to work on it in the coming weeks?

**Comment by Faldrian** [comment]
No, sorry. I stopped working on this issue some time ago, sorry for the 
missing status update. As far as I can see I will not continue working 
on this.

**Comment by cmrd-senya** [comment]
Looks like [this](https://github.com/diaspora/diaspora/blob/develop/app/helpers/aspect_global_helper.rb#L16-L25) size defining piece simply doesn't work, because the `btn-` size classes are missdefined. There [are no](http://getbootstrap.com/css/?#buttons-sizes) `btn-small` and `btn-large` in Bootstrap but `btn-sm` and `btn-lg`.

I wonder if I could just drop this size determination support since we don't use anything besides the default in fact anyway?

**Comment by Faldrian** [comment]
Size was never the problem when I looked at it. But it's been so long, I can't really say anything in this matter.

**Comment by Flaburgan** [comment]
Just to be sure, the step to reproduce this problem is get an invite link from an account, register using that link

**Comment by Flaburgan** [comment]
Oops sorry wrong button.

**Comment by cmrd-senya** [comment]
> Just to be sure, the step to reproduce this problem is get an invite link from an account, register using that link

Yes, but refactoring aspect dropdown to a backbone component requires changes for every usage place anyway.
