### ISSUE TITLE
user export: conversations not included

### ISSUE THREAD

**Issue by redmatrix** [diaspora/diaspora#6138]
Related to issue #6115 

The export of posts does not contain the complete message threads, but only the top level post and any comments which you made personally. This makes it impossible for an import utility to reconstruct the conversation, especially since due to issue #6115 there is no identifying information for the post so you can't even look it up on the original site (which could very well be dead and possibly is the reason you need to relocate).  We know from experience that trying to re-create a conversation from a federated site is likely to be incomplete, so all the more reason to include all the comments and likers in the export file. 
##

**Comment by goobertron** [comment]
Exporting other people's comments means exporting other people's data. We shouldn't be allowing that.

We'd have to find a way to make sure that the data exported contain a firm link to the conversation on any of the pods involved in it, so that even if the pod on which the conversation was started has closed, once this export has been imported to a new seed on a new pod, that seed will, when linking up with the other seeds involved in the conversation, be able to pull in all the remote comments in that conversation from any one of those seeds involved.

This may be difficult to do, but we definitely shouldn't be implementing a means of downloading *other people's* data, in my opinion.

**Comment by redmatrix** [comment]
We've a difference of opinion, but allow me to elaborate. Think of a conversation thread as a container (or "box"). It contains the top level post, comments and likes. Let's call those "books". I can create one of these things, and in some respects you're acknowledging that I "own" the box as I can create it, control who can look inside it, control who can put books in it, and I can even *destroy it completely* - along with everything inside it. Yet if my house is burning down, you're saying I can't take *my* box to safety unless I remove all the books that other people put inside it, leaving them in the house to burn. You can't have it both ways - either it is my box (along with everything inside it) or it isn't; in which case I have no rights over who takes things in or out --- and if I destroy my own books and the box itself, their books would then need to also remain intact; e.g. I have no right to destroy their comments and likes by removing my top-level post. 

Anyway, I understand Diaspora still has a fairly simple 1-to-1 ownership model, so please close this issue if this is unworkable; but I believe you're going to have to grapple with this eventually when it comes to forums and shared photo albums and other things that can different authors and "owners" and who has exactly what rights in these more complex ownership scenarios.

**Comment by jhass** [comment]
I haven't really made up my mind yet, just to clarify, from the technical side this is possible, we do store the authors signature and can export it.

**Comment by redmatrix** [comment]
Good point - the signature would also be a necessary component, though I was responding more to the policy/ownership issues raised by @goobertron .

**Comment by cmrd-senya** [comment]
Well, I think, that if a user sees comments of a person through a web interface it doesn't make much sense to disallow him downloading them in the archive, since it just a change of the format. (it feels like a DRM system).

However, refetching the comments that lack from the conversation is actually what must be possible and I wonder why there is still no issue on the tracker for that. But that is a separate quite complex story as @goobertron said.

I may implement this as a part of #6726 if nobody minds.

**Comment by cmrd-senya** [comment]
(I guess it's nice if @jhass or @goobertron or @denschub tells if it's okay in their opinion so it is felt more like consensus)

**Comment by cmrd-senya** [comment]
[Here](https://www.loomio.org/d/qsVJ2K1t/proposal/dD4N0kl7) is a loomio proposal

**Comment by cmrd-senya** [comment]
Okay, the loomio proposal has passed. I think undecided label can be removed. The comments will be included into the back up archive.
