### ISSUE TITLE
User with no avatar has no image in dropdown Notifications menu

### ISSUE THREAD

**Issue by pizzamaker** [diaspora/diaspora#6149]
It should at least display the gray default image.

Images:
https://i.imgur.com/9zxRteE.png

https://i.imgur.com/YSRAunt.png

**Comment by jaywink** [comment]
@pizzamaker pod url or version please? I'm guessing this might have been fixed, so need to know which pod the screenshots are from, thanks.

**Comment by pizzamaker** [comment]
DiasporaBR, pod version 0.5.1.1-p56df5978

**Comment by jaywink** [comment]
Yea, reproduced by manually "destroying" the correct image url. This happens when the browser gets an 404 for the image and the `alt` is rendered by the browser instead. Not much that can be done on the backend for this - we would need some JS to replace all the broken images with the default avatar.

**Comment by Faldrian** [comment]
I fixed something like that a while ago for avatars on status_messages ... will apply the same fix for the notification-dropdown. :)
