### ISSUE TITLE
Clicking on a picture sometimes fallsback to 404 on mobile

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#6177]
I'm a bit disturbed this issue doesn't already exists. On mobile view, clicking on a picture sometimes redirect to 404. My early investigations seems to show that it happens for pictures posted by people that are not on same pod.

**Edit:** The link on mobile refer to an address in the form: `/people/<id>/photos/<photo-id>` which indeed redirect to 404. I suppose this is because the picture doesn't exist on user's own pod (and actually, it is displayed using Camo).

**Comment by svbergerem** [comment]
This is related to #4755 which has been closed because of #6082.

I tried this with the first few photos in my stream and I'm not able to reproduce it. (All authors are on a different pod)

**Comment by AugierLe42e** [comment]
It makes it on d-fr with [this post](https://diaspora-fr.org/posts/1378761).

**Comment by svbergerem** [comment]
That is a limited post. Maybe it only happens with those?

**Comment by AugierLe42e** [comment]
Hmm... That could be. But then, it's a problem because it's difficult to share a minimal example :/

**Comment by goobertron** [comment]
> It makes me this on d-fr with this post.

I see that post (and image) on diaspora-fr when signed in, using desktop and mobile versions in FF39.0. (The account on diaspora-fr is not the account from which I made the post, which is on another pod.)

However, I see that there is a difference. In the mobile version the image is far smaller. This might be intentional (and appropriate for devices with small screens) but it doesn't scale up properly.

Using desktop version, the following image is served: https://diaspora-fr.org/camo/8d3b9c9d46ed84ef701c1c662d1be23a6de88a7b/68747470733a2f2f706f642e6f726b7a2e6e65742f75706c6f6164732f696d616765732f7363616c65645f66756c6c5f39623730613562633436363662343433613362622e706e67

![68747470733a2f2f706f642e6f726b7a2e6e65742f75706c6f6164732f696d616765732f7363616c65645f66756c6c5f39623730613562633436363662343433613362622e706e67](https://cloud.githubusercontent.com/assets/2530168/8619318/fa27458c-270d-11e5-8137-7c724ddbd2c6.png)

Using mobile version, the following image is served: https://diaspora-fr.org/camo/8178cb7a4334b5906e7d9074fd4152ede02946f7/68747470733a2f2f706f642e6f726b7a2e6e65742f75706c6f6164732f696d616765732f7468756d625f6c617267655f39623730613562633436363662343433613362622e706e67

![68747470733a2f2f706f642e6f726b7a2e6e65742f75706c6f6164732f696d616765732f7468756d625f6c617267655f39623730613562633436363662343433613362622e706e67](https://cloud.githubusercontent.com/assets/2530168/8619325/14ff1826-270e-11e5-8028-9eda083319a3.png)

However, when you click on the image within the post, a 404 is returned. It looks as though for some reason the {people}/{photos} link is still used rather than a camo link in this bit of code, as you said. If I right-click on the image and view the image or copy its URL, the correct camo link is served and I can see the image.

That's a bit of a long-winded way of confirming what you said!

**Comment by Sneagan** [comment]
I think I'm seeing this bug. Is there a fix or branch I can look into?

**Comment by svbergerem** [comment]
I was able to reproduce this. It happened in a limited post and the share visibilities of the photo are empty.
```
Post.find_by_guid("1234567890guidofthepost").share_visibilities.size
=> 1
```

```
Photo.find_by_id(12345).share_visibilities.size
=> 0
```

Thus `current_user.photos_from(Person.find_by_guid(params[:person_id])).where(id: params[:id])` in [the photos controller](https://github.com/diaspora/diaspora/blob/bcace2d/app/controllers/photos_controller.rb#L11) is empty.

The post came from another pod. @SuperTux88 could you check if you find an error in our federation code?
