### ISSUE TITLE
refactor Rspec syntax to use let instead of instance variables

### ISSUE THREAD

**Issue by zaziemo** [diaspora/diaspora#6192]
@Realtin and I are learning to use Rspec and want to refactor existing specs using this best practice: http://betterspecs.org/#let

**Comment by denschub** [comment]
I've merged this into develop and stable. Thank you for your contributions!

For future reference: 20 commits for changes on 9 files is a bit too much. Merging the commits would be hard in this PR since you both worked on the same files, but please squash the commits in your further PRs down to a smaller number. If you need help with that, just ping us on IRC.
