### ISSUE TITLE
Issues with webfinger and federation with Hubzilla/Redmatrix

### ISSUE THREAD

**Issue by jeroenpraat** [diaspora/diaspora#6405]
[Here](https://gurus.red/channel/one/&f=&mid=df1309f763ccf60d61b46dddaa932806df38de0586bbae8616a1c37e168947ca@gurus.red) Mike MacGirvin says:
> Significant changes were made to Diaspora 25 days related to webfinger discovery. They don't seem to be able to discover redmatrix/hubzilla channels any more via old webfinger (and no, they haven't implemented the new webfinger either). I've looked over the changes and don't see anything obvious, but I don't have a Diaspora test site or logfile access on that side. This will probably a Diaspora dev with federation knowledge to sort out. Existing connections may or may not work, but it looks like new connections are stuffed.

I have Hubzilla (fka Redmatrix) log with Diaspora specific information. What I did was first creating a new test account on my Hubzilla hub (https://hubzilla.nl), followed by trying to connect to 2 different Diaspora test accounts (1 on Geraspora, 1 on Framasphere, both running the newest stable D* version). Connection requests are never received on the 2 Diaspora test accounts. Existing Diaspora<>Hubzilla/Redmatrix connections seems to be working normally.

**Comment by jeroenpraat** [comment]
P.S. I have a log file, but I don't know what is relevant and save to share with the Diaspora devs. I have to council Mike for that.

**Comment by redmatrix** [comment]
I have created an account for test purposes "trouble@macgirvin.com". If I search for this channel from the Diaspora navbar it consistently returns "no one was found". E.g. a person object is never created after webfinger lookup. On the hubzilla side I can see that the host-meta and personal XRD are fetched using classic (circa 2010) xml based webfinger. Our XRD contents have not changed since this was last known to be working. I get the same results for trouble@zothub.com, which is a redmatrix site and the Diaspora has not changed there and which has successfully worked with Diaspora in the past. My initial guess without having access to Diaspora logs is that there is a subtle difference in our XRD format (which we made compatible with Diaspora some time ago) and that Diaspora is now doing stricter checking of the XRD.  

I do see that Diaspora now has a salmon endpoint mentioned in the personal XRD and the host-meta is no longer accessible from a browser (Firefox) without providing .xml suffix. This may require an appropriate Accept: header from Firefox. I believe we are serving the XRDs as text/xml (as we always have) in case this information is relevant. 

I must question whether the salmon rel link is a legitimate salmon endpoint or just pointing to the user/member's receive endpoint for "Diaspora salmon" - which is not salmon protocol compliant. I suspect it's pointing to an illegal salmon endpoint because there is no salmon public key provided. I am loathe to add such an endpoint because it requires supporting the 4 or 5 different variants of salmon that were legally specified by that specification; none of which are supported by Diaspora to my knowledge.  I could just support "the latest" but again this isn't compatible with Diaspora in any way, shape or form and neither is Diaspora compatible with it. Anyway, I mention this endpoint because the "user discover" tests may require this XRD declaration as part of their validity checking. In any event I recommend it either be renamed to 'diaspora-salmon' - or Diaspora made salmon protocol compliant.

Anyway we mostly need somebody to look at the logs on that side and let us know what is failing in user discovery via webfinger so we can come up with a fix on our side.

**Comment by jeroenpraat** [comment]
Has it maybe to do with this: https://github.com/diaspora/diaspora/pull/6151/

**Comment by jeroenpraat** [comment]
Or/and this: https://github.com/diaspora/diaspora/pull/6310

**Comment by svbergerem** [comment]
See https://github.com/SuperTux88/diaspora_federation/commit/b114973785f94fc49ae4c2f1c7c78bb8e51cc4de and https://github.com/SuperTux88/diaspora_federation/commit/c3e290465f2808e3d94cec0112ea6a263f704e20.

**Comment by jeroenpraat** [comment]
Thanks, that seems promising. When will this fix go into Diaspora stable (or when will a new stable be released)?

**Comment by jhass** [comment]
See https://github.com/diaspora/diaspora/milestones

**Comment by jeroenpraat** [comment]
Thanks. I see 0.5.4, due by Oct 18. Is there not a change to release a 0.5.3.2 with this fix? For Redmatrix and the upcoming Hubzilla this is important.

**Comment by jaywink** [comment]
Should we hotfix, once @SuperTux88 submits the PR? I'd be ready to :+1: such a hotfix, but of course we need core team members vote on this. I think it is important we do our bit to support federation with others.

@jhass @denschub @svbergerem @Flaburgan @Raven24 etc?

I'm prepared to "sponsor" this by doing the work of cutting the release.

**Comment by SuperTux88** [comment]
Sorry that I didn't comment on this earlier, but I had less time. I have released a new version of the federation-gem (PR #6410) and tested this already on my pod.

The problem was that the new gem has a stricter validation than the previous implementation. And friendica and redmatrix is not valid against this. I now have removed a few constraints so that friendica and redmatrix are valid again.

* in the .well-known/host-meta the lrdd element has no `type="application/xrd+xml"`
  * I have removed the additional selector and only search for `rel="lrdd"` now.
* the webfinger-xml from redmatrix has no `<Alias>` and `rel="salmon"` elements
  * I have removed these constraints, because these elements are not used at the moment.
* friendica seems to have two `<Alias>` elements, but the first is the same as the `<Subject>` element (acct:...). Why???
  * I ignore this now and use the second `<Alias>` which is correct.

@jaywink: I don't think we need a hotfix for this (I asked @jhass already before this issue was opened, because I saw the problem on my pod). Because, as I understand it now, diaspora does not officially support friendica/redmatrix, but friendica/redmatrix have support for diaspora. The old (pre-federation-gem) diaspora pods are not affected by this. But maybe we wait to see if other core team members see this differently.

@jeroenpraat: If you need this now, you can also fix this on your side, by implementing the missing stuff.

**Comment by SuperTux88** [comment]
@jeroenpraat @redmatrix @annando: and before I forget it: I changed some stuff in the discorvery-process. If you want to stay compatible, you should do this on your side too:

* `rel="http://joindiaspora.com/guid"` is now deprecated in the webfinger-xml, the guid is now searched in the HCard with the selector `.uid`
* `rel="diaspora-public-key"` is also deprecated in the webfinger-xml, the public key is now searched in the HCard with the selector `.key`

Currently diaspora does generate both in webfinger and HCard, and parse first in the HCard and fallback to the webfinger, to stay compatible with older pods (and friendica/redmatrix). But the old stuff will be removed later.

You should also add the new stuff to the HCard and change your parsing, and remove the old stuff in the webfinger later.

**Comment by redmatrix** [comment]
> friendica seems to have two <Alias> elements, but the first is the same as the <Subject> element (acct:...). Why???

This was required for statusnet (GNU-social) federation at one point. I don't know if it still does.  

>    I ignore this now and use the second <Alias> which is correct.

Just a warning - don't count on the URL form being the "second one". There is no guaranteed ordering. And if you do provide a URL form, you need to support LRDD on that URL if I recall.

**Comment by redmatrix** [comment]
> rel="diaspora-public-key" is also deprecated in the webfinger-xml, the public key is now searched in the HCard with the selector .key 

Friendica already provides an hcard .key with a different and incompatible PKCS/DER/ASN.1 encoding from Diaspora. We can do key type detection and conversions, but I don't know if Diaspora has this ability. We can't easily change our key format and the way it's used in our hcards and this could cause a serious compatibility problem.

**Comment by Flaburgan** [comment]
@jaywink I would not block an hotfix release if you want to handle it, I agree it's important to help support other projects federation.

**Comment by annando** [comment]
@redmatrix after a quick look into the source code it seems to me as if mod/hcard.php mostly is a copy of mod/profile.php and that many of the values like the "key" value aren't used there for friendica. (But they seem to appear there because they are part of the profile page as well). 

Am I right? Then it should be no problem to do some clean up.

**Comment by denschub** [comment]
No. In my opinion, releasing a hotfix to make external services work is neither good nor required. Hotfixes are for "shit, everything is broken"-releases and security hotfixes. This issue is clearly neither of those.

**Comment by SuperTux88** [comment]
> Just a warning - don't count on the URL form being the "second one". There is no guaranteed ordering.

@redmatrix: I use the one starting with "http" :) so no worries

And about the Key:

@redmatrix @annando: I think friendica already provides the correct key in the HCard (I tested this and sharing a limited post works in both directions). So friendica only needs to change the guid in the HCard.

**Comment by jaywink** [comment]
Sure, no hotfix.

> Because, as I understand it now, diaspora does not officially support friendica/redmatrix, but friendica/redmatrix have support for diaspora.

Does that mean we don't have to care about friendica/redmatrix? ;)

Just as a generic comment - it would be nice if we could stop thinking as what is ours and what is theirs. Please, lets try to keep in mind that diaspora* is decentralized and the protocol cannot be owned by just the diaspora software any more. It is more widely used. I would like that it would not be considered as "what we do and the others do theirs" but that anyone using the protocol would have some say in the changes.

> Currently diaspora does generate both in webfinger and HCard, and parse first in the HCard and fallback to the webfinger, to stay compatible with older pods (and friendica/redmatrix). But the old stuff will be removed later.

I'm not sure what "later" means here, but I've not heard of any talk about changing the protocol and making any incompatible changes. Any change that makes old software incompatible, whether that be diaspora, friendica or redmatrix - needs a proper deprecation plan and pre-announced schedule. We can't just build something, let others adopt it and break it at will. The protocol is larger than the software and all the stakeholders, ie all the people who use it, should get to participate in the discussion on what and when should change.

**Comment by jeroenpraat** [comment]
I thought 'The Federation' was moving forward, but so far I see it we have a long way to go.

**Comment by jaywink** [comment]
> I thought 'The Federation' was moving forward, but so far I see it we have a long way to go. 

Yes, it seems like it. Personally I'm surprised and disappointed.

Maybe discussion can continue here.

https://www.loomio.org/d/ohy5c3En/changes-to-the-diaspora-protocol

**Comment by annando** [comment]
@SuperTux88 The guid stuff is done: https://github.com/friendica/friendica/pull/1894

But: It really would have been nicer if we had had a little bit more preparation time.

**Comment by SuperTux88** [comment]
@annando: there was no need to do this right now, the guid (and key) in the webfinger-xml is still supported :)

the stuff what broke here was something else and was not planned, sorry for that.

**Comment by annando** [comment]
@SuperTux88 No problem. Since we are just about doing a new release, it fitted well into it.
