### ISSUE TITLE
[feature] add support for LDAP authentication

### ISSUE THREAD

**Issue by pravi** [diaspora/diaspora#6475]
disroot.org integrated email, xmpp and owncloud with single sign on, but diaspora needs a separate account. If we add LDAP as a supported authentication method, it would be useful to setups like disroot.org which already has a userbase which they want to integrate with diaspora.

**Comment by svbergerem** [comment]
We closed the same feature request about two years ago. #4748

**Comment by jhass** [comment]
Closing as duplicate. If you want to see this in main, find a committed and active maintainer for it.

**Comment by pravi** [comment]
This is not helpful. I'm trying to find support through bounty source and you can't insist on finding a supporter before even looking for one.

**Comment by jhass** [comment]
I can, we had to rip out tons of stuff already because nobody maintained it, I'm rather careful about adding new things that will easily remain unmaintained.

**Comment by jhass** [comment]
The forks that implemented it are all outdated and broken, there's clearly nobody willing to commit to maintaining it.

**Comment by jhass** [comment]
Oh and Bountysource might motivate yet another integration, but how likely is it that that contributor will also maintain it?

**Comment by pravi** [comment]
If it is used in community infra like disroot.org, they'd want to keep it working.

**Comment by jhass** [comment]
That might generate bugreports, but will there be somebody to do the fixes?

**Comment by pravi** [comment]
We can make maintenance a criteria for accepting contributions on it.

**Comment by jhass** [comment]
Looking forward to the pull request including such a commitment  then. I see no reason to track an issue for it.

**Comment by pravi** [comment]
Status of bounty source is linked to status of this issue. Keeping it closed will give a wrong message to any effort to seek support.

**Comment by jhass** [comment]
As explained I think a BountySource for this would only encourage a one time contribution, not a long term maintenance commitment.

**Comment by JosephKiranBabu** [comment]
@pravi @jhass We're trying to integrate diaspora into the FreedomBox project. FreedomBox uses LDAP for most applications. 
Would you be willing to merge LDAP integration into diaspora master if the FreedomBox team maintains it?

**Comment by Flaburgan** [comment]
I would say yes but we also need @SuperTux88 and @denschub opinion here I guess.

**Comment by denschub** [comment]
Basically, see this comment: https://github.com/diaspora/diaspora/issues/6475#issuecomment-146867235

**Comment by SuperTux88** [comment]
Basically, what @denschub says :)

But there were also requests to use diaspora with LDAP in schools and other organizations. And while it's cool when a school has a diaspora pod, that also leads to some problems: When the person leaves the school and the LDAP-account is closed, then they also loose their diaspora-account. And while you can reopen a LDAP-Account, a diaspora-account can't be reopened and is lost forever. And I somehow don't want to support that scenario.

We can maybe only lock access (that can be undone), but then the users can't close their accounts themselves, which is also bad.

So I think we need a solution where the users still are in control over their accounts, even when the LDAP-account is closed. Or otherwise it would be better for the user when a school just provides an invite-link and they create their own account, without linking it to LDAP.

**Comment by albjeremias** [comment]
please, when kids go to school they loose their LDAP access? what a lame argument. this is an oauth2 authentication, so you have an account associated with a login... you can solve that very easily, by making the user giving an email for recovery... 

this post is a flame on the diaspora users, and you are making diaspora users feel fools... 

this should be open, there is no reason to close, other than a political reason to not support LDAP, and the kid school is not a technical or political valid reason to close this thread.

**Comment by lil5** [comment]
@SuperTux88 I'm  sorry but that's a totally unrelated issue; the issue you are actually referring to is database import and exporting from one account to another. LDAP does not create, support or remove the issue of changing server.
