### ISSUE TITLE
remove users from roster, if you stop sharing with them

### ISSUE THREAD

**Issue by kas70** [diaspora/diaspora#6497]
the problem is: if i start sharing with that unfollowed person again, i have a duplicate in my roster, which is not nice.

**Comment by jhass** [comment]
Is that a Vines or a Prosody setup?

**Comment by kas70** [comment]
tried this on sechat.org. so it should be vines?!

**Comment by jhass** [comment]
Yes.

**Comment by Zauberstuhl** [comment]
same here.. this is not a diaspora issue could you open it in https://github.com/diaspora/vines ?

Also I wasn't able to reproduce it. Can you describe it step-by-step? Since vines has very restricted access to the database that could be also a temporary problem with jsxc (roster update).

Thanks for your effort

**Comment by kas70** [comment]
I tried to reproduce this. If you start a new session (log out and in), the roster is updated. Is there a possibility to update the roster within a user-session? Anyhow this may not have a very high priority.
moved [here](https://github.com/diaspora/vines/issues/74).
