### ISSUE TITLE
What if my nickname (name) is occupied, let's make a way to contest it!

### ISSUE THREAD

**Issue by nicubuga** [diaspora/diaspora#6760]
Hi, %topic. What if my name is Nicu and i want to register nicu@joindiaspora.com? It's occupied (and it's impossible to register now, i know) but why I shouldn't have my own nickname clean and nice? How about a system of contestation based maybe on time the other person is not using his account or idk what. I have the same problems with twitter for example where the owner of http://twitter.com/nicu is not using the account since 2008. 8 years and so I can't take this name? Strange...

**Comment by svbergerem** [comment]
There are a some problems that we would introduce with this feature.

Since you are a new user you will need a new keypair and we would have to delete all old data. We would also have to send a signed message to all pods that the old account is no longer existent so they can remove the corresponding contacts from all aspects.

But there are pods that have your profile data (including your public key) that you don't know about because they fetched your profile some time ago and your pod doesn't remember. Those pods will never receive the signed message to make the old public key invalid and thus will send your pod messages that it is unable to encrypt. They will also reject new messages coming from your account since they are signed with the new keypair that those pods don't know about.

And even if the pod receives the signed message and knows that this is a new user with the same diaspora id: how do we tell users that the profile they are looking at belongs to a different user than the one they saw a week ago with the same diaspora id?

We should also make sure that all other social networks that are able to use the same federation protocols are also able to handle these changes.

Solving these problems isn't easy and I don't think that it's worth the effort - neither implementing it nor maintaining the feature afterwards so it doesn't break with future releases. I'll close this issue. If you feel strong about this issue please open a thread on loomio and make sure that we have proper specs that solve all kinds of problems that we introduce with this feature before anyone starts implementing it.
