### ISSUE TITLE
"Contacts" badge number possibly shows a wrong value

### ISSUE THREAD

**Issue by wolneykien** [diaspora/diaspora#6790]
Hi there,

Can some one explain me, please, what the "Contacts" badge number on a person's profile page does mean and how exactly is it calculated? (probably, [this line](https://github.com/diaspora/diaspora/blob/master/app/assets/templates/profile_header_tpl.jst.hbs#L94)). The issue is that it doesn't look like a number of contacts that are visible to the visitor, nor it is the total number of contacts the person has (i.e. `SELECT count(*) FROM contacts WHERE user_id = :person_id`).

TIA.

**Comment by svbergerem** [comment]
The number of contacts is calculated here: https://github.com/diaspora/diaspora/blob/f3e897a/app/controllers/people_controller.rb#L90. If you are on your own profile page then the number is the same as the “All contacts” number on your contacts page. Otherwise this is the number of contacts that you are allowed to see. For each aspect you can decide if the contacts in this aspect should be able to see each other, so the number is the number of contacts in aspects that you have been added to and where contacts are allowed to see each other.

I'll close this issue since it seems to me like there is nothing wrong with the contacts count. We can of course reopen this if there is anything wrong with the calculation.
