### ISSUE TITLE
Poll display "1 vote" when 0%

### ISSUE THREAD

**Issue by SansPseudoFix** [diaspora/diaspora#6835]
Expected: 0 vote -> 0%

Test on diaspora-fr.org, version  0.5.99.0-p8e47632d 

![bug_poll](https://cloud.githubusercontent.com/assets/6507951/15320222/a9e754be-1c2f-11e6-8176-10317620164d.png)

Ping @Flaburgan

**Comment by Flaburgan** [comment]
As I wrote https://github.com/diaspora/diaspora/pull/6641 I'll have a look at this one, please assign me.

**Comment by Flaburgan** [comment]
Okay so I checked that and it comes from the local. @SansPseudoFix you should be able to confirm that by setting diaspora* to english and see 1 vote becomes 0 vote. However, I didn't find the `answer_count` segment on webtranslateit, @jhass can you please update the website?

**Comment by SansPseudoFix** [comment]
> @SansPseudoFix you should be able to confirm that by setting diaspora* to english and see 1 vote becomes 0 vote. 

Oh, you're right.

**Comment by denschub** [comment]
> please assign me.

Impossible, GitHub does not allow non-team-member assignees. Writing a comment is enough, though. :)

> I didn't find the `answer_count` segment on webtranslateit

We used to push only stable translation to wti, but since we should start polishing 0.6.0.0, I've decided to push the develop locales. You should find the translations up after wti is done importing, which should take a only few minutes.

**Comment by svbergerem** [comment]
![1 vote french](https://cloud.githubusercontent.com/assets/3798614/16465214/e0e19116-3e3d-11e6-9785-997535f956ca.png)

> This plural form is used for numbers like: n in 0..1

**Comment by Flaburgan** [comment]
Why does the indication not match the english one? (1 at the left, 0..1 at the right)

**Comment by goobertron** [comment]
I haven't looked at a poll for a while, but I thought the figure for votes given next to the percentage is for total votes placed on the poll, not the number of votes *for that option*. Thus it is to be read as 'Nope - 0% of 1 total vote on this poll', not 'Nope - 0% which equals 1 vote'.

If I'm correct, this isn't a bug as it is the way it has been coded. It is, however, a little confusing, and would make sense to list the number of votes for each answer next to that answer, rather than the figure of total votes on the poll (which is, in any case, given above).

**Comment by Flaburgan** [comment]
@goobertron the bug is not present in the english language, it's a translation problem. And the number represents the number of votes for this option, not the total of votes ;)

**Comment by jhass** [comment]
Locales update, @Flaburgan could you verify?

**Comment by Flaburgan** [comment]
Problem fixed! Thank you everyone!
