### ISSUE TITLE
Invite your friends url logs out users that are logged in 

### ISSUE THREAD

**Issue by COLABORATI** [diaspora/diaspora#7057]
Some people told me that the "invite your friends"-link I was posting them logs them out of diaspora. 
I tried to understand their problem and simulated what happened, but please excuse me when I am wrong on this, it is a little bit tiring to test with different browsers and cookies etc., however I have replayed this sequence now a few times with the same result:
* login to some pod in browser A with account A
* login to same pod in browser B with account B
* copy "invite your friends"-url from browser A to browser B
* follow that link in browser B (I mean copy to url bar and press enter, just to be clear)
* account B in browser B is now logged out and sees the login screen of the pod

I would expect this not to happen and if this behaviour of the "invite your friends"-url can be confirmed by others it should be classified as a bug. 

Thanks for your attention!

**Comment by goobertron** [comment]
I think I can see the logic in this behaviour. An invitation is something sent to people who do not have an account at Diaspora. Therefore, when an invitation token is used in a browser which has an active 'signed in' cookie, this is not the normal circumstance. To be able to use the invitation token.

There are two choices at this point: either to automatically end any current Diaspora sessions, or to ask whether the person wants to continue the current signed-in session.

Although unlikely, it is possible that the person is using the invitation token on a shared computer on which someone else previously signed in to Diaspora and forgot to sign out. There is therefore a potential security issue here: if Diaspora said 'it looks as though you're already signed in', it could allow the person using the token to access someone else's account.

As it is safe to assume that the person using a token wishes to create a Diaspora account, it seems to me to make sense to automatically end any current signed-in sessions.

ps: If you've been sending out these invitations to people who already have a Diaspora account so that they can connect with you, you're using the wrong approach. Give them your diaspora ID (the one that looks like an email address, with your pod name at the end) and they should be able to find you through the search facility.

**Comment by denschub** [comment]
> You say that the log-in screen is shown. If that's the case, I think that is incorrect and should be fixed so that the sign-up (create new account) screen is shown.

That's not the case. We show the sign up page, which obviously requires us to invalidate the current session (you cannot sign up or sign in if you are already signed in...), so this is working as expected.

**Comment by COLABORATI** [comment]
Thanks for the fix, this is great!  
@goobertron: I just want to send out / publish *one* url for everyone, of course. I do not want to publish one url for not signed in users and additionally one diaspora address for already signed in users, this would be ultra-awkward. Also having to copy paste user addresses to get to a user page will not help grow diaspora* popularity, I bet. How did you even consider writing this? :)

**Comment by denschub** [comment]
So, thanks to @svbergerem and his PR #7061, you'll now get redirected to the inviters page when you follow a invitation from a signed in sessoin.
