### ISSUE TITLE
mobile: allow sharing with more than one aspect/option

### ISSUE THREAD

**Issue by paskalito** [diaspora/diaspora#7080]
right now when try to adjust the aspect of a new share in mobile i get this:
![screenshot_2016-09-09-11-46-14](https://cloud.githubusercontent.com/assets/8012793/18383171/8c5083c6-7684-11e6-93db-e8f4c63dda87.png)

the problem is that i can eighter choose one aspect or make my post entirely public(eighter way just one optino), but if i don't want something public i usually want to share it with more than one aspect.

so its just the wrong type of selection list i get. i would need one that lets me select multiple options. - i could not find any example right now, but two other ressouces:

https://github.com/davidstutz/bootstrap-multiselect
http://www.aspdotnet-suresh.com/2014/03/jquery-multiselect-dropdown-list-with-checkboxes.html

altough it looks like they solve that inlay - i don't mind to use the OS dialog for that but like this it's just wrong. especially since d\* is all about having more control over your privacy.

**Comment by habruening** [comment]
This is really only related to mobile mode. It is only a small ui issue.

**Comment by sebastienadam** [comment]
I will try to solve this issue. Be indulgent to me, I am newbie to Ruby, RAILS and diaspora*

**Comment by Flaburgan** [comment]
@sebastienadam if you have any questions and need help please come on #diaspora-dev on IRC freenode.

**Comment by HankG** [comment]
I found a Bootstrap way of doing this but before I embarked on it I was looking at the work that Sebastien did already.  Should I be building off of what they did or is that up to me?

**Comment by goobertron** [comment]
It's up to you; you can use the old code if it will save you work; but if it's easier to start from scratch, feel free.

**Comment by HankG** [comment]
I have this mostly working at this point. I used the Bootstrap Mult-select control It behaves the same as the desktop site.  It supports multi-select. It properly disables options when "public" or "all aspects" is selected.  It is sending back the proper selected values or "public" or "all_aspects" as selected by the user.  Functionally this is done except for needing to run through style checker and that sort of thing...except...

The snafu is that if I keep it locked to the right then the window then the drop down menu renders off screen a bit since the left side of the menu aligns with the left side of the button versus the right side of the menu aligning with the right side.  I tried some CSS stuff but couldn't get it working.  Here is a screenshot of what it looks like on the left side now. It's not ready for getting pulled in yet because of that (unless there aren't strong opinions on the alignment moving).  I could use some help getting over that hurdle.  

![image](https://user-images.githubusercontent.com/1683691/47888849-19055d80-de1d-11e8-9e21-e2278b4c8bee.png)

**Comment by paskalito** [comment]
Hey, great to see progress going on :) - i don't qiet understand where the problems with the layout are. ( like from a ux viewpoint) - but i wanted to throw in a question: what happens if you have 20 aspects?

Will you still see them all - be able to select them?

**Comment by HankG** [comment]
@paskalito The problem I identified is that the aspect drop selector is now on the left instead of the right.  Maybe that's a small enough price to pay to not worry about but if there is an easy fix from someone with more CSS knowledge than me I'd take it.  If it is something deep inside the menu code I'd say we probably want to just live with it.  With respect to the menu with lots of Aspects, it has a maximum pixel size.  If you have more than that then it adds a scroll bar like this:  
![image](https://user-images.githubusercontent.com/1683691/47954781-cdf66200-df64-11e8-850b-01929bd507af.png)

**Comment by HankG** [comment]
Actually it works fine as is under iOS (screenshot attached).  The menu is rendered using a native iOS control rather than the HTML5 stuff here.  Looks pretty snazzy I think. I'm trying to scrounge up a working Android device to test now.  One thing I don't like, but I'm not sure I can fix, is that the logic on how Public/All Aspects works doesn't seem to carry over since that is in the JavaScript onChange callback.  I'm not sure there is anything I can do about that though :(
![photo nov 03 13 27 01](https://user-images.githubusercontent.com/1683691/47955329-ef5b4c00-df6c-11e8-971f-4c892e38507a.jpg)

**Comment by HankG** [comment]
Yeah similar thing on Android... 
![photo nov 03 13 41 48](https://user-images.githubusercontent.com/1683691/47955447-b15f2780-df6e-11e8-987f-5b751b17a02a.jpg)
