### ISSUE TITLE
Conversation impossible 

### ISSUE THREAD

**Issue by tursiops33** [diaspora/diaspora#7176]
Hello everyone 
I'm having an issue with the conversation feature. 
If I understand well you need to add someone to a group before being able to use this function, but on my pod even though I've added users it still doesn't recognize the username when I type it.
Also very Strangely it behaves differently when I use the mobile version on my iPhone, I could write a message and send it to a user and it would say it was sent successfully but the user would not receive it.
Is there anything I'm missing?
Thank you.

**Comment by svbergerem** [comment]
> If I understand well you need to add someone to a group before being able to use this function, but on my pod even though I've added users it still doesn't recognize the username when I type it.

You can only start a conversation with mutual contacts, so they also have to follow you. That's at least how it should work. The user suggestions will only include mutual contacts but in theory you are still able to send a message to someone who isn't following you. That's a bug which already has been reported in #7002.

> Also very Strangely it behaves differently when I use the mobile version on my iPhone, I could write a message and send it to a user and it would say it was sent successfully

That should have been fixed by #7001 which has been released in 0.6.0.0. Which version is your pod running?

**Comment by svbergerem** [comment]
There was no answer for more than 4 months, so I'll close this issue.
