### ISSUE TITLE
Non-federated mode

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#7216]
We're often asked if diaspora can work in a non-federated mode, for instance to build local entreprise SN. I think having the support from compagnies could help us a lot. Can this easily be done?

**Comment by denschub** [comment]
We've had multiple discussions about this in the past on both GitHub and Loomio. It does not matter if it's easily possible or not. diaspora\* is designed as a federation social network and that's the main use case.

If we'd allow pods to turn off federation, we'd have a very weird state where some pods can federate and some pods don't. We thus needed to indicate that somehow visible to all users and "choose a diaspora\* pod" would be an even harder task since people need to look out for closed down pods.

All requests I have seen about this were followed by questions about "do you support file sharing?", "do you support groups?" and other feature requests. While me might get such features in the future, diaspora\* most certainly will never be a suitable network for companies at all. Just have a look at how actual business networks like Yammer are implemented and you'll understand that our needs and their needs are sometimes the exact opposite.

If someone feels strong, they could fork our code and remove the federation elements. That'd also require them to change the name and everything would be fine, but I highly doubt this will happen, since, as said, a lot of stuff is missing. Also, don't take people for granted if they say "if you support a non-federated environment, we would implement X and Y" since usually, this never happens. #1762 is a good example for that. If they'd really think about putting development efforts into diaspora\*, they could easily remove the federation bits.

Closing this as this text pretty much sums up every discussion on Loomio ever. If we receive a loomio proposal with a different outcome, we could reopen.
