### ISSUE TITLE
Serve security headers

### ISSUE THREAD

**Issue by strugee** [diaspora/diaspora#7293]
There are a couple security-related headers that diaspora* should be serving:

 - [ ] [Content Security Policy](https://content-security-policy.com/)
 - [ ] [X-XSS-Protection](https://helmetjs.github.io/docs/xss-filter/) (note that this one should be disabled in older IE versions because it causes even worse problems there)
 - [ ] [X-Content-Type-Options](https://stackoverflow.com/q/18337630/1198896)
 - [ ] [X-Download-Options](https://helmetjs.github.io/docs/ienoopen/) (mentioning for completeness; probably not needed)

These are mostly nice for a defense-in-depth approach.

**Comment by denschub** [comment]
![](https://media.giphy.com/media/E7iIfUlWHBmh2/giphy.gif)

> Content Security Policy

Already available [at the podmins discretion](https://github.com/diaspora/diaspora/blob/a025a23c71bd1649af57fd5cb44c5d5abf77c0d6/config/diaspora.yml.example#L563-L572).

> X-XSS-Protection

Already always set to `1; mode=block`.

> X-Content-Type-Options

Already always set to `nosniff`.

> X-Download-Options

Already always set to `noopen`.

---

What's this? An issue that you copy and paste to every project that seems appropriate? 😒

**Comment by strugee** [comment]
Ugh! So sorry. I definitely checked my own pod and didn't find these served... :/

I'm terribly embarrassed. 

> What's this? An issue that you copy and paste to every project that seems appropriate?

Really? No. Of course not.

**Comment by strugee** [comment]
Though CSP should really be on by default...

**Comment by denschub** [comment]
We serve most of those headers for multiple years now?! Either you haven't updated in quite a while, or your reverse proxy strips out the headers. In any way, this is something you should fix. ;)

> CSP should really be on by default...

Nah, not really. First of all, we added CSP support in a minor version. We might think about switching the default in the next major, but we're not sure if this is going to happen since it may cause issues with embedded third-party resources (what a surprise).

**Comment by denschub** [comment]
Also, just checked `pod.strugee.net` and realized you're running the pod via Phusion Passenger. Note that this is nothing we support. In fact, we highly discourage doing so for a wide range of reasons (like, for example, we can't control all headers!)

**Comment by strugee** [comment]
Yeah, I don't know. I'm _sure_ I didn't see these when I looked before I filed this, but I can't reproduce anymore. It was an honest mistake. \*sigh*

Thanks for your time. I sent email to security@ too, mentioning that X-Frame-Options was missing (which it seems it isn't). So just ignore that :/

Re: Phusion Passenger, yeah, I know. I mostly use it because it's just easier operationally... been meaning to fix that for a while.

**Comment by strugee** [comment]
> We might think about switching the default in the next major

This is what I was referring to. At the very least it should be enabled in the example file; will PR that in just a second. Just FYI shipping a security feature that's disabled often isn't enough... people often don't enable things like that because it already "works" with them disabled.

**Comment by denschub** [comment]
> It was an honest mistake.

No worries. Happens to the best of us, but it was a good opportunity to post some GIFs. :p 

> I mostly use it because it's just easier operationally

I really hope you are aware of the caveats and you run a Sidekiq instance yourself. Otherwise your pod surely feels very lonely. Anyway, this is not a support forum, I hope your setup works fine, but this is nothing we can and should discuss on GitHub.

**Comment by strugee** [comment]
@denschub yeah, I run Sidekiq normally. It's only the web process that's through Passenger :)
