### ISSUE TITLE
a page dedicated to sharing new content

### ISSUE THREAD

**Issue by dvs1** [diaspora/diaspora#7312]
I'd like to be able to bookmark a page that is simply for sharing new content.
This would seemingly increase efficiency by eliminating unnecessary serving and loading of old posts.

**Comment by denschub** [comment]
Check the left sidebar under "Bookmarklet", or have a look at https://share.diasporafoundation.org/.

**Comment by dvs1** [comment]
Thank you!
The link found under Bookmarklet seems like what I was imagining. 
Maybe it could be made more prominent somehow.

I noticed there is pre-existing content inserted.

`### diaspora*`
`https://diasp.org/stream`

Is it be possible to define what is inserted?

**Comment by denschub** [comment]
> Is it possible to define what is inserted?

You're free to change it in the editor...

**Comment by dvs1** [comment]
Do you imagine the inserted content being desired more often than not?
I would rather it be removed than needing to remove it myself every time.
Alternatively, I would like to be able to define the inserted content.

**Comment by SuperTux88** [comment]
When you click on the bookmarklet in your bookmarks, it takes the title and url from the current page. If you click on the bookmarklet in your sidebar, then it also takes the title and url from your current page (your pod), which doesn't make much sense. That's why you should drag the bookmarklet to your bookmarks and not click on it (like it is described there ...)
