### ISSUE TITLE
DST double hour is not displayed correctly in several places where the localTime Handlebar helper is used

### ISSUE THREAD

**Issue by spixi** [diaspora/diaspora#7378]
Given there are two status messages with the time stamps '2015-10-25T02:00+01:00' and '2015-10-25T02:00+02:00', respectively. Set your local time zone to  Europe/Berlin and restart your web browser. Hover your mouse over the dates. For both status messages, the local time '25.10.2015, 02:00:00' is shown in the balloon.

The localTime Handlebar helper in `app/assets/javascripts/app/helpers/handlebars-helpers.js` uses the ECMAScript method `Date.prototype.toLocalString()` which does not explicitly state how to handle the double hour which happens when the time changes from summer to winter time. It only tells, that the returned Strings are *implementation-dependent, but are intended to  represent  the  Date  in  the  current  time  zone  in  a  convenient,  human-readable  form that  corresponds to  the conventions of the host environment’s current locale*

Tests with node.js 4.6.1 and Firefox 45.7.0 (compiled with Spidermonkey 1.8.5) show that there is no specific display for the double hour. This may be confusing for the user.

There should be a suffix to distinguish between 02:00:00 UTC+01 and 02:00:00 UTC+02. The times should be shown as  '25.10.2015, 02:00:00A' and '25.10.2015, 02:00:00B' to make clear which time is meant. The suffix must only be displayed, when a local date is ambiguous. Please note that the DST change dates may differ between various time zones.

**Comment by netinetwalker** [comment]
DATE/TIME is complicated... but ...
![who cares?](http://i3.cpcache.com/product/141715665/who_cares_wall_clock.jpg?width=750&height=750&Filters=%5b%7b%22name%22%3a%22background%22%2c%22value%22%3a%22F2F2F2%22%2c%22sequence%22%3a2%7d%5d)

CLOCK SHOP: http://www.cafepress.com/+who_cares_wall_clock,141715665

**Comment by spixi** [comment]
This issue is not trivial, because it statistically affects 1 out of 8760 status messages.

**Comment by denschub** [comment]
This, frankly, is nothing we care about. At least I do not care. Your "this is confusing" argument feels weird, since literally dash clock shows the same our multiple times, or sometimes it even freezes solid for an hour. If you feel like this is something that `Date.prototype.toLocalString` should take care of, raise an issue in the TC39. As for diaspora, I am fairly certain we will not write our own `toLocalString` implementation since times and dates are a pain. Since we do not guarantee any timeliness when distributing posts, this is semi irrelevant anyway.

Someone else with write access is free to reopen this issue if they feel a strong opinion to add edge-edge-case handling that probably no one cares about.

Also, when we're on being a wise ass, your statistics are wrong. You assume that two posts are posted every hour, which on average might be true, but the distribution throughout the day is not even close to linear and during nighttime, the average of posts made by users in timezones that would care is negligible. That's probably one reason why they decided to do the DST swap at 2am.

Also, @netinetwalker, I have deleted your comment. It's neither appropriate nor on-topic. I frankly don't care if you are a friend of mine or not, such comments are out of place and undesirable. If you do not have anything to say about the issue in question, please do not post comments.

**Comment by spixi** [comment]
Ok, @denschub I conclude your statement. You are certain, that *we* will not write our own `toLocalString` implementation. So you think you are the whole community. In fact do 1 of 4380 status messages (0.22 ‰) is not an edge case at all. Moreover false time interpretation may also cause legal issues, e. g. think about a contest with a fixed deadline or with a prize for the first person who can proof somethin. How do you find out which post was in time or the first one without having access to the database - sure, you can participate in the federation to receive the UTC timestamps, but the minority of users does so.

The DST swap for most European timezones happens ad 2am, but this does not mean. Sure, diaspora*'s current userbase mainly consists of users from Western Europe, especially Germany, but this does not mean, that this state will stay forever. diaspora* is an open community and thus it is spreading whole over the world in an ever-faster pace. Even when your argument may be plausible at the moment, it will be invalid faster than expected.

I appreciate that you try to play the White Knight by deleting probably inappropriate, but well meant content, but this does neither mean that you have more to say than other people, nor that you are the only decision maker here. Just stop trying to blow yourself like a turkey. In my years of experience as developer and first-time quality manager, I have encountered several types of issues and methods to work around of them.

The current implementation for example simple does not allow the user to set his own date format. So when you are in an Internet café in India, for example, you see the Indian time. This may be a bug or a feature. See this issue as a chance: It would be much better, when the user is free to decide their date/time format in the user settings, this would make it easier, as the settings are shared with all their devices and even available from far away. Maybe there are people who want to see the Islamic date instead of the Gregorian - with user-defined settings this is no problem anymore!

So please don't be so harsh and wait for more comments before you close issues. Even if this was meant well, you don't make love with people with such a behaviour. Thinking before clicking would make everything much easier.

**Comment by svbergerem** [comment]
@spixi 
> The times should be shown as '25.10.2015, 02:00:00A' and '25.10.2015, 02:00:00B' to make clear which time is meant.

This could be even more confusing for some users.

> Moreover false time interpretation may also cause legal issues, e. g. think about a contest with a fixed deadline or with a prize for the first person who can proof somethin.

Using a decentralized social network like diaspora for contests with a fixed deadline may cause legal issues. ;) You can just set the `created_at` attribute yourself on your own pod, so that's nothing i would rely on. As a user you can also look at the JSON of the post/comment, so you don't have to have access to the database. But, as i wrote before, you can't really trust timestamps anyways.

> I appreciate that you try to play the White Knight by deleting probably inappropriate, but well meant content, but this does neither mean that you have more to say than other people, nor that you are the only decision maker here.

I agree that the comment was inappropriate and I would have also deleted it.

> It would be much better, when the user is free to decide their date/time format in the user settings, this would make it easier, as the settings are shared with all their devices and even available from far away. Maybe there are people who want to see the Islamic date instead of the Gregorian - with user-defined settings this is no problem anymore!

Why would you set the date/time format for every website when you can just set it for all at once in your browser?

For the record: I would have also closed this issue since using the browser's defaults sounds to me like the sanest solution.

**Comment by spixi** [comment]
What a look that denschub is also a Mozilla webcompat developer. Since this may be considered as a web standards compliance issue, may I feel free to submit an issue at webcompat, @denschub?

**Comment by svbergerem** [comment]
@spixi This is the diaspora repository and I don't care what you do in some other repository. It looks like you are mixing personal issues with professional ones. Please stop doing that.

**Comment by SuperTux88** [comment]
> So you think you are the whole community.

I just wanted to say that I completely agree with @denschub and @svbergerem here. I also gave both comments a thumbs up, so I don't need to repeat everything here ;) Just wanted to make clear that it isn't only one person deciding for "the whole community" (he also wrote that we can reopen it, if we disagree).
