### ISSUE TITLE
Always show comment input field

### ISSUE THREAD

**Issue by mlamberti** [diaspora/diaspora#7388]
Users of my pod have problems finding the comment section as long as there is no comment yet.

When a comment exist, the user's own profile picture with a "Comment" input field appears beneath the comment section, while when there is no comment nothing is shown at all. To comment one needs to explicitly click on the "Comment" link. This is inconsistent and not intuitive. The comment input field should always be shown.

The issue applies to the mobile version as well. There the comment section is always shrinked, which is okay to save space. When comments exist one can click on "2 comments" to expand the comment section and write an own comment, while when there is none one has to find and click the comment icon. On my pod users tend to confuse this icon with the "New post" icon and write posts instead of comments. Here a click on "0 comments" should also open the comment section with an input field.

**Comment by SuperTux88** [comment]
While on mobile it doesn't hurt to make "0 comments" clickable (so I think we can add this), I don't think we should make the comment field always visible on the desktop-version (to save space), and it is consistent with "like" and "reshare".

Maybe we should change the "like", "comment" and "reshare" in the desktop version, to make it better visible, maybe also add the icons there?

**Comment by mlamberti** [comment]
> Maybe we should change the "like", "comment" and "reshare" in the desktop version, to make it better visible, maybe also add the icons there?

To be honest I don't like those icons. They just look like indicators for the counters, but it does not look like there is an action connected with them. They do not invite to click them.

> While on mobile it doesn't hurt to make "0 comments" clickable (so I think we can add this), I don't think we should make the comment field always visible on the desktop-version (to save space), and it is consistent with "like" and "reshare".

I actually measured the pixel sizes of the comment section now, together with some worst-case minimal size post examples, see the attachment.
![diaspora](https://cloud.githubusercontent.com/assets/10745701/24293450/1bed866c-1092-11e7-88f0-d98df4bed79e.png)

So in worst case it would increase a post's size by 50%. Sounds a lot, but I guess most posts aren't one liners, but contain either a long text or images. Also it only applies to posts which aren't commented yet - because once there is a comment the input field is shown.

If I write something on diaspora my intention is not to keep a diary, but to get feedback. Thus I want comments. Thus the amount of comment-less posts should be near 0. If showing the comment input field decreases the hurdle for the first commenter that's also a good thing and actually worth the space. Also on desktop version it is quiet easy to scroll.

So if we really want to save that space - disable comment input field always.
If we want people to comment easily - enable comment input field always.

Current state is just inconsistent and especially for new users a problem.

**Comment by goobertron** [comment]
> I don't think we should make the comment field always visible on the desktop-version (to save space), and it is consistent with "like" and "reshare".

I agree. I really hate open comments boxes when not focused. I wouldn't want to see it added to Diaspora.

> Maybe we should change the "like", "comment" and "reshare" in the desktop version, to make it better visible, maybe also add the icons there?

That's certainly a possible option.

**Comment by denschub** [comment]
I also do not see a reason why we should add the comment box all the time. I am actually not concerned about the height, but look at this comparison:

![screen-shot-2017-03-25-at-04 05 36](https://cloud.githubusercontent.com/assets/344777/24319008/b31013c4-1110-11e7-8cda-00c6feeeb08d.png)

I am neither bugged by the fact that we get less information in screen nor that we have increased the height, but the addition of my avatar over and over again creates a lot of visual noise. I actually tend to look at my own avatar just to read the comments, while no comments are there.

> especially for new users a problem

I've never seen any complaints or questions about this. What is you assumption based on? I don't distrust you saying you got these feedback, I just wonder if there is another issue. It's pretty clear that the actions below a post are indeed actions (they are in the same color as every other link) and if users are not able to find the comment section, they're also not able to find the like and reshare links, which makes me wonder why that is. In fact, if there is an issue with the way we present actions, adding the comment section permanently would make this issue even worse, since it completely takes the attention away from the links.

However, I do agree that we should make "0 comments" clickable on mobile, but that's another issue, so let's not mix those.

**Comment by mlamberti** [comment]
Thanks for your feedback, I actually didn't expect it would need a discussion :)

> the addition of my avatar over and over again creates a lot of visual noise.

I absolutly agree on that, plus when facebook first introduced the open comment box years ago, it bothered me a lot, because I always thought I accidentally wrote a comment.

But one thing your example leaves out: diaspora shows the comment box, as soon as there is at least one comment. How much uncommented posts appear in your stream? Because we are only talking about adding extra height/noise to those posts, the others already have it. Is it 5%, 25%, or way more?

> It's pretty clear that the actions below a post are indeed actions.
It is. What I said regarding icons looking like counters only affects mobile version.

>  What is you assumption based on?
> I just wonder if there is another issue.
Probably there is, as the persons I talked to (non tech affine family members) mainly use the mobile version. To not mix this further up I'll create a new ticket.

**Comment by mlamberti** [comment]
So to say it in other words again, on my pod users have problems commenting posts when there is no comment already. What happens is probably following:

They use **mobile version**, read the post, read the comments and use the already shown input field to write their own comment. All fine.
But when there is no comment, they create a new post instead.

This lead me to create this issue to always show the input field.

**Comment by SuperTux88** [comment]
> How much uncommented posts appear in your stream? Because we are only talking about adding extra height/noise to those posts, the others already have it. Is it 5%, 25%, or way more?

That totally depends on your contacts and what they post, and how active their contacts comment on their posts. But new posts always have no comments (so top of the stream). Just for the record, right now my first page of stream (first 15 Posts), have 4 Posts with comments, and 11 with no comments, so it is 73% uncommented posts. On the second page, there is only one post with comments (again, out of 15), so 93% uncommented posts. So yes, it would add a log of additional noise and waste use space.

Maybe we should change the way we display posts with comments, but I think it's ok how it is now, because it is more likely to answer to a post that already has comments. From the 5 commented posts from my first 30 posts in my stream, there is one post with 6 comments, one with 5, 2 with 2 and only one post that has only one comment yet. Again, that depends on your contacts and how their contacts write comments. And when there already are comments, the additional noise is less.

> They use **mobile version**

But then we shouldn't change the desktop version, we should improve the mobile version, so as you suggested (and everybody agreed), making the "0 comments" clickable.

**Comment by denschub** [comment]
> Because we are only talking about adding extra height/noise to those posts, the others already have it. Is it 5%, 25%, or way more?

No idea, let's see!

```
irb(main):001:0> posts = Post.count
=> 4818336
irb(main):002:0> posts_with_comments = Comment.distinct.pluck(:commentable_id).count
=> 750875
irb(main):003:0> (posts_with_comments.to_f/posts.to_f*100).round(2)
=> 15.58
```

Which means only approx. 16% of all posts in the Geraspora database have comments. Note that I am not counting local posts here but also all posts that have been federated in, so this number should be fairly representative across the network. Obviously this is not the best metrics ever since we should filter out some sources of noise, but a quick survey over my personal stream gives me rougly 35%, so the majority of posts still do not have comments.

I agree that the mobile UX is bad here, and I'd not discuss on linking the "0 comments" there as I agree that this is pretty confusing. Still feels wrong to touch the desktop version here, though.

**Comment by denschub** [comment]
Gnah, @SuperTux88 was a bit faster. However, I have the cooler numbers. 😛

**Comment by denschub** [comment]
So let's close this in favor of #7393 since there seems to be agreement that the action links in the desktop versions are good enough and we have a tracking issue for the mobile changes.

**Comment by mlamberti** [comment]
Thanks for the numbers. They are quiet enlightening and I fully agree on closing this issue.
