### ISSUE TITLE
Use postgresql parallel query 

### ISSUE THREAD

**Issue by tursiops33** [diaspora/diaspora#7434]
Hi I just saw the following article about postgresql parallel query and though to myself if diaspora used that kind of queries. If not it would an idea to develop. Thanks. All the details can be found here. https://www.postgresql.org/docs/current/static/parallel-query.html

**Comment by denschub** [comment]
?! It's not like it is a magic flag diaspora could turn on and then magic unicorns appear inside the database and do the work in a magical fancy way. ;)

If there are free background workers available (which is a postgres setting that's out of our control) and if the database is able to satisfy the requests with multiple workers, it will do that without us doing anything. There's a pretty clear explanation of requirements at https://www.postgresql.org/docs/current/static/when-can-parallel-query-be-used.html ...

Given the fact I was able to experience performance boosts with the 9.6 upgrade (which is where parallel queries were introduced) and other were as well, some of the database requests are friendly.

Sadly, we can't just write everything optimized for postgres since we have to support MySQL as well. In addition, we have people who are interested in optimizing all database IO in general and they are eventually going to do so. Since there is no clear action item out of this issue, I'll close it.
