### ISSUE TITLE
moar notifications without reloading

### ISSUE THREAD

**Issue by DeusFigendi** [diaspora/diaspora#7460]
Well, I don't know if this idea makes to much i/o but I present it anyway, it might be closed if it's a bad one :-D

Since a few weeks desktop diaspora i pulling notification on a time based interval like every 300 seconds and it's notifying my operating system. This is totally awesome! :+1: 

I just wanted to suggest… maybe every request you do anyway as liking something, pulling the comments, sending a comment, adding a contact to an aspect, resharing, uploading an image, pulling more posts in the stream-view etc. etc. like "everything" with an JSON-answer **could** contain information about notification **additional** to it's usual content/result.

This way if I actively using diaspora at the moment the server would check more often if I got new notifications and if I don't use it active it just pulls over the time (maybe this could even be reduced). As an user I would get the information faster without clicking the notification-icon.

I don't know if it's a better way to inform only **that** there are new notifications or even its content (so… who commented what etc.).

And as I said I have no idea if this makes a lot of i/o database request that take sooo much CPU time and take waaaaaaay to long to answer a simple "jep, you liked" or if this is a neat idea and easy to do drive by. Maybe it's easy at some of those mentioned requests (like querying more posts) but hard on others (like uploading an image). I have no correct idea about diasporas database model (well yes, @CSammy told me a little last summer ^^). So I guess this one `needs discourse`

**Comment by SuperTux88** [comment]
This isn't a problem about db-load, but we would need to add the notification logic to every controller in the backend, and we would also need to filter and handle included notifications everywhere in javascript. It would be mutch easier to just trigger a second request on every click or just increase the interval based on how active someone is using diaspora.

**Comment by DeusFigendi** [comment]
>  or just increase the interval based on how active someone is using diaspora.

Well maybe… or just not, I just thought it would be kinda effective. But maybe I was wrong :3

**Comment by denschub** [comment]
Am I understanding you correctly that every XHR response should contain additional payloads like the current notifications?

If so, no, that does not make sense. Not only does it completely break the separation of concerns  in our controllers (since every controller would need to load notifications or we would invent some kind of magic that builds the actual response JSON outside of the controller), it also makes our frontend code much more complicated, since we would parse possible notifications from every response ever made. Given the fact that the notification request is very cheap, there is no point in adding that complexity in the first place.

Given that there are two vetos against this idea, I'm going to close this. If you feel strong, please start a discussion on Discourse.

(Also, if you knew it would need a discussion in Discourse anyway, why didn't you start there?)
