### ISSUE TITLE
Unicode Emoji Support fails

### ISSUE THREAD

**Issue by kannanvm** [diaspora/diaspora#7475]
while posting "😊" in diaspora
![screenshot-2017-06-25_13 44 59](https://user-images.githubusercontent.com/24734920/27514817-a104102e-5984-11e7-86c2-80ece41a65d7.png)

while commenting "😊" in diaspora
![screenshot-2017-06-25_14 31 20](https://user-images.githubusercontent.com/24734920/27514844-10d81c10-5985-11e7-8555-6734b54de596.png)

some of the unicode emojis arent working while posting and commenting. **not all**, "❤️" works.

current diaspora **version 0.6.6.0**

**Comment by goobertron** [comment]
That's intentional, because no emoji character set has been identified which fits in with Diaspora's UI.

See #4560, [Add smileys support?](https://discourse.diasporafoundation.org/t/add-smileys-support/391) and [Emoji support](https://discourse.diasporafoundation.org/t/emoji-support/445/156) for previous/existing discussions of this.

**Comment by denschub** [comment]
This works perfectly fine in normal environments. Which pod are you on? Is it your own? If so, what MySQL version do you run and what's the output of `SHOW FULL COLUMNS FROM posts;`?

**Comment by SuperTux88** [comment]
Yes, that was fixed over 2 years ago with #5530 in 0.5.0.0. If your pod still have this problem, your podmin either didn't run this migration or if the pod was setup later than 0.5.0.0, the installation was done incorrectly. So please contact your podmin to fix that problem.

**Comment by tclaus** [comment]
So this can be closed?
