### ISSUE TITLE
Posts not available as XML anymore

### ISSUE THREAD

**Issue by Bonsaiheldin** [diaspora/diaspora#7492]
Hello! 👋

I noticed that Diaspora doesn't seem to deliver XML files for posts anymore. JSON still works though. Is XML deactivated? I used the XML files to easily get the GUID of posts as i find it easier to read than JSON. 🤔

https://nerdpol.ch/posts/3784958
https://nerdpol.ch/posts/3784150
https://nerdpol.ch/posts/3784277

https://nerdpol.ch/posts/3784958.xml
https://nerdpol.ch/posts/3784150.xml
https://nerdpol.ch/posts/3784277.xml

Regards

**Comment by SuperTux88** [comment]
This was never an official feature, it was only an internal route that was needed by very old pods and was deprecated now since over a year and removed since yesterday. If you want the GUID of a post, you can just click the timestamp on single-post-view or the permalink icon in the stream:

![](https://cloud.githubusercontent.com/assets/10187586/26047044/4cfecb12-395a-11e7-8a18-f282d8094e09.png)
![](https://cloud.githubusercontent.com/assets/10187586/26047043/4cdf03d6-395a-11e7-94bb-81d24adf8570.png)

**Comment by Bonsaiheldin** [comment]
Funny, i never saw that link. Thanks! 😅

For anyone reading this: There is no visible permalink in the single view: You can still get the GUID by clicking on the timestamp - it links to the same post, using it.
