### ISSUE TITLE
The Translation: String "you are mentioned in a comment" in /user/edit is not Translatable

### ISSUE THREAD

**Issue by paskalito** [diaspora/diaspora#7559]
At least i can't find it on webstranslateit

and its not translated in german, and french as well.

**Comment by pskosinski** [comment]
I think the string you mention is `users.edit.mentioned_in_comment`. Type it into the "Search for a segment" field. It was translated to French and German but not proofread and I suppose that's why it didn't get into release. They were translated 8 months ago and not changed since, so probably just need accepting by a proofreader.

**Comment by SuperTux88** [comment]
@paskalito As @pskosinski already wrote: The string is there and it's translated in the 0.7 release (we pull all translated strings, so it doesn't need to be proofread). On which pod did you see that it isn't translated? Was that pod still on the frozen pre-release? The new translations were pulled 3 hours before the release and so they weren't there in the pre-release.

**Comment by denschub** [comment]
No feedback received. This string is translateable so this feels like an invalid issue. Wen can reopen if there is actually something wrong...
