### ISSUE TITLE
Only mark notification as 'read' if post viewed in SPV

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#7574]
I find (and I think this is fairly new) that notifications are often marked as read when the stream is loaded with the page, or when I scroll down and another section of stream is loaded. This means that they get marked as read without me looking at the post to which they belong.

I think notifications should be marked as read only when either I have loaded the post in the SPV or manually mark them as read.

**Comment by SuperTux88** [comment]
> I think notifications should be marked as read only when either I have loaded the post in the SPV or manually mark them as read.

That's already the case:

https://github.com/diaspora/diaspora/blob/ce5e42c471a1633069df110fa4907306ad237f55/app/controllers/posts_controller.rb#L21

This is only called from the SPV, the stream goes a completely different way to load the posts and there is no notification logic there.

Can you reproduce the behavior you describe? Mark a notification as unread and then scroll through the stream?

**Comment by goobertron** [comment]
Yes, just did it.

A slight correction to what I wrote above: you have to click the notification icon to open the drop-down when the relevant post is loaded in the stream, and the notification(s) will be instantly marked as read.

I just tested it with two separate notifications for two separate posts, and both were marked as read as soon as I opened the notification drop-down.

pod.orkz.net, if you don't think this is a code issue.

**Comment by svbergerem** [comment]
I'm unable to reproduce that. I have an unread “also commented on” notification, scrolled down until the post was visible, opened the notification dropdown and the notification is still unread. If I open the post in the background and then open the notification dropdown from the stream, then the notification is of course marked as read, since the notifications in the dropdown are updated as well.

**Comment by goobertron** [comment]
Hmm, not sure what to say. It's happening here consistently, and only in the last few days. Although I can't say with 100% certainty, I'm pretty sure that it's since the pod updated to 0.7.0.0.

If you are both working on development environments, could it be that this has been fixed by a more recent code change? Have you tried it on a production pod running 0.7.0.0 stable?

**Comment by svbergerem** [comment]
My pod only includes #7530 and some minor style changes.

**Comment by goobertron** [comment]
OK, let's see if anyone else can reproduce this. Thanks to you both for your input.

**Comment by Flaburgan** [comment]
@goobertron could you possibly do a screen video with `recordmydesktop` for example to demonstrate?

**Comment by SuperTux88** [comment]
Same as @svbergerem, I can't reproduce this. I tested this with the 0.7.0.0 release (no additional changes, and I made a video: https://www.youtube.com/watch?v=Zlkdp5hqyIA

I created the top 3 notifications, the 4 posts at the top are interesting, the most top is a reshare of my post, the other 3 are the posts with the notifications. As you see all 3 are visible and I reload the page at the beginning, so loading the stream doesn't mark them as read. The I open post 1 and 3 in a tab, and after each the notification is marked as read (as expected when opening the SPV). The I reload the page again, the notification for post 2 is still unread, when I open that in a tab too, it's marked as read, as expected.

The notification dropdown refreshes when you open it, so when you opened some posts in SPV since you opened the dropdown the last time, it updates and it marks them as read, that's maybe what confuses you, because it looks like they are marked as read when you open the dropdown, but they are marked as read by opening the post in SPV before opening the dropdown.

**Comment by Waithamai** [comment]
I tried on pods running 0.6.6.0, 0.6.7.0, 0.7.0.0, and dev, and I can't reproduce it on any of them. So I also tested on pod.orkz.net - and I still failed to reproduce.

**Comment by goobertron** [comment]
Well, it just happened again when @SuperTux88 liked my ['arf' post](https://pod.orkz.net/posts/7f5f81206a820135025600163e5dbca2)...

**Comment by SuperTux88** [comment]
And you didn't open the post in SPV?

**Comment by goobertron** [comment]
> And you didn't open the post in SPV?

Nope. I've just taken a video, to prove what I was saying. However I also did some more digging around in add-ons, and ... [it's always embarrassing when this happens] ... it was the '[add podsavelink](https://github.com/DeusFigendi/Userscripts/raw/master/Diaspora/Add_podsavelink.user.js)' extension which was causing this. With this extension disabled, everything works fine. Enable it again, and the problem occurs once more.

Sorry for wasting all of your time. Beers all round!

**Comment by svbergerem** [comment]
@DeusFigendi You might be interested in this, since it's your userscript.

**Comment by DeusFigendi** [comment]
Yes, I see the trouble here, the script gets the guid by asking the server for the json of every posting. Probably this is recognized as "opened in SPV".

I don't know if I could do this other way I think the needed information is in the permalink these adays. So there is no need for the script and/or I can edit it so it doesn't need any requests anymore (because it can get the guid from the permalink).
