### ISSUE TITLE
I can log in on desktop but not with android mobile diaspora APP.  WTH?

### ISSUE THREAD

**Issue by stacyn** [diaspora/diaspora#7604]
I can log in just fine on my desktop.  

I've been trying for hours to log in on my anrdoid mobile tablet, via the diaspora app from the google play store, and all I get is the red banner saying "invalid username or password."  

And yes I've looked over my username a million times to make sure I'm not misspelling it.  I don't have special characters in it.   I have also looked over my password which is very simple.  

I've tried logging in with my username AND with my full diaspora ID.  It just doesn't work on mobile.  

Help.  I wouldn't go to the trouble of submitting this if I hadn't tried every intuitive angle.  How do we expect people to use diaspora if it's this difficult to merely log IN on mobile while using the diaspora app (which most people will use). 

I'm using the diaspora app I got from the google play store.  I can only log in on mobile if I use a browser on my tablet.

**Comment by SuperTux88** [comment]
Are you sure you login to the correct server?

> AND with my full diaspora ID.

full diaspora ID doesn't work, please use only the username.

**Comment by SuperTux88** [comment]
And you just changed the title, so you use the App? Can you please try with the browser? All currently existing apps are unofficial and third-party. If it's a problem with the app please create an issue for the app.

**Comment by stacyn** [comment]
The app is unofficial?  It sure looks official and had 4 stars if I recall.  Isn't the whole point of the diaspora project that most is unofficial?

I edited the original post when I realized I could log in via browser on my mobile. 

Is there an app for diaspora that actually works?

**Comment by SuperTux88** [comment]
With "unofficial" I mean that it has nothing to do with the repository here. That are completely different people developing the app not directly related with diaspora development.

Diaspora doesn't have an API yet, so the apps are basically a browser with some extras around it using some "hacks" to do things (which can break, because it's not officially supported). If it works with the browser, just use the browser. Or ask the app developers for help.

(closing this issue because it's not a problem with diaspora)
