### ISSUE TITLE
User email address format for mentioning users

### ISSUE THREAD

**Issue by AlenPelin** [diaspora/diaspora#7649]
_Apologize if this topic was raised before, search didn't help this time._

**Proposal:**  
It is possible to mention somebody using quite tricky syntax: `@{username@pod}` which is not something most people are familiar with. I propose to switch to email syntax everybody is used to: `username@pod`. 

**Pro:**  
* Email address is a standard and everybody is familiar with it
* This syntax is already in use in some parts of the system (when user doesn't have name specified, it's name is shown as `<a href="https://pod/people/userid">username@pod</a>`

**Con:**  
* There can be confusion when people want to mention email instead of account

**Comment by Flaburgan** [comment]
Hello, thank you for opening an issue to improve diaspora. The mention syntax is not aimed to be entered directly by the user. Instead he is supposed to enter @ and the beginning of the username and then use the autocompletion to choose the mentionned user. Especially, the autocompletion works for both the displayed user name (most known by the users) and the diaspora ID when the formal syntax only works with the ID.

**Comment by AlenPelin** [comment]
@Flaburgan thanks for your prompt reply.

It indeed makes sense, but please consider it is as a secondary function as may be useful for mobile or alternative clients, integrations with other networks, etc.

**Comment by AlenPelin** [comment]
And another minor reason is the format looks kinda weird, even though it is populated automatically - it is stored in the text field "as is", not replaced by FirstName LastName as in facebook. 

![image](https://user-images.githubusercontent.com/2854666/31916955-deca8ce6-b8a0-11e7-8b25-66761efb067c.png)

![image](https://user-images.githubusercontent.com/2854666/31916976-fcd16034-b8a0-11e7-9353-a595e75c3bdc.png)

So having this variant would be quite simple compromise:

![image](https://user-images.githubusercontent.com/2854666/31916999-15b393ba-b8a1-11e7-9842-e8ede7144d25.png)

**Comment by SuperTux88** [comment]
> There can be confusion when people want to mention email instead of account

That's exactly the problem. We already simplified the mention syntax to `@{username@pod.org}` in #7276, but we need the `@{}` to mark it as a mention, so we can detect and display it correctly. Only `username@domain.org` can be anything and currently it is a mail address, so it would be really weird for users when we change this to be a mention. The `@{}` syntax is supported by other project compatible with the diaspora protocol too, so it would be a problem for other projects too when we change this.

As @Flaburgan already wrote, you normally don't need to write mentions by hand, you can just use the auto-completion. And if you need to write the mention by hand, the additional `@{}` shouldn't be a big problem.

> And another minor reason is the format looks kinda weird, even though it is populated automatically - it is stored in the text field "as is", not replaced by FirstName LastName as in facebook.

First: We are not facebook. Second: When you used the auto-completion the name would be displayed when you switch to the preview. The input field isn't a wysiwyg editor, that's why the preview is there. We had that auto-replace with name once, and it was a big problem and really broken, that's why it was removed.
