### ISSUE TITLE
Feature request: Larger images

### ISSUE THREAD

**Issue by SunyataZero** [diaspora/diaspora#7664]
It would be nice to have the option to upload and see larger images

Btw thank you all for what you are doing for the freedom of the internet

Kind Regards, Tord

**Comment by DeadSuperHero** [comment]
Well, Diaspora's uploader already provides several different versions of the image after it has been uploaded and processed: https://github.com/diaspora/diaspora/blob/develop/app/uploaders/processed_image.rb

When you refer to "Having the option to upload and see larger images", what are you referring to here specifically? Would this be a user setting, or are you hoping to just have link access somewhere to the full-size image on statuses containing image attachments?

**Comment by SunyataZero** [comment]
@DeadSuperHero Hi and thank you for your answer and interest in this. As it is right now when i click on an image it covers only a fairly small part of the screen for me:

![image](https://user-images.githubusercontent.com/10245688/32923898-4d0e95b6-cb3a-11e7-94d2-62454b393713.png)

(If i right click on the photo and choose "open in new tab" it has the same size)

It would be nice if there was an option to go to full screen, even if the file is smaller than full screen this may still look good

Another thing would be to increase the max pixel size of the allowed images, but i can understand that you have limited bandwidth and the hosting costs money

A third thing is to increase the size of the image in the view that you get by clicking on it (as in the screenshot above), this could be done either by "simply" increasing the max pixel size, or by scaling up the image

Again, thank you for what you're doing, i appreciate it and i'm trying to spread the word to my friends

Kind Regards,
Tord

**Comment by Flaburgan** [comment]
As explained [here](https://github.com/diaspora/diaspora/issues/7888#issuecomment-429291214), there are two issues here: the size of the displayed images, in pixels, and the allowed size of uploaded images, in bytes.

Since https://github.com/diaspora/diaspora/pull/7734 if the uploaded image is bigger than 4MB then we try to bring it under that limit by resizing its biggest side to be 3072px max. IMO that's big enough for the raw file, we're not Flickr and if you want to share bigger images in diaspora*, you can still host them and embed them using markdown. (I guess the "needs discourse" label was there because of that problem? @denschub please confirm)

So this issue is now only about the size of the image on the screen. In my opinion, 700px (so our `scaled_full` files) is big enough for the stream (mainly to limit bandwidth consumption), but I agree that when the users click on the image (so they explicitly ask to display the image) we should show it bigger. We have the raw file, so we can do that.

I'm updating the issue title and will check the code, see if the change is hard to do.

**Comment by denschub** [comment]
> I guess the "needs discourse" label was there because of that problem? @denschub please confirm

Well, no. It was actually for the mobile part of this story.

**Comment by Flaburgan** [comment]
Oh, didn't even think about mobile version here. I propose to focus on desktop version on this issue, and open a new one for mobile if needed.

**Comment by Flaburgan** [comment]
With #7890 merged, I think this issue can be closed. If someone really to be able to access the raw image in the mobile version please let me know here and I'll reopen.
