### ISSUE TITLE
Increase number of posts in Atom feed

### ISSUE THREAD

**Issue by dest4** [diaspora/diaspora#7666]
Hi,
I parse my D* atom feed to display the contents on my personal page.
I'd like to have control on the number of posts that are displayed.

Currently, if I understand correctly, it's hardcoded at 25, according to line 75 of  diaspora/app/controllers/users_controller.rb
```
  def public
    if @user = User.find_by_username(params[:username])
      respond_to do |format|
        format.atom do
          @posts = Post.where(author_id: @user.person_id, public: true)
                       .order("created_at DESC")
                       .limit(25)
                       .map {|post| post.is_a?(Reshare) ? post.absolute_root : post }
                       .compact
        end

        format.any { redirect_to person_path(@user.person) }
      end
    else
      redirect_to stream_path, error: I18n.t("users.public.does_not_exist", username: params[:username])
    end
end
```

Would it be possible to have that 25 value customizable in diaspora.yml?
Sorry I don't do Ruby
Thanks

**Comment by dest4** [comment]
Or is it okay to directly change the value in users_controller.rb and restart D*?
What will happen at updates?

**Comment by SuperTux88** [comment]
For most podmins it doesn't make sense to increase this value (since it would only make atom feeds slower and/or increase the load on the server, because atom feeds are fetched on a regular basis), so I'm against adding a setting to the diaspora.yml (also to keep the file clearer and don't overloaded the file).

However, you can just change that value on your pod if you like. But at updates you would need to resolve conflicts yourself (basically change the value again), if there are any conflicts.
