### ISSUE TITLE
user themes

### ISSUE THREAD

**Issue by 8spinach** [diaspora/diaspora#7668]
users should be able to, whether from a menu system or in text, be able to set fonts and colors at their end for a personalized experience. currently, implementation is admin only and added themes affect the entire pod; this proposal is in addendum, with narrower scope. prior suggestions have included using browser extensions to manually update css, but this option is inaccessible to users on mobile devices and unfeasible for users visiting through multiple browsers and devices, or using shared public devices such as library or school computers. user-pointed themes should be stored with the user's data on their pod.

**Comment by denschub** [comment]
This has come up multiple times. Ultimately, we decided to build predefined color themes instead (#4297), because the amount of work that needs to go into fully flexible user themes would be too much to handle in the long term. If you disagree with this, feel free to open a discussion on Discourse, but for now, that's the way it is.
