### ISSUE TITLE
birthday notifier mailed out wrong birthdays

### ISSUE THREAD

**Issue by mbutler** [diaspora/diaspora#7687]
Received email notifications on 2017-12-31 for all my contacts that December 31 was their birthday.

**Comment by Flaburgan** [comment]
Are you sure you received an email for all your contacts? I received many notifications but definitely not all of them. On which pod are you registered btw?

**Comment by Waithamai** [comment]
works for me. i checked every single birthday notification for every single account. they were all correct (on geraspora).

**Comment by mbutler** [comment]
Received email notifications on 2017-12-31 for all my contacts that December 31 was their birthday.

**Comment by mbutler** [comment]
It was definitely all of them, but I have only a few contacts. Maybe a default birth date that never got set?

**Comment by jhass** [comment]
I guess we really shouldn't send them if we only have the year. But not sure we can currently disambiguate that from somebody that acutally has their birthday on the first

**Comment by Waithamai** [comment]
it's not possibly to only set a year as birthday. it's possible to set day+month without year, but not only the year without day and month.

**Comment by denschub** [comment]
So, this is weird. As far as I can tell, we actually *do not* have an issue, or at least, this is my current opinion.

Based on a little discussion I had with someone on twitter, I checked my database because I wanted to make sure we didn't run into an issue where we accidentally set a default birthday for a large portion of users. And we do not.

For reference, I have 146009 profiles in my DB without a birthday[1] and only 1265 profiles with birthdays at the 1st of January[2]. So I am fairly certain we do not have an issue with resetting birthdays. Since we [check for both day and month matches](https://github.com/diaspora/diaspora/blob/13d24cc6113b6ab4a59401d742b6d761eb001b87/app/workers/check_birthday.rb), I am *sure* we do not hit profiles with `birthday = NULL`.

However, there is still something *weird*. I checked for the average birthday distribution[3] and you can see pretty quickly that there is indeed a large spike at 01-01:

```
   b   | count
-------+-------
 01-01 |  1265
 01-02 |    20
 01-03 |    23
 01-04 |    22
 01-05 |    26
 01-06 |    25
 01-07 |    31
 01-08 |    19
 01-09 |    21
 01-10 |    24
 01-11 |    24
 01-12 |    21
 01-13 |    18
 01-14 |    25
 01-15 |    26
 01-16 |    21
 01-17 |    29
 ...
```

So that's weird. I wanted to check the distribution per year, and run a second query[4] and we have indeed a spike at 1970:

```
count | year
------+------
  756 | 1970
  311 | 1984
   21 | 1980
   16 | 1930
   13 | 1000
   10 | 1990
   10 | 2000
    9 | 1985
 ...
```

But that's confusing. Quite a lot of profiles have 1970 set as their year, but quite frankly, that's not *enough* to show that we have a bug. I also did not check if these profiles are diaspora profiles or federated from somewhere else, mainly because I do not have an easy way of doing so.

Still, the majority of users either have no birthday set, or an actually valid birthday. And even if they have set the birthday to `01-01`, it feels like they did it *as a joke*.

Maybe some pod had a broken database migration and a lot of `NULL`s are now 1st of January's. Maybe @Zauberstuhl can verify his numbers on JD to see if they look sane. However, as for our project, **I am very confident we do not have an issue** in both our handling of birthdays or in the implementation of the birthday mailer. Therefore, I will close this issue as invalid.

---

**1**:

Counted on the rails console, `Profile.where("birthday IS NULL").count`

**2**:

Counted on the rails console, `Profile.where("EXTRACT(DAY FROM birthday) = 1 AND EXTRACT(MONTH FROM birthday) = 1").count`

**3**:

SQL query, likely only runs on Postgres, though.

```sql
SELECT
  CONCAT(
    LPAD(CAST(EXTRACT(MONTH FROM birthday) AS text), 2, '0'),
    '-',
    LPAD(CAST(EXTRACT(DAY FROM birthday) AS text), 2, '0')
  ) as b,
  count(*)
FROM
  profiles
WHERE
  birthday IS NOT NULL
GROUP BY
  b
ORDER BY
  b;
```

**4**:

SQL query, likely only runs on Postgres, though.

```sql
SELECT
  count(*) as count,
  EXTRACT(YEAR FROM birthday) as year
FROM
  profiles
WHERE
  EXTRACT(DAY FROM birthday) = 1
  AND EXTRACT(MONTH FROM birthday) = 1
GROUP BY
  year
ORDER BY
  count DESC;
```

**Comment by Flaburgan** [comment]
Numbers on https://framasphere.org:
1: 86016
2: 215
3:
```

   b   | count 
-------+-------
 01-01 |   215
 01-02 |    21
 01-03 |    22
 01-04 |    18
 01-05 |    22
 01-06 |    30
 01-07 |    15
 01-08 |    19
 01-09 |    24
 01-10 |    32
 01-11 |    19
 01-12 |    22
 01-13 |    18
 01-14 |    24
 01-15 |    21
 01-16 |    20
 01-17 |    24
 01-18 |    20
 01-19 |    18
 01-20 |    16
 01-21 |    28
 01-22 |    16
 01-23 |    19
 01-24 |    19
 01-25 |    20
 01-26 |    14
 01-27 |    16
 01-28 |    25
 01-29 |    17
 01-30 |    22
 01-31 |    17
 02-01 |    21
 02-02 |    26
 02-03 |    27
 02-04 |    26
 02-05 |    29
 02-06 |    26
 02-07 |    26
 02-08 |    14
 02-09 |    23
 02-10 |    22
```

4:
```

 count | year 
-------+------
    41 | 1970
    14 | 1980
     8 | 1004
     8 | 1991
     8 | 1892
     7 | 1985
     7 | 1984
     7 | 1910
     6 | 1977
     6 | 1987
     6 | 1000
     5 | 1930
     5 | 1990
     5 | 1992
     5 | 2000
     4 | 1972
     4 | 1973
     4 | 1960
     4 | 1979
     4 | 1975
     3 | 1988
     3 | 1983
     3 | 1971
     3 | 1967
     3 | 1994
     3 | 1976
     3 | 1891
     2 | 1989
     2 | 1901
     2 | 1968
     2 | 1969
     2 | 1905
     2 | 1890
     2 | 1993
     2 | 1966
     1 | 1951
     1 | 1956
     1 | 1957
     1 | 1958
     1 | 1959
     1 | 1961
     1 | 1963
     1 | 1964
     1 | 1911
     1 | 1974
     1 | 1978
     1 | 1982
```

Numbers on diaspora-fr.org:
1: 64822
2: 69
3: 
```
   b   | count 
-------+-------
 01-01 |    69
 01-02 |     5
 01-03 |     2
 01-04 |     4
 01-05 |    12
 01-06 |     4
 01-07 |     6
 01-08 |    12
 01-09 |     6
 01-10 |     6
 01-11 |     8
 01-12 |     6
 01-13 |     9
 01-14 |     2
 01-15 |     9
 01-16 |     5
 01-17 |     8
 01-18 |     3
 01-19 |     7
 01-20 |    12
 01-21 |    12
 01-22 |     8
 01-23 |     7
 01-24 |     2
 01-25 |     7
 01-26 |     5
 01-27 |    10
 01-28 |     9
 01-29 |     2
 01-30 |     5
 01-31 |     4
 02-01 |     5
 02-02 |     8
 02-03 |    11
 02-04 |     7
 02-05 |     6
 02-06 |     7
 02-07 |     8
 02-08 |     6
 02-09 |     6
```

4: 
```
 count | year 
-------+------
    12 | 1970
     6 | 1980
     4 | 1930
     4 | 1000
     4 | 1984
     3 | 1004
     3 | 1910
     3 | 2000
     2 | 1960
     2 | 1991
     2 | 1972
     2 | 1985
     2 | 1977
     2 | 1996
     1 | 1892
     1 | 1981
     1 | 1967
     1 | 1950
     1 | 1990
     1 | 1976
     1 | 1896
     1 | 1956
     1 | 1997
     1 | 1989
     1 | 1911
     1 | 1983
     1 | 1982
     1 | 1890
     1 | 1992
     1 | 1975
     1 | 1971
     1 | 1978
(32 rows)
```

**Comment by denschub** [comment]
Cool. This basically confirms that we have no widespread issue with `NULL` vs. `1970-01-01`. Thanks, @Flaburgan, that is appreciated. I feel comfortable with simply ignoring this now. :)

**Comment by mbutler** [comment]
Glad to hear it's not a bug. FWIW (and this only just occurred to me), but all of my contacts joined via invite on the alpha server from the Kickstarter in 2010. I confirmed with them that they didn't manually set a birthdate. Might help explain the weirdness.

**Comment by denschub** [comment]
I pinged @Zauberstuhl earlier, who is responsible for joindiaspora.com, your contacts are on. If this turns out to be a local issue with that pod, that would be *kinda* bad, but manageable.

Let's see when Lukas responds with his numbers. Thanks for the feedback.
