### ISSUE TITLE
Automatic translation of comments

### ISSUE THREAD

**Issue by LorenzoAncora** [diaspora/diaspora#7699]
Users should be able to translate comments written in foreign languages into their own language from the GUI of Diaspora*, without the need of copy-pasting them into an external translator.

Example use cases:
- the reader uses the Italian GUI and a comment contains English text, Diaspora* should offer the option to translate the comment into Italian.
- the reader uses the English GUI and a comment contains Spanish text, Diaspora* should offer the option to translate the comment into English.

This should facilitate participation to users who want to speak only their own language or who cannot speak a lingua franca.

**Comment by denschub** [comment]
This has been discussed multiple times in the past, including [here](https://discourse.diasporafoundation.org/t/language-filter-for-diaspora-as-a-gsoc-project/321). Supporting automatic translation of contents has some privacy implications, especially since the contents have to be sent to an external service and process there. As for now, the current state of the discussions looks like this is nothing we're going to implement. In any case, this would needs brroader discussion on Discourse first.

**Comment by LorenzoAncora** [comment]
Hello, @denschub.

> This has been discussed multiple times in the past, including [here](https://discourse.diasporafoundation.org/t/language-filter-for-diaspora-as-a-gsoc-project/321).

I've already searched for this topic here on GitHub before asking, without results. That's why I've asked. :-)

> Supporting automatic translation of contents has some privacy implications, especially since the contents have to be sent to an external service and process there.

Users already copy-paste the contents of other users into on-line translators. Most browsers already implement the automatic translation: on-line services (like Google<sup>&reg;</sup> Translator or Bing/Microsoft<sup>&reg;</sup> Translator) will parse the contents of Diaspora* and will get informations like the URL and the full DOM (including text, images etc.).
You can do nothing to block these client-side features: the only good thing you can do is offer an option for automatic translation in Diaspora*, and this will increase the privacy because you'll be able to filter the contents before the submission takes place.
This can be an optional feature (for example a "click here to translate into X" link or the babel-fish icon near each post/comment), there is no need to impose the automatic translation.

> In any case, this would needs brroader discussion on Discourse first.

...also talk on IRC if you want, this is not my business. If it helps, good for you. :-)
When you'll decide to take care of the feature request, reopening this issue you just closed is advised.
Probably, after a while non-English speakers will just migrate to other social networks, because Diaspora* lacks a good UX for foreign language speakers.

Regards,
Lorenzo

**Comment by denschub** [comment]
> I've already searched for this topic here on GitHub before asking, without results. That's why I've asked. :-)

Which is why I liked to a Discourse discussion, and not a GitHub issue. We have had multiple discussions about this exact topic there in the past, including about the different privacy implications by automated/embedded translations vs. people copy'pasting content.

Discussions about controversial issues and features in this project happen on Discourse, not on GitHub, and that's the sole reason I closed this issue. Past discussions on Discourse about translation features and language filters did not create any actionable outcome, and as long as this does not change (and by that I mean that we can agree on a solution we feel like implementing), this issue, and all related, will stay closed.

> Probably, after a while non-English speakers will just migrate to other social networks, because Diaspora* lacks a good UX for foreign language speakers.

That's your opinion and that's fine. I have a different opinion, and given that there is a majority of German users who are able to use diaspora perfectly fine within certain German-only bubbles, I do not think your statement is generally true. Maybe the solution is not to offer automated translations, but to create a language filter. In my opinion, filtering content could be a preferable solution, since translating text never works as it should. There are a lot of valid concerns against automated translations, like the possibility to motivate people to leave comments in their mother tongues, which could make discussions messy.

Discussions like these are the reason we have Discourse. This has nothing to do with people "blocking these client-side features", but more with people who want to build *good* solutions, not solutions that looked good on a first glance.
