### ISSUE TITLE
Stream sometimes doesn't load when opened in background tab

### ISSUE THREAD

**Issue by SuperTux88** [diaspora/diaspora#7739]
I observed this occasionally for quite some time now (so it isn't new). When loading a user profile in a background tab (I don't know if this is only for profiles or if it also happens for other streams, tags pages), and switch to that tab later, sometimes the spinner is still spinning, but never finishes. I'm only able to reproduce it when loading in background tab (maybe because background tabs get less resources and so some race condition happens that doesn't happen when going to a profile in the same tab). When I then reload the page the stream always loads.

It sometimes takes many tries to be able to reproduce it, but when the error happens and I open the javascript error console I see the following error:

`Error: The partial status-message could not be found`

(Also while trying to reproduce it, I saw that sometimes the timago-timestamp is missing until the first timeago-update, I don't know if this ythe same issue as when the stream doesn't load at all, or if it is the same issue as #7645 (but there the timeago is in the wrong language, not missing), or if this is a completely different issue).

**Comment by cmrd-senya** [comment]
`status-message` is the only template that is used in another template (reshare) as a partial: [code link](https://github.com/diaspora/diaspora/blob/develop/app/assets/templates/reshare_tpl.jst.hbs#L24).

However partials are have to be registered, and here is the code responsible for that: [code link](https://github.com/diaspora/diaspora/blob/develop/app/assets/javascripts/app/helpers/handlebars-partials.js).

I guess that this jQuery document ready handler is just not being executed fast enough so it happens that by the time the partial got to be rendered, the handler has not been fired yet.

So it only happens when the profile page (or other pages) you open contain reshares.

**Comment by cmrd-senya** [comment]
@SuperTux88 could you please test if #7740 solves it for you?
