### ISSUE TITLE
Use our color theme for our public profile.

### ISSUE THREAD

**Issue by xSquid** [diaspora/diaspora#7756]
I set the dark theme in my account settings but it is not used for my public profile.
What do you think about using it for both public and private profiles?

NB: Dark theme is really beautiful (thanks @SuperTux88)

**Comment by Flaburgan** [comment]
What do you mean by "public profile"? The theme determines how every diaspora* pages will be rendered **to the user who set it**, it is not aimed to be a way to customize your profile page.

**Comment by goobertron** [comment]
Yup; the theme you set determines how any page you view appears to you when signed in. If someone else views your page or any of your posts, they will see it according to the theme that they have chosen. If someone views your page while not signed in, they will see it according to the default theme.

**Comment by SuperTux88** [comment]
Theoretically we could display the profile with the theme when showed to a not logged in person, but:

1. it would leak your theme setting
2. you maybe don't want that (at least I as diaspora HQ account don't want this ;) ), so we would need to add either a setting to disable this or create a different setting to chose a public profile
3. you could also use the theme for your single post views when visited without login, but that would only work when visiting the posts on your pod, not on others post, because the theme information isn't federated

So this gets really complicated really fast ... and since that's not why themes were created in the beginning (they were created to be used by the users while be logged in), I'm going to close this. If you still want to select a theme for users which aren't logged in, you can setup your own pod and select a default theme.

**Comment by xSquid** [comment]
Ok, I didn't think it was complicated.
I was asking because it's implemented on Friendica:

- https://squeet.me/profile/perig
- https://squeet.me/profile/xsquid

No matters, thanks.

**Comment by SuperTux88** [comment]
Yes, as said, it would be possible, but I think it would at least need more discussion how to implement it and where to use which theme (because there are probably people who don't like it). And I don't know if the additional complexity is worth it, because it would only be visible for people visiting your profile without being logged in and because if you **really** want it, you can "easily" do it with a personal pod (which has other advantages too) :)

And I just checked your friendica links, they only use the theme for the profile, so you switch to a different theme when you open a post from there (which could be especially annoying when you switch between dark and light theme ;) ).

**Comment by goobertron** [comment]
I think it's better that each user can choose how Diaspora pages appear to them – which is the current situation. This proposal would entail forcing an appearance on users that they might not want. I think it's better to leave this as it is.

**Comment by Fensterbank** [comment]
I think both approaches are valid.
A theme defines, how diaspora* is presented to the user using this theme. It's like a Firefox theme, where my browser looks the way I want and websites cannot influence this.

The other approach is the - let me call it - profile skin.
It's a skin I can select to present me and my identity to other people visiting my profile. It's exactly like profile theming in twitter works and therefore I understand the initial request and confusion.

But if such a profile skin is implemented, it should be done right. So the available skins have to be well known for every pod or there are possible color values for different parts of your profile page.
And of course this has to be federated alongside with the profile picture and other profile information.

I like the idea, but it should not have conflicts with the existing theming feature and it would require some work on UI and Federation. Could be discussed on Discourse.
