### ISSUE TITLE
Joining Diaspora

### ISSUE THREAD

**Issue by Progenator** [diaspora/diaspora#7765]
Hi, when going to the join Disapora page, I enter my intended user name and Password and it tells me "you have not used the required format". But nowhere does it tell me what the required format is, either for the username or for the password. I tried to send a message as feedback with having issues, but I have to be logged in first. So no go there. So I joined GitHub and found myself a workaround. Great. But that doesn't tell me whether I should really have used my real name, or a 'nickname' when registering an account. I'm here because I want to leave Facebook. I know a bit about programming and workarounds, but 90% of my friends don't have a clue about such things, and would have been put off at the outset. FB is a bit of a curse by now, along with Google, in terms of personal info abuse. Both went too far IMHO, and so there is the possibility of getting myriad people away from commercialism and into Open Source projects. Hats off to people who have made Diaspora a reality - now please think about making it easily accessible for most people who have little or no computer knowledge, and make it easy to join. SPECIFICALLY: please make it obvious what the username and password criteria are. (I still don't know myself). And please make it possible for people to ask questions when thy are not logged in (if they don't know how to do so, for example) or you risk never receiving the most valuable of feedback. Thanks, Jules

**Comment by Fensterbank** [comment]
Hello @Progenator,
registrations for new users on joindiaspora.com are currently disabled.
So you tried to register yourself with the login form, which doesn't work. :)
if you open [joindiasporas sign-up page](https://joindiaspora.com/users/sign_up) you will see an error message.

Since Diaspora* is a decentralized social network, pod administrators ("podmins") close or reopen the sign up for their pod from time to time, e.g. to encourage people to spread more on different pods or when the user count hits a high limit.

**What you can do:**
Visit [the-federation.info/diaspora](https://the-federation.info/diaspora) and search for a pod you like to use which has open signups.
For best user experience the version should be 0.7.4.0 or higher (nobody wants to be on rarely updated pods) and there should be some active users so that you see more content when following tags. But since it's a decentralized system you maybe also don't want to use the biggest pod.
But it's up to you.
Please read more about it here: https://wiki.diasporafoundation.org/Choosing_a_pod

PS: This github repository is used for discussion bugs and features in the diaspora code.
So your question is on the wrong place.
A lot of questions should be answered when you read the official wiki page and documentation on https://diasporafoundation.org/.

**Comment by denschub** [comment]
There is a large "Questions" headline [in the README](https://github.com/diaspora/diaspora#questions), which likely is the first site you have seen when accessing this GitHub repository. In addition, the front page of joindiaspora.com, on which you tried to log in, links to the project website, and has a link titled "Project discussions and support", where we offer support.

@Fensterbank told you that you cannot create an account on joindiaspora, because registrations are, in fact, disabled, so obviously, you cannot find valid credentials there. In addition, he linked you to *the official website*, which not only provides you answers about "what's going on" and "how to join etc", but also links to the place where we offer support.

I think it's fair to ask you to look at the resources someone linked you, especially when someone takes the time to write a very nice and easy to understand explanation of why you faced the issue and what you can do about it.

**Comment by Flaburgan** [comment]
That being said, it is true that it is not obvious to know that registrations are closed on a pod. Maybe there is something we can do to make that more explicit.

**Comment by Progenator** [comment]
Firstly, I haven't said anywhere that I would not look at any links - so you confuse me with your last paragraph.

 

Now, I looked at DIASPORA, not GitHub, and indeed knew of no definitive link between them - indeed the ONLY link or connection thereto is under Make A Contribution in small print - which I had no intent of doing, not even having been able to log in.

 

One would reasonably expect info needed to go about joining to be instantly accessible ON THAT WEBSITE, not on any third party website. In an age of one getting referred to scan sites one after another, I think people would be wise to wonder at being referred on - especially after visiting a page that offers joining, only for it to be found impossible and with no explanation, and apparently thus not working or perhaps having no web-background at all, for all anyone visiting for the first time knows.

 

Really, I don't care whether Diaspora succeeds or fails, because I barely even know what it is from the past few days' experience to now, so observe please that I tried to be constructive in very light criticism cum observation, with facts in supoort. 

 

Now, I took the time to point out that if, (and it seems so) people have spent  alot of time trying to make something constructive such as a social media site, then it would be good to make it easily accessible, and if not, to explain why or how to go further. Do you think my reply was for my own joy? I was and am trying to be helpful. Showing indignance, feigned or otherwise isn't doing anyone any favours - our communication was (as far as I knew) private and no one need be offended.


 

I don't know what to say - I find the situation of having a set up that seemingly cannot be accessed, -certainly not simply at least - and with no explanation offered, rather odd. Don't you?

 

regards, J


Sent: Wednesday, April 04, 2018 at 5:16 PM

**Comment by Progenator** [comment]
thanks for the reply - that sounds positive. Also a directly accessible overview and instruction set would be very helpful to the first time visitor I think.

 

regards J

 

Sent: Wednesday, April 04, 2018 at 5:38 PM

**Comment by Fensterbank** [comment]
@Progenator I know you are knew to Github, so just for your information:

> our communication was (as far as I knew) private and no one need be offended.

This is not a private communication, it's the [discussion in the issue](https://github.com/diaspora/diaspora/issues/7765) you created in our Github Project.
You got notification mails from Github about new comments in the issue. If you directly answer to these mails, your message will be added as comment to the discussion. Nothing here was private, just follow the link and open the discussion in the web view. 🙂
