### ISSUE TITLE
Block #nsfw content by age

### ISSUE THREAD

**Issue by 6543** [diaspora/diaspora#7797]
What about blocking #nsfw stuff if you set your age in you provile and it is under 18years?

**Comment by Flaburgan** [comment]
I say +1 to this, even if it can be easily bypassed, and we don't require a birth date, at least we don't break french law anymore.

**Comment by piraz** [comment]
Should we show #nsfw only if age is informed and it is under 18 years? With that we have consent from the user's action.

**Comment by 6543** [comment]
@piraz you mean is not under 18?!?

**Comment by piraz** [comment]
I mean if you not informed the data you don't get nsfw. Plus what you suggested.

**Comment by 6543** [comment]
would be a great feature!
so we dont have to wory recommend diaspora to joung people.

-> I notis that you cant block anithing by #tag wich would be is a huge improfement.
... you can block users ...
so i created a record #7799

**Comment by 6543** [comment]
@devs sory for mouch issues and at least non code :(

**Comment by 6543** [comment]
> content to users without age(birthday) informed right?
what about privacy :(
at least it should only require a year

**Comment by goobertron** [comment]
>> content to users without age(birthday) informed right?
>
> what about privacy :(
> at least it should only require the year value

As D* doesn't require any evidence of personal data (name, gender, birthday, etc.) being correct, people can enter whatever date they want. So there can't be an invasion of privacy. If someone wants to enter their real data, that's their choice, so not an invasion.

**Comment by SuperTux88** [comment]
> I mean if you not informed the data you don't get nsfw.

When somebody don't add a birth date nsfw content should still be shown, otherwise we would force users to add a date (either the correct or a fake date) which we shouldn't. Some people just don't want to add a birth date at all, and it's currently optional and it should stay optional.

**Comment by cmrd-senya** [comment]
Also putting nsfw is kinda optional too. There is no guarantees that the "improper content" in terms of law will be marked as nsfw and vice-versa, nsfw mark doesn't mean there is actually anything which is illegal to read by the underaged.

**Comment by cmrd-senya** [comment]
NSFW means "not safe for work", which is basically something you don't want to be displayed when you're at your workplace. This is not strictly matches with pornography or anything else defined illegal by a law of any country. For instance, Russia has a law forbidding so called "gay propaganda" making any LGBT mentions not allowed to be shown to people below 18. Following @Flaburgan's logic, Russian user has to put @nsfw hash tag on any post containing any LGBT information.

I think we could actually add a feature to hide contents based on age, but that can't be decided basing on nsfw tag presense for sure. Instead we could add some "hide the post for < 18 y/o people" tick.

Another problem here is that original post author can't know in what country the post will be viewed. Also we can't expect the post author to know the laws of every country where the post can be viewed. So we can't rely on the post author's personal choice here. If the post is marked by a Russian author as "illegal for <18 y/o" because the author wants to comply with the "gay propaganda" law it can still be legally shown in Ukraine or Germany, so the author's marking will result in lots of irrelevant data hidings.

So we have to collect all possible cases as a list of checkboxes, where the author could select which are relevant for the posted content.
Like
- [ ] Does your post contain nude bodies images
- [ ] Does your post contain LGBT people information
... etc, and so on...

At the same time, we can't expect people to fill the data correctly, so in order for a pod to comply with the law, you'll have to have a team of moderators who will verify the correctness of the selections in the checkboxes list.

After that, you'll have to match the following things: user's age, user's location and post contents "categories". This is enough to decide what can be shown and what can't.

Also the users without the birthdate set is the least problem. We can easily create a widget which would contain a question like "This content is restricted to the age 18+ in your location. Are you under 18?". This is how websites work when there is no way to check the age and it's considered to be enough.

So I think that it could totally be implemented and and thus we can make diaspora* to comply with the laws of as much countries as we want to, but that is a lot of work, and not only in terms of development, but also in terms of moderation.

**Comment by 6543** [comment]
@cmrd-senya i think kind a "18+" option would be nice and at least the desischon if this flag is set or not shut be a opiniin of the post-creator (perhaps optional the oportunety of moderators ...)

**Comment by cmrd-senya** [comment]
> i think kind a "18+" option would be nice and at least the desischon if this flag is set or not shut be a opiniin of the post-creator (perhaps optional the oportunety of moderators ...)

This is not enough to make us comply to laws of some countries, but this still can be a useful and desirable  feature for at least some of diaspora users.

**Comment by goobertron** [comment]
Of course 18 is only a relevant age limit in some countries....

**Comment by goobertron** [comment]
(Please would someone with admin access edit the title to change 'Contend' to 'content' (lower-case 'c', ending in 't')? It 'bugs' me (see what I did there?) every time I see it. Thanks!

**Comment by Globulle** [comment]
It is difficult to strictly comply with the law of each country, but we can think in term of *what social network we want to create*? And I think beyond freedom, decentralization and privacy, having pro-active measures to protect young people (which are vulnerable persons) from disturbing content seem very desirable for a platform that has some ethics.

**Comment by goobertron** [comment]
> having pro-active measures to protect young people (which are vulnerable persons) from disturbing content seem very desirable for a platform that has some ethics.

I agree. I don't see how the Diaspora can protect children against their will (as it doesn't force people to prove, or even provide, their date of birth); but we can certainly enable children to protect themselves.

**Comment by goobertron** [comment]
@ddsgdsg 'nsfw' just means 'not safe for work'. So it can (and ideally should) include anything that might possibly get someone into trouble if their boss walks behind them in the office and sees it on their screen. It doesn't mean 'adult material', although that seems to be what it is most commonly used for.

**Comment by SpcCw** [comment]
Perhaps better and easier solution would be an option to filter all NSFW content - set by default for new profiles. Then users can toggle it as they want ("...by clearing this checkbox I confirm I am at least 18 years old and agree to view content that might be of violent, disturbing or sexual nature...").  It is not just about age though as some people are uncomfortable seeing this type of content regardless of age.

When set on all NSFW posts should be filtered out of all streams including public one (not just collapsed or loaded in background).

**Comment by CSammy** [comment]
Duplicate of #7315
