### ISSUE TITLE
Posts of account not visible to others

### ISSUE THREAD

**Issue by MarkusWET** [diaspora/diaspora#7842]
Hi, I tried to check if this issue has been addressed/solved with 0.7.6.0 but I have no accounts on pods running the newest version. Behaviour seen at [diasp.eu (0.7.5.0)](https://diasp.eu) and [mondiAspora (0.7.4.1)](https://mondiaspora.net/)

## Expected behaviour
- Alice@podA adds Bob@podB / Bob@podB adds Alice@podA to some aspect
- Alice@podA posts something to an aspect which Bob@podB is part of (or public)
- Bob@podB accesses Alice@podA's profile and sees the post

## Actual behaviour
- Alice@podA adds Bob@podB / Bob@podB adds Alice@podA to some aspect
- Alice@podA posts something to an aspect which Bob@podB is part of (or public)
- Bob@podB accesses Alice@podA's profile and **does not see** the post

Please try to verify with [my diasp.eu account](https://diasp.eu/people/5f778a4096c1013525b64061862b8e7b) - As of now, there are  **12 public posts**. When accessing the profile from my alternate account on mondiAspora, I can see **one public post** from 2018-02-13. Same applies to aspect-limited posts, as described above.

**Comment by denschub** [comment]
Thanks for the report. However, this is, unfortunately, nothing we can act upon. In general, what you describe should work, and it usually does. If a post from Alice does not appear on Bob's pod, then Alices podmin should check their Sidekiq logs to see if the sending job worked, and Bob's podmin should check if receiving worked. We could provide support for the podmins on [Discourse](https://discourse.diasporafoundation.org/), and open a GitHub issue if it turns out to be one, but this could also be a case of temporary or hidden issues between those two pods. So, sorry, but I have to ask you to ping the podmins about that.
