### ISSUE TITLE
feature request: handling fake accounts

### ISSUE THREAD

**Issue by jayrope** [diaspora/diaspora#7847]
Certain (public, mostly music-oriented) posts are being "liked" here by users, that appear to have never posted anything (at least publicly) themselves. 

- What way could there be to find out if those are fake/robot-generated accounts and 
- how could they or new suspected auto-generated profiles be stopped from auto-liking future posts of mine, as well as 
- stopped from following me?

Those likes appear in a kind of regular fashion, every week there is just one more like by a different new profile, always using common, mostly English names. In other words, the regularity of those likes let's me suspect, that the accounts behind could be fake. 

Thanx for any insights.

**Comment by jayrope** [comment]
I am sorry to disagree. It is a software issue, because detection of fake accounts as well as user options to handle them are/should be enabled by the software. Let's call it a feature request, eventually.

**Comment by denschub** [comment]
Well, no, it is, in fact, not a software issue. I am ware of the accounts you mentioned in https://github.com/diaspora/diaspora/issues/7847#issue-352872153, but they have something in common: all of them are joindiaspora accounts. This is, by all means, a case of automated abuse of previous existing user accounts, and the only person able to investigate and mitigate that is the administrator of said pod. And they are aware.

The only possible "user option to handle them" would be somehow forwarding local reports to the right podmin (tracked in #7316), so you could use the report button to make joindiaspora.com aware. We could be discussing a method to auto-lock an account after a given amount of reports, but then again, this is nothing we can discuss here on GitHub as this is not an actionable item, as it needs more discussion. Also, it is a bad idea, as it makes abusing such a feature horribly easy.

Whoever is able to see your content is also able to like, comment, and reshare it, unless they are blocked, which would stop them from liking and commenting. diaspora\* allows you to block users, and it also allows you to limit the scope of people able to see the post in the first place.

In any way, this issue is not an actionable item, as it does not contain actual features to implement or actual bugs to solve. If you want to have a more generic discussion on how the software, the project, and the podmins can or should handle this, [our Discourse](https://discourse.diasporafoundation.org/) is the place to go. If a discussion there comes up with any *actual* action items, we can file them on GitHub and wait until some magic implements them! :)
