### ISSUE TITLE
Shareable Blocklists and Standardized TOS

### ISSUE THREAD

**Issue by Tectract** [diaspora/diaspora#7866]
Right now D* has an issue with controlling abusive and hatespeech accounts, including child pornography. We have no effective tools to prevent abusive users from flagrantly violating the terms of service and jumping from pod to pod. 

I propose that we standardized the TOS system so that there are standard TOS that pods can subscribe to, and each pod can maintain a blocklist of users associated with that TOS. Pods should be able to subscribe to the blocklists of other pods, such that I could import the blocklist from the bigger pods to prevent abuses on my smaller pod, based on which TOS they are enforcing.

Preventing hatespeech and child pornography on the D* network is not censorship, it's enforcement of a rational terms of service. Let's get this done because right now, we've got CP and hate accounts that are facing basically no repercussions. 

In my opinion, the FAIRNESS of a network in enforcing a rational TOS is a critical factor in the quality of the social network itself. Right now, D* is struggling because there are no effective moderation tools.

**Comment by SuperTux88** [comment]
As I told you before, this was already discussed on discourse and will not happen in diaspora. The risk of abuse of such a system is too high. Also diaspora doesn't need something like that, it works pretty well as it is now. You can either report a problematic user to their podmin, and if the podmin is inactive or ignores you, you can report it to your podmin and they can then remove the user locally (or in your case, you as a podmin can do it yourself). This already worked pretty well with multiple problematic users in the past and it also worked for ‘Islamic State’ propaganda accounts which were created on different pods, see [this blog post](https://blog.diasporafoundation.org/5-dealing-with-problem-content-in-a-distributed-system).

As [announced](https://github.com/diaspora/diaspora/issues/7464#issuecomment-421517315) I'll block you from GitHub too, because it looks like you don't want to listen and you'll just create another issue with the same thing.

And if you really need such blocklist, just start one yourself and ask other podmins to block everybody on this list.
