### ISSUE TITLE
@Mentions in Comments do not pop up picklist

### ISSUE THREAD

**Issue by lunagloaming** [diaspora/diaspora#7877]
Although @mentions in comments work (e.g. @{user@pod}), they do not appear to pull up the helpful pick list like they do in new posts, at least on my pod.

I would expect @mentions to work the same in both posts and comments.

**Comment by Flaburgan** [comment]
Hi @lunagloaming and thank you for reporting a possible bug in diaspora*.

First of all, the autocomplete mention feature isn't implemented in the mobile version of diaspora* (see https://github.com/diaspora/diaspora/issues/4817) but I guess you were using the desktop version.

Mentions in comments are a bit different than mentions in posts because of content visibility.
You should be able to mention anyone in a comment made **on a public post** but you can only mention a user **who already interacted with a post** for a limited post. This limitation is there to be sure to not mention someone who doesn't have access to the post. There surely is room for improvement there but that's the current situation.

Can you confirm you're not falling in that case by trying to mention someone in a comment on a public post? Thank you.

**Comment by lunagloaming** [comment]
OK, here is the use case... there is a post which I feel another friend might be interested in.  I do not know the limits of the original post, nor should I (aspect names being private), however there is a chance that the mutual friend might have access and I'd like to call their attention to the post.

On Facebook, I can @mention them regardless of the original post's visibility... it might not do anything if they don't have access, but it is allowed.  And if they do have access, they'll see the mention and be directed to the relevant post.

**Comment by goobertron** [comment]
By design, diaspora\* respects the wishes of the original poster as to who will be able to see what they have posted. It therefore doesn't allow another person to change that scope. Mentioning someone not in the original scope, if it gave that person access to the content, would 'leak' the content to someone whom the original poster didn't intend to see it. This is a case where what Facebook allows is, although it might be convenient, not necessarily a good thing.

As it's not possible to give someone access to limited content in this way, there's no point having a UI that mimics the 'mention' UI but performs no function. So it was decided not to enable the act of @-linking an account in a comment on a limited post unless that person had already interacted with the content, thereby demonstrating that they are part of the scope of that content.

You can read how the decision was reached to limit mentions in comments in this way in [this discussion](https://discourse.diasporafoundation.org/t/mention-users-in-comment/177/22).

Hope that helps clear things up!

**Comment by denschub** [comment]
This isn't a bug, and although this could resolve into a feature request, this discussion is best started/continued in Discourse. See the previous comment for a link.
