### ISSUE TITLE
birthday notification of a closed account

### ISSUE THREAD

**Issue by norayr** [diaspora/diaspora#7936]
i got a birthday notification of a person who's closed the account years ago.

diaspora version is 0.7.7.0.

**Comment by Flaburgan** [comment]
Can you please indicate your pod and the user full ID ?

**Comment by norayr** [comment]
spyurk.am
/people/e86d647ec17aaf97
sent you jid on irc in private.

**Comment by SuperTux88** [comment]
That's weird, when an account is closed, the birthday date is cleared, so it can't trigger a birthday notification, because there is no birthday anymore. Maybe the podmin did modify the database and manually set the closed flag without running the account deletion? Or the account deletion didn't run properly, there was a bug in the past a long time ago, but in the upgrade-guides was a command to rerun them again, maybe that wasn't executed?

**Comment by norayr** [comment]
i am the podmin. i did not mess up with database.
may be something failed.

so if you think it is hardly a bug then lets close the issue.

**Comment by norayr** [comment]
i can see the birthday in admin console.
and the account is marked as deleted anyway.
but the deletion was four years ago, so may be four years ago code did not clean the birthday.

**Comment by norayr** [comment]
sorry, somehow missed this reply.
running the check, let's see.

**Comment by norayr** [comment]
Running account deletions...

its running and deleting!

thank you!
