### ISSUE TITLE
Why # and * are backslash escaped in XML messages?

### ISSUE THREAD

**Issue by MrPetovan** [diaspora/diaspora#7952]
Sorry if this has been discussed already, I received yet another Diaspora message on my Friendica node where hash characters `#` are prefixed by a backslash `\`.

Here's the full XML message:
```xml
<status_message>
  <author>wotd@pod.jpope.org</author>
  <guid>f7422b40f0e10136685535162d7f1629</guid>
  <created_at>2019-01-02T17:30:04Z</created_at>
  <public>true</public>
  <provider_display_name>wotd bot</provider_display_name>
  <text>### [rentier](https://wordsmith.org/words/rentier.html)

noun: A person who lives on income from rent, interest, etc.

\#WOTD \#Wordsmith \#rentier

Via &lt;https://wordsmith.org&gt;
</text>
</status_message>
```

Is it an expected Markdown feature?

**Comment by SuperTux88** [comment]
Well, it looks like it's the author doing it. While escaping `*` is to prevent formatting (for example for `diaspora\*`), I never saw somebody escaping hashtags. But I just noticed it breaks hashtags parsing for diaspora too, the post isn't linked with any of these tags. So maybe that's intended by the author of this post (I still don't understand why? why adding hashtags when you don't want them to work)?

But backslash escaping is a markdown feature: https://spec.commonmark.org/0.28/#backslash-escapes (so that's perfectly fine markdown)

**Comment by goobertron** [comment]
You're right, @SuperTux88 , it does appear to be something added by the user. As it's a bot, it might be an improperly set-up bot.

I've just compares the JSON for that post and another post using hashtags, and the back-slashes are not added to the JSON in the other post. I also compared a post by a different bot, and that didn't add back-slashes before the tags either, so it appears to be the way that particular bot has been set up. Looking back at its previous few posts, they are all coded the same.

ps: I like it – a 'word of the day' bot that posts every few months...

**Comment by MrPetovan** [comment]
And yet the original post shows the hashtags: https://pod.jpope.org/posts/f7422b40f0e10136685535162d7f1629

So it seems to be specific to the XML output.

**Comment by SuperTux88** [comment]
No, the backslashes are not only in the XML, they are everywhere (in the database, in the json sent to the frontend, and obviously also in the XML sent to other pods), but as in the commonmark spec, the backslash aren't shown, so `\#` just renders as `#`.

**Comment by MrPetovan** [comment]
Got it, thanks for the explanation.
