### ISSUE TITLE
Don't generate a notification for "User commented on a deleted post"

### ISSUE THREAD

**Issue by Siedlerchr** [diaspora/diaspora#7957]
Hi,

I got a notification that someone commented on a deleted post. Obviously, this doesn't have any information value as I can't see the deleted post as it is removed (which is the whole purpose of deleting a post).
So I suggest not generating a notification for this. From what I see, #1344 implemented showing a message that the comment got deleted. But as I've written before that information has no value.

![commentedondeleteddiaspora](https://user-images.githubusercontent.com/320228/50954453-aa94e980-14b6-11e9-9dff-b10a91f75f62.PNG)

**Comment by Flaburgan** [comment]
@Siedlerchr that is not how things are going: obviously, when the user commented on the post, the post wasn't deleted. So the notification was sent at that time, and there is no way diaspora* could guess that the post will become deleted. Then, the author deleted the post, so we don't want to link to it anymore, that would be a 404. So we change the displayed text of the notification to indicate that the post doesn't exist anymore so users don't search for it wondering what happened.
We could have removed the entire notification at the same time the post is removed instead of changing its text, but this doesn't seem like a good idea to me, as users could wonder why something disappeared. For example, I have diaspora* open at work but I don't read it. I sometimes check the notifications and see I have a new one. I'm then like "nice, I'll read that when back home this evening. Then during my trip, the author deletes the post. When I open diaspora* at home, with your suggestion, the notification will not be displayed anymore and I will wonder where it goes. In the current situation, I know what happened even if I can't do anything about it.

**Comment by Siedlerchr** [comment]
Ah okay, thanks for the info!
