### ISSUE TITLE
German Website login to complicated

### ISSUE THREAD

**Issue by Sebastian3001** [diaspora/diaspora#7985]
Hi Guys,

I set up an account quite a while ago and now I tried to log into my acoount.
As I'm from Germany I was shown this website https://diasporafoundation.org/
I was searching for a "log in" button. It simply does not exist.
When I click on register I end up on this wired website https://podupti.me/

Consider me as a standard user, I've got no "nerd factor" I just wanna use diaspora.
What I can give as a feedback - this is not the usability I am looking for when searching for an alternative to fb. I want to login within less a minute. 

For my personal taste the front page of https://diasporafoundation.org/ is also not adressing the average social media user, unstructured, to much text, to much picutures inbetween, chatotic. But maybee that's not the goal and I'm simply not part of the target group. 

Please see my fedback as constructive cricism. I would love to see diaspora growing.

Best,
Sebastian

**Comment by jhass** [comment]
diaspora* is a software that provides a distributed social network, think of it like an email server. You have to remember your provider, like you cannot sign into Yahoo mail using your Google account or vice versa, you cannot sign into any installation of diaspora* with an account you made at another.

**Comment by steffenlyng** [comment]
I agree that getting started with Diaspora seems pretty complicated for new users - and I'm wondering if @Sebastian3001 doesn't have a point that this is something that scares off people from even bothering. 

Since I understand the distributed nature of disapora it wasn't complicated to understand why I need to pick a pod, and remember my initial provider. 

But perhaps we could help new users to an "entry" pod, and they can learn more from there. Getting people on board seems quite important - more than having them understand the nature of diaspora to begin with.

**Comment by goobertron** [comment]
As Jonne said, the nature of diaspora\* means that you can't simply 'sign up' without selecting a pod, either manually by choice or by using an automated tool.

There is no way around that while respecting user choice/control, which is a core concept of diaspora\*. That said, it should be possible to make the process simpler, and it would be a great boost to the project if this can be done.

This isn't a technical issue so much as a design issue, and it needs discussion in order to find the best way (if there is one) to improve the initial learning and sign-up process. GitHub is therefore not the place for this to take place. If you have ideas how to improve the process, please contribute to [this discussion](https://discourse.diasporafoundation.org/t/1356/30) on the project's Discourse forum. If you don't have an account there, you can sign in using your GitHub account.

I think there's already a place-holder issue in GitHub about the sign-up process, so this one could be closed.
