### ISSUE TITLE
Link to reshares instead of profiles

### ISSUE THREAD

**Issue by DeusFigendi** [diaspora/diaspora#7989]
When a post is reshared, the desktop view generates a list of users who reshared a post:

![reshares](https://user-images.githubusercontent.com/1711504/55258029-f52a3480-5261-11e9-97da-b897ba1fdcdd.png)

These Avatars link to their owners profiles. That seems to be very logical but not always handy :)

Because when I check the reshares, I most likely want to find the reshares and not their owners.
Typical situations are when I asked a question and my problem got solved I probably want to inform the resharer and the readers of the resharers it's done. Or my own post is old and I want to check all the comments once made on the topic, on the OP but also on reshares.

Plus: Changing this would not mean much a loss of usability because:

1. Hovering the avatar with a point device brings up the hover card of that user and **that** contains a hyperlink to the users profile too.
2. When linking to the reshare it is only **one** click more to find the users profile if that was the users aim.

So to make it clear, what I suggest is: The list of reshares should link to the reshares not to the resharers. The hover card is fine.

**Comment by SuperTux88** [comment]
With #4219 in mind, where reshares wouldn't be their own post anymore in the futures (so nothing to link to), I suggest we can close this again (since it probably doesn't make much sense to add it only to remove it again).

But even you want to keep this open, I think this wouldn't be good UX, because avatars **always** link to the profile, so:
1. People wouldn't try it, because you don't expect it to happen
2. People who want to go to the profile and click on the avatar would be confused

> Hovering the avatar with a point device brings up the hover card of that user and that contains a hyperlink to the users profile too.

That would even make the UX worse, because you then need to click fast (not much time to aim), because if you wait a second too long the hovercard would block the link to the reshare again.

**Comment by DeusFigendi** [comment]
> With #4219 in mind, where reshares wouldn't be their own post anymore in the future

Ah okay in that case… nevermind.

(on the other points I disagree but there's no reason to argue, at least not in an issue)
