### ISSUE TITLE
Missing space between captcha image and text at sign up

### ISSUE THREAD

**Issue by Waithamai** [diaspora/diaspora#8016]
On some pods, the text next to the captcha when registering is positioned incorrectly, with the first words hidden behind the captcha image. It seems to be broken on pods with the dark theme as default, while the default theme looks okay. 

![Screenshot sign up fields in dark themed nerdpol ch](https://user-images.githubusercontent.com/3577985/57774118-f9c78100-7719-11e9-9072-9e5e1899aa83.png)

![Screenshot sign up fields on default light themed pod](https://user-images.githubusercontent.com/3577985/57774227-43b06700-771a-11e9-91a4-ee55f649ef9f.png)

**Comment by SuperTux88** [comment]
It looks like this is a regression from #7896, because of [this change](https://github.com/diaspora/diaspora/pull/7896/files#diff-6d3da0be5dbca60cf86d9febd12659c6L1). With `.action-new` it's displayed correctly. So it doesn't depend on the dark theme (my pod is just more or less the only one with open registration and this change already deployed, because this isn't released yet).

**Comment by Flaburgan** [comment]
I also noticed that on my pod, I can confirm this.

**Comment by Flaburgan** [comment]
I'm working on a fix.
