### ISSUE TITLE
pod stream not loading anymore...

### ISSUE THREAD

**Issue by hknet** [diaspora/diaspora#8051]
Hi
we run into a "no stream loading" situation on our pod and I have absolutely no clue on how to fix this...
in the end the JS console reports this:

console.trace() Unable to create user prefix jsxc-2b7d12c3001fbd9dafd91290a5c5f089e0e3f4ec8a8010a41aabe1dda0ea62ef.js:44:11840
    getPrefix https://diaspora.kapper.net/assets/jsxc-2b7d12c3001fbd9dafd91290a5c5f089e0e3f4ec8a8010a41aabe1dda0ea62ef.js:44
    getItem https://diaspora.kapper.net/assets/jsxc-2b7d12c3001fbd9dafd91290a5c5f089e0e3f4ec8a8010a41aabe1dda0ea62ef.js:44
    getUserItem https://diaspora.kapper.net/assets/jsxc-2b7d12c3001fbd9dafd91290a5c5f089e0e3f4ec8a8010a41aabe1dda0ea62ef.js:44
    get https://diaspora.kapper.net/assets/jsxc-2b7d12c3001fbd9dafd91290a5c5f089e0e3f4ec8a8010a41aabe1dda0ea62ef.js:43
    init https://diaspora.kapper.net/assets/jsxc-2b7d12c3001fbd9dafd91290a5c5f089e0e3f4ec8a8010a41aabe1dda0ea62ef.js:42
    init https://diaspora.kapper.net/assets/jsxc-2b7d12c3001fbd9dafd91290a5c5f089e0e3f4ec8a8010a41aabe1dda0ea62ef.js:41
    <anonym> https://diaspora.kapper.net/assets/jsxc-2b7d12c3001fbd9dafd91290a5c5f089e0e3f4ec8a8010a41aabe1dda0ea62ef.js:45
    jQuery 4

any suggestions are very welcome (also to go away from here and ask somewhere else)

thx
hk

**Comment by denschub** [comment]
Usually, [our Discourse](https://discourse.diasporafoundation.org/) is the place to ask for support. :)

This error is related to the chat integration, which unfortunately, we can't really support at the moment because it's based on some known-to-be-broken tech and there is nobody left to maintain it. [There are discussions to remove it](https://discourse.diasporafoundation.org/t/removing-diaspora-s-current-chat-integration/2718?u=denschub), so it's probably gone sooner or later. For now, to get your pod running, it's probably easiest to just disable the chat integration in `diaspora.yml` and restart diaspora\* after making the change. The stream should be back, but without the chat.

If you have further issues, please head over to Discourse! :)
