### ISSUE TITLE
Private pods

### ISSUE THREAD

**Issue by beppeben** [diaspora/diaspora#8080]
Hi,

Are private (family) pods possible? I'm a bit confused as I read from wikipedia the founders saying that

"You can have a pod all to yourself, or one for just you and your friends, or your family, giving you complete ownership and control over your personal social information (including your identity, your posts, and your photos) and how it's all stored and shared."

But then on the diaspora wiki:

"Can I make my pod private/isolated/not communicate with other pods? No."

Could you please clarify what's the actual situation?

Thanks.

**Comment by goobertron** [comment]
Hello,
Please could you post your question in the support category of diaspora\*'s Discourse forum? https://discourse.diasporafoundation.org/

Github is for identifying and fixing technical issues, not for general questions.

In short answer: diaspora\* is a federated network, in which nodes (pods) all communicate with each other. It is possible for an admin to break this federation, but it's not recommended. However, the way to choose who sees what you share is by using aspects. If you set up a pod for the use of your family and each family members adds all the other members to their aspects and then shares to those aspects alone rather than publicly, only the people on your pod will be able to see that content. The pod therefore acts in effect like a private pod.

Pods only federate with other pods with which a user has set up a sharing relationship; so, if none of the members of your pod start sharing with someone on another pod, your pod will likely not federate with any other pod.
