### ISSUE TITLE
how to login to joindiaspora.com via mastodon.social ?

### ISSUE THREAD

**Issue by skywinder** [diaspora/diaspora#8104]
1) https://joindiaspora.com/users/sign_in - says, that you can log in via other pods.
2) according to link in 1) https://podupti.me/ - mastodon network is one of the pod
3) if so, doest it mean, that following integration completed?
3.1) if so, what should I put into login/password on https://joindiaspora.com/users/sign_in ?

(I tried @skywinder@mastodon.social , skywinder@mastodon.social , @skywinder ) - nothing works.

**Comment by skywinder** [comment]
might be related: https://github.com/tootsuite/mastodon/issues/780

**Comment by jhass** [comment]
joindiaspora.com is historically one of the biggest (in terms of users) servers running diaspora. So in order to encourage the decentralization of the network, its administrators decided to close registrations and refer to users to other servers for sign up. This is meant for registration, diaspora doesn't have nomadic identities, you have to use the server you registered at, same as you cannot sign into gmail using your hotmail account. So the wording might be a bit confusing there. 

Second part is the same as the response to your other comment, so crossposting: 

Podupti.me used to exclusively track diaspora installations, that's why it has pod in it's name, which is diaspora brand terminology for a server. Hence it is widely referenced inside the diaspora project, also out of a lack of alternatives. 

As other projects such as friendica added compatibility layers in order to communicate with diaspora, it started listing those severs too, which kind of made sense since you could consider it one network. 

Unfortunately with the ActicityPub wave, its maintainers decided to jump onto that and list those projects, and even others, too. All the while making an, to be honest, terrible job at presenting and grouping the different network technologies to show which servers and projects are compatible with each other. The metadata for knowing that is there, it's just not used... So yeah, there's space for a new fediverse sever index project ;) 

Neither joindiaspora.com not podupti.me is run by active developers of of the diaspora software, so nothing to be done here :)

**Comment by skywinder** [comment]
thanks, @jhass for the detailed answer. In this case, I would ask to update details in https://joindiaspora.com/registrations_closed since it's very confusing, where to go to register.

Can you recommend some list of servers, where registration is open? (I found https://diasp.org/ as one of the most popular next to you (yeah, it's not very good for decentralisations, but it's probably good sign, that this server will stay online for a long run, right?)

**Comment by skywinder** [comment]
so, still can't login via my account on  https://diasp.org/ (tried skywinder@diasp.org / skywinder )
which password should I use ( same as on main pod) ? or how to set password?

**Comment by jhass** [comment]
joindiaspora.com is run by a community member, not by the project itself. So no I/we cannot update it.

Diaspora doesn't support nomadic identities, you cannot login into joindiaspora.com with your diasp.org account, only into diasp.org itself. This is the same email, you cannot log into hotmail with your gmail account either. But you can still exchange messages between the two.

Unfortunately there currently is no better resource than podupti.me. In the software column you have a dropdown which you can use to filter down to just diaspora installations.
