### ISSUE TITLE
Add a "contact the podmin" method

### ISSUE THREAD

**Issue by denschub** [diaspora/diaspora#8139]
Currently, there is no way for non-logged in people to contact a podmin on a unified channel. Some pods expose an email address in their Terms of Service, but not all do. NodeInfo exposes the username of the admin account, but that's not great, as you need to have a diaspora\* account to send messages to that.

We could build a simple "contact form" on a well-known URI that allows people to send an email to `podmin_email` if it's set. This would resolve some issues we have when people try to get in touch with their podmins for account-related questions, and it would also make reporting contents easier between podmins.

Spam protection might be a hard issue, though, as we can't rely on "more robust" solutions like ReCaptcha, so this will likely need some careful consideration.

**Comment by SuperTux88** [comment]
> Spam protection might be a hard issue, though, as we can't rely on "more robust" solutions like ReCaptcha, so this will likely need some careful consideration.

Personally I'd rather have the mail-address listed public somewhere instead of a contact form, because I think it's easier to spam-filter plain mails instead of contact-form-mails sent by diaspora containing spam ... and I think we can all agree that a captcha wouldn't help much for spam. I have also all well-known common addresses (abuse@, webmaster@, postmaster@ and @hostmaster@) configured on my domains, and I don't receive much spam on them, but if we want to we could also hide the mail-address behind a captcha?

**Comment by denschub** [comment]
Just listing the email address would also be significantly easier. Probably works as well, as long as it is placed on a known URL, maybe linked in the footer, and can't be accidentally removed. :)
