### ISSUE TITLE
change the email address of the account - BUG

### ISSUE THREAD

**Issue by asteree** [diaspora/diaspora#8269]
I do not receive the activation link on the email address. The email address is correct, but I receive all exchanges on an old gmail address. 
How can I deactivate gmail?
How do I activate the correct address?
How can I avoid receiving all email exchanges?
Thanks for help me - I can't develop on github... Thank you very much

**Comment by SuperTux88** [comment]
Assuming this is from the same person who also asked in IRC, maybe @Flaburgan wants to have a look at this and why some mails from diaspora-fr.org don't work (or to some recipients, as some mails seem to work? Or maybe the mail also just landed in the spam folder?).

@asteree for support please use discourse (https://discourse.diasporafoundation.org/c/support/14) instead of GitHub, or reach out to your podmin directly (`podmin@diaspora-fr.org` on diaspora).

> How can I avoid receiving all email exchanges?

You can just disable all email notifications in your settings.
