### ISSUE TITLE
Error 403 forbidden with a loadblancer

### ISSUE THREAD

**Issue by jon-bit** [diaspora/diaspora#8270]
I'm sure this is a easy fix but, I'm running a diaspora inctence on centos 8 and I can not get it to work. I'm useing the zevenet loadblancer. when I try to get to the website I get. 

`2021/07/12 11:59:17 [error] 85111#0: *1 directory index of "/home/diaspora/diaspora/" is forbidden, client: 172.16.52.200, server: mywebsite.com, request: "GET / HTTP/1.1", host: "mywebsite.com"` with a 403 error where 172.16.52.200 is the loadblancer using backend https. I also have a wildcard cert on the loadbalancer witch I would like to use but I can't at the moment.

Thank you to everyone who helps :)

**Comment by jon-bit** [comment]
And BTW I fallowed the instructions completely.

**Comment by goobertron** [comment]
Hi there, this looks likely to be an issue with your setup somewhere rather than in Diaspora's core code-base. The place to ask for support like this is in the podmin support section of Diaspora's Discourse forum: https://discourse.diasporafoundation.org/c/support/podmin-support/15

You can sign in there with your GitHub account. Alternatively, shout out on IRC – details here: https://wiki.diasporafoundation.org/How_we_communicate#IRC

Good luck.
