### ISSUE TITLE
False positive Test? Following user not respected? 

### ISSUE THREAD

**Issue by tclaus** [diaspora/diaspora#8278]
Hi - 
This test seems to be result in a false positive: 
https://github.com/diaspora/diaspora/blob/d02848c216f4e8068476ead14d5d0a622315a4ce/spec/lib/evil_query_spec.rb#L26
![Bildschirmfoto 2021-08-04 um 18 53 58](https://user-images.githubusercontent.com/501326/128222336-595c10b0-6be0-4fd3-963f-787cbb30870b.png)

The point is: 
- the expect for not include(public_post) should be a 'include' public post. (because Its public, and user is not blocked)= 
- the next line: not include private_post is OK. But the reason WHY this list is empty is different: 

evil_query is runs by Context user "Alice". 

Make relation method: 
https://github.com/diaspora/diaspora/blob/d02848c216f4e8068476ead14d5d0a622315a4ce/lib/evil_query.rb#L62

![Bildschirmfoto 2021-08-04 um 18 56 53](https://user-images.githubusercontent.com/501326/128222696-0b7e216d-31b7-4c58-aa50-40317133a573.png)

It collects the IDs from Posts-by-Aspect, the Posts-By-tags and Posts-by-Mentions, right? 
During runtime, `aspects_post_ids`! is empty every time. Right? 
`followed_tags_posts`! is also empty ( No posts with any tags - right) 
and no mentions - correctly empty. 

So this method returns and empty result every time, no privates and no public post, which I think is horrible wrong? 

So what should the make_relation! method correctly return?

**Comment by SuperTux88** [comment]
This is correct as it is. The tests run as user alice (as you already said), eve created a public post (which alice can see), and eve added alice to her aspects, and shared a private post to that aspect, so alice can also see that post. But if alice doesn't also follow eve, these two posts don't show up in the stream of alice, which is what this test is testing.

`make_relation!` is used in the main "stream" which shows posts from people you follow, from tags you follow, from people who mentioned you and from community-spotlights (if enabled). Non of these is the case for the two posts eve created, because alice doesn't follow eve, the posts neither contain tags or mentions, and community-spotlights aren't enabled.

So this test checks that if eve shares with alice, but alice doesn't share/follow back, then eves posts don't show up in alices stream (so eve can't force alice to view her posts if alice doesn't want to), so both the `make_relation!` and the test are correct.

**Comment by tclaus** [comment]
Thanks for clarification. 
My false attempt was, that the '`followed_tags_post`' meant to return just the followed tags from PUBLIC posts. That was my false assumption. 
Thank you.
