### ISSUE TITLE
Develop is failing CI

### ISSUE THREAD

**Issue by weex** [diaspora/diaspora#8279]
This happened with the last merge from next-minor into develop.

It's failing on test (2.6, postgresql, cucumber)

https://github.com/diaspora/diaspora/runs/3157102492

**Comment by SuperTux88** [comment]
There are some cucumber tests that don't run stable and fail every now and then, so this is "normal" and we know it failed. If all other tests are green, and especially since next-minor also was green, this can safely be ignored.

If you want to help making some tests more stable, have a look at #7373
