### ISSUE TITLE
Deleting join diaspora account

### ISSUE THREAD

**Issue by Farcidiacono** [diaspora/diaspora#8283]
Hello
I cannot login, reset my password and cancel my joindiaspora account.

I tried my mails address but I do not receive any mail to reset my password and login. Thus, I would like to delete the account. 

How to do that? Any contact of the support department? Thanks

**Comment by goobertron** [comment]
Hi there,
Github is a tracker for issues with the core Diaspora software code, and not a place to give individual support. The place to get support is from [our Discourse forum](https://discourse.diasporafoundation.org/c/support/14). However, hopefully you won't need to do that.
Because Diaspora is fully decentralised, only the admins of a pod can deal with account issues. You can contact the admins of joindiaspora via the email address at the foot of the Terms of Service page: https://joindiaspora.com/terms
Hopefully they will be able to help you restore access to your account so you won't need to delete it.
I'll close this issue now. If you don't have any success via that email address, feel free to open a support ticket in the Discourse forum, and people there will see if they can get a response from the JD.com podmins.
Good luck!
