### ISSUE TITLE
Gallery links don't work on Mozilla Firefox

### ISSUE THREAD

**Issue by Cesese** [diaspora/diaspora#8352]
# Versions
Diaspora* 0.7.15.0 / 0.7.16.0 (I tried on 2 different pods)
Mozilla Firefox for Arch Linux 100.0 (64-bit)
# Problem
I use Firefox, and a friend of mine uses Safari. Both of us aren't logged in.

- My friend sent me this link https://iviv.hu/people/bfe281001b5a8561/photos/127981 and it shows a blank page for me.
- They tried sharing it from another pod https://pod.dapor.net/people/b29871b0fdf4013827ac10bf487fe7cf/photos/1163493, but it still had the same result.
- Then, we found that this link https://iviv.hu/posts/609670 works.
- Later they tried opening the gallery link on their firefox, and it also didn't work.

I didn't try on a pod on latest version (0.8.0.0) but I don't see anything in the changelog implying that this was fixed.

**Comment by goobertron** [comment]
I think that the problem is not with Firefox but that you're trying to view invalid links to images.

I believe that image files themselves aren't federated to remote servers; that is, they're not stored on any server except the one the account that uploads them is based on. So, when you view an image on a remote pod, your pod fetches the image from the poster's server.

If you visit the account in question in your pod, then select the Photos tab, find the photo you want and select 'View image in new tab' from Firefox's floating menu, you'll get a link to that account's home pod that ends in `.jpg` – which is what links to images look like: `https://originating-pod.tlf/uploads/images/[guid].jpg`. 

And I think that is the only way to share a direct link to an image rather than a post with an image in it (which is what the working link you posted is).

So I'm pretty sure there's no bug here, just an attempt to share images in a way that's no intended to work.

**Comment by Cesese** [comment]
It's not a direct link to the picture my friend wanted to send me, but a link to the post. Also this issue is specific to firefox, they tried the link on their phone before sending it to me and it worked.

If the gallery links are really invalid, then why do they work on my friend's phone? And why don't they show an error instead of a blank page?

![Screenshot of the phone's web browser showing the post correctly without being logged in](https://lutim.stemy.me/b46nUlbH/PZ1ZiSdI.jpg)

**Comment by goobertron** [comment]
The first two links you posted are not valid links to a post but to an image, which is not usually viewable that way. If they wanted to send you a link to the post, then https://iviv.hu/posts/609670 would have been the correct link; or, even better, click on the timestamp on that post to reveal the post's guid – https://iviv.hu/posts/59ee0f90856d013a52cb543d7eeced27 – and send that to you so that you could view it in your own pod.

I've just looked into this a bit further and indeed it is possible to view an image directly in a phone browser without being signed in to that pod – and I don't think this is supposed to happen, especially if the image was uploaded to a limited-scope post.

And the browser in which the links 'worked' on my phone was Firefox, whereas I've tried Firefox, Opera and Safari on desktop with no success, so it's not an issue specific to a browser but to a platform, and is perhaps a weakness in the mobile version of the site.

Why the pages are blank on desktop rather than being a 404 or other error, I'm not sure, but I don't think such links have ever worked on desktop, and indeed I don't think it's possible to generate such links to images on desktop – as I said before, when I tried it, I got a link ending .jpg to the image on the host server.

Thanks for raising it.
