### ISSUE TITLE
Unicode characters are not displayed

### ISSUE THREAD

**Issue by memo-567** [diaspora/diaspora#8435]
Unfortunately, diaspora doesn't seem to be up-to-date here.

![pod mv2k com -  2023 - 08 - 25  08 - 58](https://github.com/diaspora/diaspora/assets/58190287/d68d0935-b93a-4162-952f-a44eb3045d04)

I'm aware that there's a chance some developers might not like emojis, but they're standard these days.

**Comment by Flaburgan** [comment]
Hello @memo-567 and thank you for taking the time to open an issue. Can you please tell us which pod you're running on? Thank you.

**Comment by memo-567** [comment]
I'm running the latest official Version 0.7.18.2

**Comment by memo-567** [comment]
btw: 

I missed saying "**not all** unicode caharcters".

**Comment by denschub** [comment]
Are you on MySQL or Postgres? Did you ever migrate database engines?

**Comment by denschub** [comment]
Well, actually, no. It's not a setup issue. It's a client issue. Because [even on the origin pod](https://pod.geraspora.de/posts/e5e941702541013c8632060a1d1a2d95), emojis work fine:

<img width="800" alt="Screenshot 2023-08-25 at 15 44 20" src="https://github.com/diaspora/diaspora/assets/344777/e6649a68-50a7-4b75-be60-febe2b4cac27">

It's possible that you have some weird browser addon that messes things up. Or maybe you're on Linux and don't have an Emoji font installed (and your browser isn't shipping one, or something). Either way, this is not diaspora\*s issue - it's something on your end.

**Comment by memo-567** [comment]
Thank you for your prompt reply.

In the meantime, I have found the reason. It seems Windows doesn't support Unicode flags in general.

However, since other programs and Fediverse systems also, can display and do this, there seems to be a solution that their developers use.

It would certainly not only be of interest to me, but also to other Diaspora users if this were also integrated into the Diaspora code.

**Comment by denschub** [comment]
> It seems Windows doesn't support Unicode flags in general.

Then use a browser that does work around that. Firefox, for example [works around that](https://emojipedia.org/mozilla):

> On Windows platforms Firefox uses [Twitter's Twemoji](https://emojipedia.org/twitter/) designs for [flag emojis](https://emojipedia.org/flags/), which have never been supported by [Microsoft's](https://emojipedia.org/microsoft/) emoji set.
